In [1]:
%cd ../

/Users/harrysonghurst/Documents/Coursework/L48 Machine Learning and the Physical World/TrafficEmu


In [2]:
# If you get a SciPy error when installing Emukit, build it from source:

# git clone https://github.com/amzn/Emukit.git
# cd Emukit
# pip install -r requirements/requirements.txt
# python setup.py develop

In [3]:
import numpy as np
import pickle
import emukit as ek
import GPy

from emukit.model_wrappers import GPyModelWrapper
from emukit.experimental_design.experimental_design_loop import ExperimentalDesignLoop
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.core.initial_designs import RandomDesign, latin_design
from emukit.experimental_design.acquisitions import ModelVariance, IntegratedVarianceReduction
from emukit.core.loop import UserFunctionWrapper
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.bayesian_optimization.loops import BayesianOptimizationLoop
from emukit.core.optimization import GradientAcquisitionOptimizer
import matplotlib.pyplot as plt
import seaborn as sns

from sumo_grid_simulation.grid_simulation import Simulator
import experimental_design.config as config

sns.set()

### Pseudocode

Fitting a gaussian process to a simulator using Emukit takes the following form (taken from L48 lectures):

```
initialize GP with some randomly chosen points
while stopping condition is not met:
    compute candidate point(s) using GP and acquisition funciton (model_variance) -> new point
    evaluate this new point with our simulator/user function -> observation
    update model with new observation -> new GP
```

### Simulator

In [4]:
simulator = Simulator(end_time=300)

### User Function
 
This is the function we want to understand. Namedly, how are CO2 emissions and timeLoss (the time lost due to driving below the ideal speed) affected by the following parameters: 

```
gridSize: the size of the grid network where the simulation is carried out
edgeMaxSpeed: legal speed limit in m/s - this can be exceeded (11.11 == 40km/h)
maxSpeed: the absolute maximum velocity of any vehicle in m/s (55.55 == 200 km/h)
edgeLength: length of the roads between intersections in meters
numLanes: number of lanes per road
accel: The acceleration ability of vehicles in m/s^2.
```

*A complete list of parmeters analysed is discussed in our report.*

In [5]:
def user_function(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function time loss called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, edgeLength, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.2
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * edgeLength / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            edgeLength    = edgeLength,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average co2 / average route duration
        CO2 = s['CO2']/s['num_emissions_samples']
        # average emissions / average route length
        result.append(CO2/s['routeLength'])
        i += 1
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

### Model Inputs / parameter space

In [6]:
gridSize = DiscreteParameter('gridSize', domain=[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
edgeMaxSpeed = ContinuousParameter('edgeMaxSpeed', min_value=8, max_value=19)
edgeLength = ContinuousParameter('edgeLength', min_value=30, max_value=70)
numberOfLanes = DiscreteParameter('numberOfLanes', domain=[1,2,3])
accel = ContinuousParameter('accel', 1.5, 5.)

parameter_space = ParameterSpace([gridSize, edgeMaxSpeed, edgeLength, numberOfLanes, accel])

### Get init and test points

In [7]:
design = RandomDesign(parameter_space)
init_X = design.get_samples(20)
init_Y = user_function(init_X)

design = RandomDesign(parameter_space)
test_X = design.get_samples(100)
test_Y = user_function(test_X)

[[16.         14.26673765 42.26563219  1.          3.3250345 ]
 [ 5.         11.99550728 53.22371287  2.          1.84254406]
 [10.         13.42157625 47.8207475   3.          2.62849847]
 [19.         10.99085753 37.5983005   3.          1.64518036]
 [ 5.          9.99053082 43.83530281  2.          3.18764036]
 [14.         10.6573746  32.92800549  2.          3.24687241]
 [16.          8.96021016 52.85024401  3.          3.31964014]
 [15.         16.38373519 38.66565652  3.          3.77951955]
 [20.         12.63518694 40.46642563  3.          4.42391479]
 [20.          9.38254641 37.95138823  1.          2.45156313]
 [14.         10.67463094 40.85488606  2.          3.61766387]
 [ 8.         18.94882678 57.57934457  3.          2.8185991 ]
 [17.         16.66219944 36.6487441   1.          2.38244049]
 [ 4.         15.50793326 41.86086832  3.          4.45706677]
 [19.          8.47763026 59.05202552  1.          4.22648744]
 [12.         10.95792113 47.53915507  2.          1.55

 Retrying in 1 seconds

Evaluating input: 2 of 100

 Retrying in 1 seconds

Evaluating input: 3 of 100

 Retrying in 1 seconds

Evaluating input: 4 of 100

 Retrying in 1 seconds

Evaluating input: 5 of 100

 Retrying in 1 seconds

Evaluating input: 6 of 100

 Retrying in 1 seconds

Evaluating input: 7 of 100

 Retrying in 1 seconds

Evaluating input: 8 of 100

 Retrying in 1 seconds

Evaluating input: 9 of 100

 Retrying in 1 seconds

Evaluating input: 10 of 100

 Retrying in 1 seconds

Evaluating input: 11 of 100

 Retrying in 1 seconds


error: unpack requires a buffer of 4 bytes

### Experimental Design - Model Variance

In [15]:
MV_Xs = []
MV_Ys = []
mses_MV = []
    
def user_function_model_variance(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function time loss called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, edgeLength, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.2
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * edgeLength / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            edgeLength    = edgeLength,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average co2 / average route duration
        CO2 = s['CO2']/s['num_emissions_samples']
        # average emissions / average route length
        result.append(CO2/s['routeLength'])
        MV_Xs.append([int(gridSize), edgeMaxSpeed, edgeLength, int(numLanes), accel])
        MV_Ys.append(CO2/s['routeLength'])

        i += 1
    
    # evaluate / validate model
    if len(MV_Xs) % 50 == 0:
        pred_Y, pred_Y_variance = emukit_model_mv.predict(np.array(test_X))
        rmse = np.sqrt(np.mean((pred_Y-test_Y)**2))
        mses_MV.append((len(MV_Xs), rmse))
        print('EVALUATED: ', len(MV_Xs), rmse)
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

#### Model / Emulator (GP)

Our surrogate model is our emulator. In this case, a gaussian process.

In [16]:
emulator_mv = GPy.models.GPRegression(init_X, init_Y)
emukit_model_mv = GPyModelWrapper(emulator_mv, n_restarts=5)
emukit_model_mv.optimize()
emulator_mv

Optimization restart 1/5, f = -67.57915497275103
Optimization restart 2/5, f = -38.643089255789256
Optimization restart 3/5, f = -38.64309508277225
Optimization restart 4/5, f = -63.23622460617891
Optimization restart 5/5, f = -38.64308921188966


#### Acquisition Function

In [17]:
model_variance = ModelVariance(model=emukit_model_mv)

#### Optimizer

In [18]:
optimizer = GradientAcquisitionOptimizer(parameter_space)


#### Experimental Design Loop

In [19]:
ed_loop_mv = ExperimentalDesignLoop(
    model = emukit_model_mv,
    space = parameter_space,
    acquisition = model_variance,
    acquisition_optimizer = optimizer,
    batch_size = 1
)

In [20]:
ed_loop_mv.run_loop(user_function_model_variance, 750)

Optimization restart 1/5, f = -67.57915497277844
Optimization restart 2/5, f = -38.643089211701636
Optimization restart 3/5, f = -38.64308925045841
Optimization restart 4/5, f = -67.5791549601593
Optimization restart 5/5, f = -38.643089211701685
[[20.         20.56323278 30.45933824  1.          4.87437208]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -71.25737182232857
Optimization restart 2/5, f = -40.15188532238996
Optimization restart 3/5, f = -40.151885322389646
Optimization restart 4/5, f = -40.15192109777739
Optimization restart 5/5, f = -40.15188532238964
[[ 3.         24.5081419  68.85494919  3.          3.53975891]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -74.69204245184355
Optimization restart 2/5, f = -74.69204245164534
Optimization restart 3/5, f = -74.69204241404252
Optimization rest

 Retrying in 1 seconds
Optimization restart 1/5, f = -137.4437354259297
Optimization restart 2/5, f = -137.44537098967174
Optimization restart 3/5, f = -137.445370989698
Optimization restart 4/5, f = -137.44537098755308
Optimization restart 5/5, f = -137.44537098873957
[[20.         22.61826022 30.62750479  2.          1.57330998]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -141.5702970744477
Optimization restart 2/5, f = -141.57032177416892
Optimization restart 3/5, f = -141.57032177352747
Optimization restart 4/5, f = -72.09702091066825
Optimization restart 5/5, f = -141.57032177412543
[[ 4.         24.67244448 69.38597536  1.          1.59530008]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -143.3070664802919
Optimization restart 2/5, f = -143.3070664764629
Optimization restart 3/5, f = -143.30706

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -207.26317895805624
Optimization restart 2/5, f = -103.10461474101852
Optimization restart 3/5, f = -207.2631789438312
Optimization restart 4/5, f = -207.26317895454957
Optimization restart 5/5, f = -207.2631789594652
[[ 3.          8.14156709 46.77647724  3.          1.51668114]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -210.87857017381904
Optimization restart 2/5, f = -210.87859499055833
Optimization restart 3/5, f = -210.87859498693533
Optimization restart 4/5, f = -210.87859499272585
Optimization restart 5/5, f = -105.07704152812059
[[ 3.         24.57393824 54.81421182  1.          4.85926593]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -214.76491056173657
Optimization restart 2/5, f = -214.7649105637943
Optimization restart 3/5, f = -214.7

 Retrying in 1 seconds
Optimization restart 1/5, f = -284.7326289635124
Optimization restart 2/5, f = -284.73262896351054
Optimization restart 3/5, f = -284.7326289635235
Optimization restart 4/5, f = -284.732628948966
Optimization restart 5/5, f = -284.73262896308927
[[14.         24.86756115 63.61651136  1.          4.84335402]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -289.2406488319132
Optimization restart 2/5, f = -289.2406488358574
Optimization restart 3/5, f = -289.24064882967286
Optimization restart 4/5, f = -289.2406488351182
Optimization restart 5/5, f = -289.2406488358509
[[ 9.         24.50792    30.3926305   3.          4.69822985]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -293.64395867562246
Optimization restart 2/5, f = -293.6439586755876
Optimization restart 3/5, f = -293.6439586

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -343.99337216327586
[[ 3.         22.26374937 30.8357136   1.          4.98536391]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -349.353300376658
Optimization restart 2/5, f = -349.3533003820229
Optimization restart 3/5, f = -349.3533003823644
Optimization restart 4/5, f = -349.35330036769903
Optimization restart 5/5, f = -349.3533003823731
[[10.         24.34664157 69.47132451  3.          1.81416937]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -353.80364551756026
Optimization restart 2/5, f = -353.803699513795
Optimization restart 3/5, f = -353.80369951742966
Optimization restart 4/5, f = -353.80369951538427
Optimization restart 5/5, f = -167.4196766903414
[[ 3.         24.27145955 63.02706922  3.          1.60500251]]

User function time loss called with 1 inputs to s

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -381.04607705128717
Optimization restart 2/5, f = -381.0461582884221


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -380.0870972548816
Optimization restart 4/5, f = -381.04615828844874
Optimization restart 5/5, f = -381.04615828578443
[[ 3.         15.87601785 69.70663936  1.          1.73798013]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -383.76287740308175
Optimization restart 2/5, f = -383.7628774035304
Optimization restart 3/5, f = -383.7628774035405
Optimization restart 4/5, f = -182.1777590397833
Optimization restart 5/5, f = -182.17775903925343
[[20.         19.37244804 41.31599777  3.          4.18766851]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -388.06982597238135
Optimization restart 2/5, f = -388.070121949871
Optimization restart 3/5, f = -388.07012195089334
Optimization restart 4/5, f = -388.07012195014994
Optimization restart 5/5, f = -388.0701219488026
[[ 3.        

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -188.1726631554048
Optimization restart 5/5, f = -401.45001931582954
[[20.          8.23574872 68.62385534  3.          4.1733496 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -405.9085966643738
Optimization restart 2/5, f = -405.9088993381397
Optimization restart 3/5, f = -405.9088993381626
Optimization restart 4/5, f = -405.9088991469015
Optimization restart 5/5, f = -190.19171039320656
[[ 8.          8.8298104  69.53624876  3.          1.5450493 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -410.40732259281816
Optimization restart 2/5, f = -410.4073257241435
Optimization restart 3/5, f = -410.4073257242769
Optimization restart 4/5, f = -410.4073257239329
Optimization restart 5/5, f = -410.4073257242636
[[ 3.         16.18765705 30.2051754   3.          4.7820767 ]]



 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -414.47575205489306
Optimization restart 2/5, f = -414.4757520554833
Optimization restart 3/5, f = -414.47575205582217
Optimization restart 4/5, f = -414.4757520539779
Optimization restart 5/5, f = -414.4757520556984
[[ 8.         24.94571463 30.18679263  1.          4.54585163]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -418.5877341501548
Optimization restart 2/5, f = -194.94633360917666
Optimization restart 3/5, f = -418.5877341533933
Optimization restart 4/5, f = -418.5877341576838
Optimization restart 5/5, f = -418.587734160193
[[19.         19.80288602 69.47883484  3.          1.71997401]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -423.0723287212357
Optimization restart 2/5, f = -196.7897020195817
Optimization restart 3/5, f = -423.07241816

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -440.69320309048567
Optimization restart 4/5, f = -447.5679775635116
Optimization restart 5/5, f = -447.5679775636566
[[19.         24.79405318 31.19707094  3.          4.70767819]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -451.8436480876257
Optimization restart 2/5, f = -451.84387738932264
Optimization restart 3/5, f = -451.843877388545
Optimization restart 4/5, f = -451.8438773298162
Optimization restart 5/5, f = -207.48523922166
[[20.         17.7279355  62.07650431  3.          4.91748905]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -456.2375567468419
Optimization restart 2/5, f = -456.2375567468748
Optimization restart 3/5, f = -209.48122314460957
Optimization restart 4/5, f = -456.23755674688334
Optimization restart 5/5, f = -456.2375567469209
[[20.         24.9

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = -482.7393348229479
Optimization restart 5/5, f = -482.7393345322381
[[ 3.          8.56622944 63.81881984  3.          4.72495704]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -487.2123806791835
Optimization restart 2/5, f = -221.68381116813333
Optimization restart 3/5, f = -487.21243243525754
Optimization restart 4/5, f = -487.2124324300147
Optimization restart 5/5, f = -487.2124324353768
[[19.          9.23541257 30.57243954  1.          4.99450838]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -491.4678377353684
Optimization restart 2/5, f = -491.46783773592574


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -487.5523598088192
Optimization restart 4/5, f = -491.46783767092086
Optimization restart 5/5, f = -491.4678377352153
[[20.         24.11249746 45.6691529   3.          4.75187648]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -495.8714714064679
Optimization restart 2/5, f = -495.87147141657147
Optimization restart 3/5, f = -495.8714714227829


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -483.67781064017595
Optimization restart 5/5, f = -495.8714714229525
[[17.          8.63240779 69.47591973  1.          1.98590396]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -500.46109877017284
Optimization restart 2/5, f = -227.5074122590582
Optimization restart 3/5, f = -500.4611193420983
Optimization restart 4/5, f = -500.4611193672529
Optimization restart 5/5, f = -227.50751690027562
[[20.         23.18097332 30.3851197   3.          1.62757016]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -505.0544943559976
Optimization restart 2/5, f = -228.55357513579514
Optimization restart 3/5, f = -228.55357516527715
Optimization restart 4/5, f = -505.0544944799991
Optimization restart 5/5, f = -505.0544944800137
[[ 3.         24.7771697  32.68152539  1.          4.8066294 ]]

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = -531.0770571658029
Optimization restart 3/5, f = -531.0770571653602
Optimization restart 4/5, f = -531.0770571656378
Optimization restart 5/5, f = -531.0770571658668
[[ 8.         24.94907542 37.29024708  3.          4.7885115 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -535.0252417091243
Optimization restart 2/5, f = -535.0252417116277
Optimization restart 3/5, f = -535.02523975315
Optimization restart 4/5, f = -535.0252416747857
Optimization restart 5/5, f = -535.025241711692
[[ 3.         24.27505035 30.18483541  1.          1.8854936 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -539.3881430685277
Optimization restart 2/5, f = -539.3881430683416
Optimization restart 3/5, f = -539.3881430682624
Optimization restart 4/5, f = -539.3881430685562
Optimization restart 5

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -578.3554309567979
Optimization restart 3/5, f = -581.5275265470157
Optimization restart 4/5, f = -581.5275263209965
Optimization restart 5/5, f = -581.5275264242756
[[20.         23.54462259 69.9806798   1.          3.97192564]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -586.1108809288783
Optimization restart 2/5, f = -586.110895375452
Optimization restart 3/5, f = -586.1108955679821
Optimization restart 4/5, f = -586.1108955671598
Optimization restart 5/5, f = -586.1108949920811
[[13.          9.94739    30.28349941  3.          1.72319949]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -588.2845030882982
Optimization restart 2/5, f = -588.2845030879164
Optimization restart 3/5, f = -588.2845030883118
Optimization restart 4/5, f = -588.2845030850674
Optimization restart

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -601.8754686528878
Optimization restart 4/5, f = -601.8754686638705
Optimization restart 5/5, f = -601.8754686376691
[[20.         23.74661827 31.06912254  1.          4.89732126]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -606.1576827738015
Optimization restart 2/5, f = -606.158015973056
Optimization restart 3/5, f = -606.158015966204
Optimization restart 4/5, f = -606.1580159732862
Optimization restart 5/5, f = -606.1580159733052
[[20.          8.47613944 39.22389684  3.          4.83048806]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -610.6236102003045
Optimization restart 2/5, f = -610.6236105979538
Optimization restart 3/5, f = -610.6236105978033
Optimization restart 4/5, f = -610.6236105977342
Optimization restart 5/5, f = -610.6236105955471
[[15.          8.4210

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -670.9761803288583
Optimization restart 4/5, f = -680.0976826299911
Optimization restart 5/5, f = -680.0976826275619
[[20.          8.56712881 66.87012455  1.          4.89089248]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -684.5131077488306
Optimization restart 2/5, f = -684.513500556227
Optimization restart 3/5, f = -300.9633570540824
Optimization restart 4/5, f = -684.5135005714206
Optimization restart 5/5, f = -684.5135005682403
[[ 3.         24.99638193 66.21127618  1.          4.92817085]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -689.1225466331557
Optimization restart 2/5, f = -689.122611890405
Optimization restart 3/5, f = -689.1226118943329


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = -689.1226118942383
Optimization restart 5/5, f = -689.1226117688678
[[14.          8.04119321 45.95714276  1.          4.79701891]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -691.0283583390027
Optimization restart 2/5, f = -691.028358334625
Optimization restart 3/5, f = -691.0283583391613
Optimization restart 4/5, f = -691.0283583385944
Optimization restart 5/5, f = -691.028358214006
[[20.          8.73534111 69.99338152  3.          4.08284779]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -695.6541763057821
Optimization restart 2/5, f = -695.6542631565956
Optimization restart 3/5, f = -695.6542631604758
Optimization restart 4/5, f = -695.6542631344225
Optimization restart 5/5, f = -695.6542631605334
[[ 3.         18.96558968 61.06004905  1.          1.51093442]]

User 

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = -731.9307741398278
Optimization restart 3/5, f = -731.9307741118752
Optimization restart 4/5, f = -731.9307741395745
Optimization restart 5/5, f = -731.9307741398917
[[20.         24.98176008 69.93203285  3.          3.73174282]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -736.3675502801785
Optimization restart 2/5, f = -736.3675502786334
Optimization restart 3/5, f = -736.3675502415351
Optimization restart 4/5, f = -584.3482144242971
Optimization restart 5/5, f = -736.3675502695808
[[ 3.          9.62353274 69.77082932  3.          4.97245497]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -740.9125038540385
Optimization restart 2/5, f = -740.9125950103886
Optimization restart 3/5, f = -740.912590427123
Optimization restart 4/5, f = -740.9125949028706
Optimization restart

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -742.981232845688
Optimization restart 4/5, f = -743.5138241828356
Optimization restart 5/5, f = -743.5138241828872
[[ 6.          8.20758213 30.14731829  1.          4.67440389]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -746.5631516770251
Optimization restart 2/5, f = -746.563324042786
Optimization restart 3/5, f = -746.5633240438865
Optimization restart 4/5, f = -746.5633240419435
Optimization restart 5/5, f = -746.5633240445491
[[ 3.         24.86631265 48.61129623  3.          1.60682985]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -751.0504953626329
Optimization restart 2/5, f = -751.0506286592687
Optimization restart 3/5, f = -751.0506286589135
Optimization restart 4/5, f = -751.0506286593774
Optimization restart 5/5, f = -751.050628659335
[[ 3.         16.86635

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -761.3882455317453
Optimization restart 5/5, f = -763.8843295971093
[[20.          8.52725494 37.29608243  3.          1.50719563]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -766.3227839548123
Optimization restart 2/5, f = -766.3236110580118
Optimization restart 3/5, f = -766.3236110574298
Optimization restart 4/5, f = -766.3236110579526
Optimization restart 5/5, f = -766.3236110564872
[[ 3.          8.04211428 69.94271603  2.          1.82465442]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -770.8061919897114
Optimization restart 2/5, f = -770.8064119056778
Optimization restart 3/5, f = -770.806411905107
Optimization restart 4/5, f = -770.8064119081367
Optimization restart 5/5, f = -770.8064117854965
[[13.         24.92480318 46.85676239  1.          4.94137656]]

User

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -804.2312724731524
Optimization restart 3/5, f = -813.5949559181381
Optimization restart 4/5, f = -813.5949559139784
Optimization restart 5/5, f = -813.5949559175775
[[ 9.          8.22060711 31.91038392  3.          1.50435612]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -817.6757000504151
Optimization restart 2/5, f = -817.6757000381941
Optimization restart 3/5, f = -817.6757000526662


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -812.5336894197693
Optimization restart 5/5, f = -805.480762662847
[[12.          8.00794894 54.27978222  1.          1.88112082]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -822.3050728576767
Optimization restart 2/5, f = -822.3050782919454
Optimization restart 3/5, f = -822.3050783434901
Optimization restart 4/5, f = -822.3050783431315
Optimization restart 5/5, f = -822.3050783195246
[[13.         20.01384543 49.56316838  3.          4.99176485]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -826.8004110755614
Optimization restart 2/5, f = -826.8004110325212
Optimization restart 3/5, f = -826.8004111301435
Optimization restart 4/5, f = -826.8004111770308
Optimization restart 5/5, f = -826.8004111783977
[[ 4.          8.12623525 38.83849874  1.          4.99494022]]

User

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -827.4060366492572
Optimization restart 4/5, f = -359.74349880643194
Optimization restart 5/5, f = -827.406036651512
[[13.         24.9725943  48.13939925  3.          1.64499639]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -832.0254132075827
Optimization restart 2/5, f = -832.0254132474637
Optimization restart 3/5, f = -832.0254132491679
Optimization restart 4/5, f = -832.0254132486198
Optimization restart 5/5, f = -832.0254132489574
[[20.         13.62592227 41.50993629  3.          1.71220545]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -836.2850673450115
Optimization restart 2/5, f = -836.2850672800186
Optimization restart 3/5, f = -836.2850667920002
Optimization restart 4/5, f = -836.2850673725663
Optimization restart 5/5, f = -836.2850673693202
[[ 5.          8.24

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -847.3119190754501
[[ 3.         13.60488787 51.74174162  1.          1.6097218 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -867.0644916101653
Optimization restart 2/5, f = -867.0644990996025
Optimization restart 3/5, f = -867.0644990964438
Optimization restart 4/5, f = -867.0644991004751
Optimization restart 5/5, f = -867.0644991015548
[[ 3.         24.84476862 30.52996963  1.          4.98482144]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -871.0902358463222
Optimization restart 2/5, f = -871.0906973691043


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -871.0906973690743
Optimization restart 4/5, f = -871.090694009892
Optimization restart 5/5, f = -871.0906970662787
[[14.         16.32256076 30.07790214  1.          4.8926635 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -875.7672014208985
Optimization restart 2/5, f = -875.7677344320742
Optimization restart 3/5, f = -875.7677344404898
Optimization restart 4/5, f = -875.7677344383688
Optimization restart 5/5, f = -875.7677344408027
[[20.         24.80200579 53.34462521  3.          4.93705547]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -880.4263217160889
Optimization restart 2/5, f = -880.4263252691545
Optimization restart 3/5, f = -880.4263252691665
Optimization restart 4/5, f = -880.4263251979921
Optimization restart 5/5, f = -880.4263250907367
[[11.          8.209

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -891.5140838870437
Optimization restart 4/5, f = -915.5836262413204
Optimization restart 5/5, f = -915.5836262454563
[[ 7.         20.31191765 52.57920034  1.          4.8140247 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -920.3090346693346
Optimization restart 2/5, f = -920.3090577579534
Optimization restart 3/5, f = -920.309057763382
Optimization restart 4/5, f = -920.3090576785116
Optimization restart 5/5, f = -920.3090577416875
[[ 4.         24.9077667  69.68554364  3.          4.99798418]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -924.5353681255407
Optimization restart 2/5, f = -924.5353681270503
Optimization restart 3/5, f = -924.535368128112
Optimization restart 4/5, f = -924.5353681277207
Optimization restart 5/5, f = -924.5353681269557
[[20.          8.2145

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -929.104606113923
Optimization restart 4/5, f = -929.1046061138351
Optimization restart 5/5, f = -929.1046061138669
[[20.         20.83955878 37.90302182  1.          1.77518481]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -932.819424175131
Optimization restart 2/5, f = -932.819424160515
Optimization restart 3/5, f = -932.819424173664
Optimization restart 4/5, f = -932.8194241750027
Optimization restart 5/5, f = -932.81942417295
[[20.         16.65422382 30.89013937  3.          1.55696981]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -913.5900175077649
Optimization restart 2/5, f = -913.590017508789
Optimization restart 3/5, f = -913.5900175087816
Optimization restart 4/5, f = -913.5900175067748
Optimization restart 5/5, f = -913.5900175077027
[[20.          9.15541622 

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -929.9180454459931
Optimization restart 4/5, f = -939.79785953241
Optimization restart 5/5, f = -939.7978595316026
[[16.          8.06106477 30.39673716  1.          1.66291747]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -943.5529384402473
Optimization restart 2/5, f = -943.5529384362316
Optimization restart 3/5, f = -943.552938439913
Optimization restart 4/5, f = -943.552938386478
Optimization restart 5/5, f = -943.5529384423148
[[ 3.          8.13033092 68.80227432  1.          1.74341392]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -948.1869132583475
Optimization restart 2/5, f = -414.64093320379754
Optimization restart 3/5, f = -948.1869208418667
Optimization restart 4/5, f = -948.1869208474973
Optimization restart 5/5, f = -948.1869208475065
[[20.          8.08947

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -994.3098298436573
Optimization restart 4/5, f = -994.3098298368651
Optimization restart 5/5, f = -994.3098297484036
[[20.          8.16018941 30.51323642  1.          3.652213  ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -998.9685799270507
Optimization restart 2/5, f = -998.9686804614423
Optimization restart 3/5, f = -998.9686804616953
Optimization restart 4/5, f = -998.9686804617776
Optimization restart 5/5, f = -998.9686804556986
[[ 8.          8.08707576 40.03130183  1.          1.62735431]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -1003.6342052755521
Optimization restart 2/5, f = -1003.6343460152239
Optimization restart 3/5, f = -1003.634346025907
Optimization restart 4/5, f = -1003.6343460336302
Optimization restart 5/5, f = -1003.634346032447
[[ 3.          8

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = -1039.3248234160324
Optimization restart 5/5, f = -451.9204636559184
[[ 9.         24.74993638 62.13966342  1.          1.64482369]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -1043.6391200493767
Optimization restart 2/5, f = -1043.6391199749964
Optimization restart 3/5, f = -1043.6391200517664
Optimization restart 4/5, f = -1043.6391200580338
Optimization restart 5/5, f = -1043.639120058938
[[20.         24.86525108 47.25166861  3.          1.69790891]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -1048.320663349135
Optimization restart 2/5, f = -1048.3207036147796
Optimization restart 3/5, f = -1048.3207036416852
Optimization restart 4/5, f = -1048.320703646456
Optimization restart 5/5, f = -1048.3207036427068
[[12.         16.87708882 30.13220855  3.          1.6324331

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = -1063.104877055353
Optimization restart 3/5, f = -1063.1048770551083
Optimization restart 4/5, f = -1063.1048770609432
Optimization restart 5/5, f = -1063.1048770586633
[[20.          8.56377208 65.49573982  3.          1.73858759]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -1067.7934731658538
Optimization restart 2/5, f = -1067.7935218881116
Optimization restart 3/5, f = -1067.793521950979
Optimization restart 4/5, f = -1067.7935219479073
Optimization restart 5/5, f = -1067.7935219299986
[[ 3.          8.65813472 30.39135671  3.          1.54158478]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -1072.0048013523399
Optimization restart 2/5, f = -1072.0048013646294
Optimization restart 3/5, f = -1072.0048013668747
Optimization restart 4/5, f = -1072.0048013653932
Optimiza

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -1116.6369500802298
Optimization restart 3/5, f = -1121.2376424836086
Optimization restart 4/5, f = -1121.2376424718284
Optimization restart 5/5, f = -1121.2376423453982
[[10.         24.90472621 69.86110132  3.          4.34367545]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -1125.9437790476866
Optimization restart 2/5, f = -1125.943919880615
Optimization restart 3/5, f = -1125.9439198761117
Optimization restart 4/5, f = -1125.9439198817008
Optimization restart 5/5, f = -1125.9439198802093
[[20.          8.07545063 37.44171321  1.          4.42335929]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -1129.3588246140398
Optimization restart 2/5, f = -1129.3588246332981
Optimization restart 3/5, f = -1129.3588244035068
Optimization restart 4/5, f = -1129.3588246270217
Optimiz

KeyboardInterrupt: 

### Experimental Design - Integrated Variance Reduction

In [ ]:
IVR_Xs = []
IVR_Ys = []
mses_IVR = []
    
def user_function_integrated_variance_reduction(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function time loss called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, edgeLength, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.2
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * edgeLength / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            edgeLength    = edgeLength,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average co2 / average route duration
        CO2 = s['CO2']/s['num_emissions_samples']
        # average emissions / average route length
        result.append(CO2/s['routeLength'])
        IVR_Xs.append([int(gridSize), edgeMaxSpeed, edgeLength, int(numLanes), accel])
        IVR_Ys.append(CO2/s['routeLength'])

        i += 1
    
    # evaluate / validate model
    if len(IVR_Xs) % 50 == 0:
        pred_Y, pred_Y_variance = emukit_model_ivr.predict(np.array(test_X))
        rmse = np.sqrt(np.mean((pred_Y-test_Y)**2))
        mses_IVR.append((len(IVR_Xs), rmse))
        print('EVALUATED: ', len(IVR_Xs), rmse)
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

#### Model / Emulator (GP)

In [ ]:
emulator_ivr = GPy.models.GPRegression(init_X, init_Y)
emukit_model_ivr = GPyModelWrapper(emulator_ivr, n_restarts=5)
emukit_model_ivr.optimize()

#### Acquisition Function

In [ ]:
integrated_variance_reduction = IntegratedVarianceReduction(
    model=emukit_model_ivr, 
    space=parameter_space, 
    num_monte_carlo_points=100
)

#### Optimizer

In [ ]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [ ]:
ed_loop_ivr = ExperimentalDesignLoop(
    model = emukit_model_ivr,
    space = parameter_space,
    acquisition = integrated_variance_reduction,
    acquisition_optimizer = optimizer,
    batch_size = 1
)

In [ ]:
ed_loop_ivr.run_loop(user_function_integrated_variance_reduction, 750)

### Random GP

Supervised learning

In [ ]:
# Train points are used to optimize a GP without experimental design - to verify experimental design works.

design = RandomDesign(parameter_space)
train_X = design.get_samples(770)
train_Y = user_function_time_loss(train_X)

In [ ]:
emulator_rnd = GPy.models.GPRegression(train_X, train_Y)
emukit_model_rnd = GPyModelWrapper(emulator_rnd, n_restarts=5)
emukit_model_rnd.optimize()
emulator_rnd

In [ ]:
mses_RND = []
for j in range(50,1000,50):
    xx = train_X[:j]
    yy = train_Y[:j]
    emulator_x = GPy.models.GPRegression(xx, yy)
    emukit_x = GPyModelWrapper(emulator_x, n_restarts=1)
    emukit_x.optimize()
    
    pred_Y, pred_Y_variance = emukit_x.predict(np.array(test_X))
    rmse = np.sqrt(np.mean((pred_Y-test_Y)**2))
    mses_RND.append((j, rmse))
    print('EVALUATED: ', j, rmse)

### Evaluate

Evaluate RMSE of each model on our test set of 50 randomly selected points.

In [ ]:
pred_Y, pred_Y_variance = emukit_model_ed.predict(test_X)
mse_ed = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Model Variance RMSE: ', mse_ed)

In [ ]:
pred_Y, pred_Y_variance = emukit_model_ird.predict(test_X)
mse_ird = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Integrated Variance Reduction RMSE: ', mse_ird)

In [ ]:
pred_Y, pred_Y_variance = emukit_model_rnd.predict(test_X)
mse_rnd = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Random GP RMSE: ', mse_rnd)

In [ ]:
p = 1 - (mse_ed/mse_rnd)
f'Experimental Design w/ Model Variance is {p*100:.3f}% better than training on random points.'

In [ ]:
p = 1 - (mse_ird/mse_rnd)
f'Experimental Design w/ Integrated Variance Reduction is {p*100:.3f}% better than training on random points.'

#### Plot MSE Graphs

In [ ]:
fig, ax = plt.subplots(figsize=(10,8))
X_mv, Y_mv = zip(*mses_MV)
X_ivr, Y_ivr = zip(*mses_IVR)
X_rnd, Y_rnd = zip(*mses_RND)
ax.plot(X_mv, Y_mv)
ax.plot(X_ivr, Y_ivr)
ax.plot(X_rnd, Y_rnd)

### Save Models

In [ ]:
with open(f'experimental_design/models/model_variance_20_init_points_750_loops_co2_per_distance.pkl', "wb") as f:
     pickle.dump(emukit_model_mv, f)

with open(f'experimental_design/models/integrated_variance_reduction_20_init_points_750_loops_co2_per_distance.pkl', "wb") as f:
     pickle.dump(emukit_model_ivr, f)
        
with open(f'experimental_design/models/770_random_points_supervised_GP_co2_per_distance.pkl', "wb") as f:
     pickle.dump(emukit_model_rnd, f)

### Dump whole session

In [ ]:
import dill                            
dill.dump_session('5_params_co2_per_distance_session.pkl')