In [1]:
%cd ../

/Users/Matteo/PycharmProjects/TrafficEmu


In [2]:
# If you get a SciPy error when installing Emukit, build it from source:

# git clone https://github.com/amzn/Emukit.git
# cd Emukit
# pip install -r requirements/requirements.txt
# python setup.py develop

In [3]:
import numpy as np
import pickle
import emukit as ek
import GPy

from emukit.model_wrappers import GPyModelWrapper
from emukit.experimental_design.experimental_design_loop import ExperimentalDesignLoop
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.core.initial_designs import RandomDesign, latin_design
from emukit.experimental_design.acquisitions import ModelVariance, IntegratedVarianceReduction
from emukit.core.loop import UserFunctionWrapper
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.bayesian_optimization.loops import BayesianOptimizationLoop
from emukit.core.optimization import GradientAcquisitionOptimizer

from sumo_grid_simulation.grid_simulation import Simulator
import experimental_design.config as config

warning in stationary: failed to import cython module: falling back to numpy
warning in coregionalize: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy


### Pseudocode

Fitting a gaussian process to a simulator using Emukit takes the following form (taken from L48 lectures):

```
initialize GP with some randomly chosen points
while stopping condition is not met:
    compute candidate point(s) using GP and acquisition funciton (model_variance) -> new point
    evaluate this new point with our simulator/user function -> observation
    update model with new observation -> new GP
```

### Simulator

In [4]:
simulator = Simulator(end_time=300)

### User Function
 
This is the function we want to understand. Namedly, how are CO2 emissions and timeLoss (the time lost due to driving below the ideal speed) affected by the following parameters: 

```
gridSize: the size of the grid network where the simulation is carried out
edgeMaxSpeed: legal speed limit in m/s - this can be exceeded (11.11 == 40km/h)
maxSpeed: the absolute maximum velocity of any vehicle in m/s (55.55 == 200 km/h)
edgeLength: length of the roads between intersections in meters
numLanes: number of lanes per road
accel: The acceleration ability of vehicles in m/s^2.
```

*A complete list of parmeters analysed is discussed in our report.*

In [5]:
def user_function_time_loss(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function time loss called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, maxSpeed, edgeLength, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.005
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * edgeLength / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            maxSpeed      = maxSpeed,
            edgeLength    = edgeLength,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average time loss / average route duration
        result.append(s['timeLoss']/(s['duration'] * s['speed']))
        print(f'\nOutput {result[-1]}\n')
        i += 1
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

### Model Inputs / parameter space

In [6]:
parameter_space = config.get_parameter_space()

### Get init, test, and train points

Train points are used to optimize a GP without experimental design - to verify experimental design works.

In [7]:
design = RandomDesign(parameter_space)
init_X = design.get_samples(20)
init_Y = user_function_time_loss(init_X)

design = RandomDesign(parameter_space)
test_X = design.get_samples(50)
test_Y = user_function_time_loss(test_X)

design = RandomDesign(parameter_space)
train_X = design.get_samples(270)
train_Y = user_function_time_loss(train_X)

[[17.         16.54672711 26.65024964 49.39868362  1.          2.04534632]
 [14.          8.10154659 20.31951646 43.07129858  3.          3.12082837]
 [11.         19.81438307  9.45902677 45.34608534  2.          1.548178  ]
 [10.         12.30842156 25.85690788 63.67883874  1.          1.69950228]
 [ 7.         17.48670123 15.93596633 38.73726654  3.          3.19783345]
 [19.         24.58968644 26.95614182 32.35683821  2.          2.50847927]
 [16.         19.10368982 21.58606951 52.46944389  1.          2.23003101]
 [14.         16.24791738 11.04390841 45.72242476  3.          2.93171126]
 [ 8.         21.12240215 24.90754974 64.13936886  1.          4.02442867]
 [ 7.         24.2507225  12.74328701 53.75709243  3.          4.879222  ]
 [ 9.         19.60221509 16.81528477 65.03782558  2.          3.92135173]
 [ 8.         13.96060615  6.98971681 61.53613441  1.          4.27260238]
 [ 7.         18.69104509 25.30115725 68.38728907  1.          3.5784463 ]
 [15.          8.73304137


Evaluating input: 36 of 50

 Retrying in 1 seconds

Evaluating input: 37 of 50

 Retrying in 1 seconds

Evaluating input: 38 of 50

 Retrying in 1 seconds

Evaluating input: 39 of 50

 Retrying in 1 seconds

Evaluating input: 40 of 50

 Retrying in 1 seconds

Evaluating input: 41 of 50

 Retrying in 1 seconds

Evaluating input: 42 of 50

 Retrying in 1 seconds

Evaluating input: 43 of 50

 Retrying in 1 seconds

Evaluating input: 44 of 50

 Retrying in 1 seconds

Evaluating input: 45 of 50

 Retrying in 1 seconds

Evaluating input: 46 of 50

 Retrying in 1 seconds

Evaluating input: 47 of 50

 Retrying in 1 seconds

Evaluating input: 48 of 50

 Retrying in 1 seconds

Evaluating input: 49 of 50

 Retrying in 1 seconds

Evaluating input: 50 of 50

 Retrying in 1 seconds
[[12.         19.03810381 21.70634426 33.17166425  3.          2.07380182]
 [18.         18.306412   15.8701729  61.6371389   2.          3.61948402]
 [ 9.         10.80773887 18.16207099 53.45559076  3.          3.07138


Evaluating input: 131 of 270

 Retrying in 1 seconds

Evaluating input: 132 of 270

 Retrying in 1 seconds

Evaluating input: 133 of 270

 Retrying in 1 seconds

Evaluating input: 134 of 270

 Retrying in 1 seconds

Evaluating input: 135 of 270

 Retrying in 1 seconds

Evaluating input: 136 of 270

 Retrying in 1 seconds

Evaluating input: 137 of 270

 Retrying in 1 seconds

Evaluating input: 138 of 270

 Retrying in 1 seconds

Evaluating input: 139 of 270

 Retrying in 1 seconds

Evaluating input: 140 of 270

 Retrying in 1 seconds

Evaluating input: 141 of 270

 Retrying in 1 seconds

Evaluating input: 142 of 270

 Retrying in 1 seconds

Evaluating input: 143 of 270

 Retrying in 1 seconds

Evaluating input: 144 of 270

 Retrying in 1 seconds

Evaluating input: 145 of 270

 Retrying in 1 seconds

Evaluating input: 146 of 270

 Retrying in 1 seconds

Evaluating input: 147 of 270

 Retrying in 1 seconds

Evaluating input: 148 of 270

 Retrying in 1 seconds

Evaluating input: 149 of 27

### Experimental Design - Model Variance

#### Model / Emulator (GP)

Our surrogate model is our emulator. In this case, a gaussian process.

In [8]:
emulator_ed = GPy.models.GPRegression(init_X, init_Y)
emukit_model_ed = GPyModelWrapper(emulator_ed, n_restarts=5)
emukit_model_ed.optimize()
emulator_ed

Optimization restart 1/5, f = -67.43039929354521
Optimization restart 2/5, f = -67.43039929552418
Optimization restart 3/5, f = -38.54329430666736
Optimization restart 4/5, f = -38.54329430667104
Optimization restart 5/5, f = -67.43039929583743


#### Acquisition Function

In [9]:
model_variance = ModelVariance(model=emukit_model_ed)

#### Optimizer

In [10]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [11]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ed,
    space = parameter_space,
    acquisition = model_variance,
    acquisition_optimizer = optimizer,
    batch_size = 1
)

In [12]:
ed_loop.run_loop(user_function_time_loss, 250)

Optimization restart 1/5, f = -67.43039929588755
Optimization restart 2/5, f = -38.54329430667199
Optimization restart 3/5, f = -38.54329430670175
Optimization restart 4/5, f = -67.43039929589975
Optimization restart 5/5, f = -67.43039929590742
[[ 3.         12.82763838  6.11290235 30.97717003  3.          3.80292813]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -71.22121042811158
Optimization restart 2/5, f = -40.58170147119566
Optimization restart 3/5, f = -40.581701467256885
Optimization restart 4/5, f = -40.58170146725469
Optimization restart 5/5, f = -40.581728760892595
[[20.         24.26626349  6.27598189 67.36861932  2.          2.26794857]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -75.1673871205529
Optimization restart 2/5, f = -75.16738712057006
Optimization restart 3/5, f = -42.876616513

Optimization restart 5/5, f = -74.3871603368514
[[ 4.          9.2361118   5.50674863 65.15163655  1.          4.22739248]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -128.71020863999274
Optimization restart 2/5, f = -75.99214990935306
Optimization restart 3/5, f = -75.99214863780715
Optimization restart 4/5, f = -128.71020864071647
Optimization restart 5/5, f = -128.71020862657167
[[ 5.          8.52946041  6.47746218 69.54051412  3.          1.73236055]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -132.47345689537153
Optimization restart 2/5, f = -112.68798021651392
Optimization restart 3/5, f = -78.27382913648472
Optimization restart 4/5, f = -132.4738164285173
Optimization restart 5/5, f = -132.47381643959426
[[ 3.          8.23929817 25.91542834 32.88519784  2.          2.26095521]]

User functi

 Retrying in 1 seconds
Optimization restart 1/5, f = -177.69871158104988
Optimization restart 2/5, f = -177.69871158102154
Optimization restart 3/5, f = -103.49806598264487
Optimization restart 4/5, f = -103.49805105134526
Optimization restart 5/5, f = -177.69871158105025
[[20.         24.83246216 11.7025949  37.98500272  1.          2.2105675 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -180.21696337239516
Optimization restart 2/5, f = -180.21696337262634
Optimization restart 3/5, f = -105.49803700963348
Optimization restart 4/5, f = -180.21696337263046
Optimization restart 5/5, f = -105.49804040549499
[[ 4.         24.64810243 25.24780244 62.02718173  3.          1.75798666]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -177.64036174730273
Optimization restart 2/5, f = -105.99204893947238
Optimizat

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -177.64036174711697
[[19.          8.4877469  26.55726955 40.38610888  3.          3.81991154]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -181.44885801567267
Optimization restart 2/5, f = -181.44885801547275
Optimization restart 3/5, f = -108.04809812797937
Optimization restart 4/5, f = -181.44885801567867
Optimization restart 5/5, f = -181.4488580156791
[[17.         12.27758528 14.70953553 69.90496422  3.          4.59756338]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -184.50228852802528
Optimization restart 2/5, f = -110.17968784972928
Optimization restart 3/5, f = -184.5022885300943
Optimization restart 4/5, f = -184.50228852865058
Optimization restart 5/5, f = -184.5022885285112
[[ 4.          8.338702   13.95734041 33.11187782  1.          1.63185738]]

User fun

Optimization restart 5/5, f = -230.85722067525953
[[20.         23.48393987  9.52170286 69.80073332  1.          4.90938687]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -234.66661846809143
Optimization restart 2/5, f = -234.66663915211078
Optimization restart 3/5, f = -142.13138059322125
Optimization restart 4/5, f = -234.6666391521308
Optimization restart 5/5, f = -142.1313578669014
[[ 3.         23.29865448  5.50596464 46.2962615   1.          4.68425604]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -237.11883487084276
Optimization restart 2/5, f = -143.64933341578597
Optimization restart 3/5, f = -237.11883487346657
Optimization restart 4/5, f = -143.64933341578603
Optimization restart 5/5, f = -237.1188348736234
[[ 8.          8.34188894 18.95447003 31.21939962  3.          4.72844178]]

User fun

Optimization restart 5/5, f = -286.96585322259784
[[19.         23.74241428  5.51249882 30.23808165  3.          3.44748604]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -288.45760406940775
Optimization restart 2/5, f = -288.4576040653773
Optimization restart 3/5, f = -173.80720769420378
Optimization restart 4/5, f = -173.80720769420444
Optimization restart 5/5, f = -288.45760407020293
[[19.         11.68567188  5.8646043  69.95594439  3.          2.82060008]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -292.1964238843683
Optimization restart 2/5, f = -175.86212943559258
Optimization restart 3/5, f = -292.196495198873
Optimization restart 4/5, f = -175.8621570108417
Optimization restart 5/5, f = -292.196495198405
[[15.          8.69005571 26.30465095 68.18589485  3.          3.56585335]]

User functio

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -288.55136623844345
[[20.         24.33450291 16.37270698 55.47833547  3.          4.66751435]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -299.5614893668388
Optimization restart 2/5, f = -180.03035093732984
Optimization restart 3/5, f = -299.5614893673344
Optimization restart 4/5, f = -299.56148936731466
Optimization restart 5/5, f = -180.03033549458488
[[20.         10.17928307  5.35205798 39.71357785  3.          1.71087902]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -303.1784107860793
Optimization restart 2/5, f = -182.14909560623659
Optimization restart 3/5, f = -303.1784107850442
Optimization restart 4/5, f = -182.14905099681033
Optimization restart 5/5, f = -182.14905099681022
[[ 6.          8.29581012  5.51035577 69.73342494  1.          4.73868362]]

User func

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -322.68247383682973
Optimization restart 4/5, f = -196.4302549989024
Optimization restart 5/5, f = -196.43033898355273
[[11.         13.63365704 25.43939487 30.33234085  3.          1.61036319]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -336.49738167415643
Optimization restart 2/5, f = -197.75049543210034
Optimization restart 3/5, f = -336.49738575137076
Optimization restart 4/5, f = -336.4973857512483
Optimization restart 5/5, f = -336.4973857513909
[[17.         23.41604709  5.13225105 30.21270083  3.          1.53508564]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -339.3165885887311
Optimization restart 2/5, f = -339.3165885882236
Optimization restart 3/5, f = -339.3165885884239
Optimization restart 4/5, f = -339.31658858865393
Optimization restart 5/5, f = -199.193

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -353.80423609434825
Optimization restart 4/5, f = -207.5477921838106
Optimization restart 5/5, f = -207.54779218386008
[[20.          8.11914992  5.79062821 57.18597571  3.          1.82164916]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -357.51404256432454
Optimization restart 2/5, f = -357.5140751014036
Optimization restart 3/5, f = -209.66097575255642
Optimization restart 4/5, f = -357.5140750781736
Optimization restart 5/5, f = -357.51407509334547
[[16.         24.67585122 26.64582332 68.53709196  1.          1.60866899]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -361.1416734670316
Optimization restart 2/5, f = -361.1416732972432
Optimization restart 3/5, f = -361.14167346264617
Optimization restart 4/5, f = -211.3838733142094
Optimization restart 5/5, f = -361.141

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = -372.6157162348212
Optimization restart 3/5, f = -372.615716234086
Optimization restart 4/5, f = -218.43338201182314
Optimization restart 5/5, f = -218.43337638157215
[[ 5.         23.90106177 26.19015031 69.91570007  3.          1.54488298]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -375.578489166749
Optimization restart 2/5, f = -375.5786130721749
Optimization restart 3/5, f = -375.5786130722662
Optimization restart 4/5, f = -220.05658213524336
Optimization restart 5/5, f = -375.578613072276
[[ 4.          9.25967814  5.45019375 30.20335256  1.          1.82119159]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -379.0875546936682
Optimization restart 2/5, f = -222.0264589211288
Optimization restart 3/5, f = -379.0875699348418
Optimization restart 4/5, f = -222.026458895

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -409.8838418980631
Optimization restart 4/5, f = -413.20483195217884
Optimization restart 5/5, f = -413.2048319506197
[[ 3.         24.92326281  5.97563502 45.96590897  3.          1.55513024]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -416.6367524869204
Optimization restart 2/5, f = -416.63675248943315
Optimization restart 3/5, f = -416.6367524894078
Optimization restart 4/5, f = -381.86446293591655
Optimization restart 5/5, f = -416.63675248007496
[[ 4.          8.65667785 25.97067212 51.4278548   1.          1.53591035]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -420.4613888595079
Optimization restart 2/5, f = -244.83026612616308
Optimization restart 3/5, f = -420.4614108631125
Optimization restart 4/5, f = -420.4614108631217
Optimization restart 5/5, f = -420.4614

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -441.64518115979666
Optimization restart 2/5, f = -258.07926204139574
Optimization restart 3/5, f = -258.07931146321056
Optimization restart 4/5, f = -441.6451811574931
Optimization restart 5/5, f = -258.07926085099643
[[ 3.          8.05875986 17.62315414 65.44690825  1.          4.85022788]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -445.4526954011624
Optimization restart 2/5, f = -445.4526995711984
Optimization restart 3/5, f = -445.4526995696827
Optimization restart 4/5, f = -445.45269955046996
Optimization restart 5/5, f = -260.11983353776463
[[17.         24.69097875 18.16909399 69.96941571  3.          1.6041796 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -449.1980479130839
Optimization restart 2/5, f = -262.08544408474995
Optimization r

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -441.9596938147185
Optimization restart 5/5, f = -452.9986714469053
[[10.          9.72882684  5.36497301 42.67459549  1.          4.97919558]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -456.14013897916504
Optimization restart 2/5, f = -456.1401389746911
Optimization restart 3/5, f = -456.1401389793107
Optimization restart 4/5, f = -456.1401389785899
Optimization restart 5/5, f = -456.14013897932347
[[ 3.          8.04133677  6.38991958 31.83593332  1.          4.9941462 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -459.74065083547157
Optimization restart 2/5, f = -266.3609423323055
Optimization restart 3/5, f = -459.7406506967077
Optimization restart 4/5, f = -459.74065083380884
Optimization restart 5/5, f = -459.74065081951403
[[18.          8.21000349 18.02826625 6

Optimization restart 5/5, f = -514.3771380182905
[[20.         24.41697123  7.94270446 69.22276987  1.          4.93322576]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -518.1292762712951
Optimization restart 2/5, f = -518.1292762838697


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -494.04251638830874
Optimization restart 4/5, f = -299.89505831267945
Optimization restart 5/5, f = -518.1292762483604
[[15.          8.43953936 26.95895855 45.34518138  3.          4.95981924]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -521.0875082209936
Optimization restart 2/5, f = -521.0875082220846
Optimization restart 3/5, f = -301.88274702076865
Optimization restart 4/5, f = -521.0875082224317
Optimization restart 5/5, f = -521.0875082223276
[[20.         24.95156575  5.81069136 60.26405418  1.          2.16854384]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -524.9416365882175
Optimization restart 2/5, f = -304.0144097197528
Optimization restart 3/5, f = -524.9416482950329
Optimization restart 4/5, f = -524.9416482982085
Optimization restart 5/5, f = -304.014409

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -519.5204974661934
Optimization restart 4/5, f = -534.7197658383672
Optimization restart 5/5, f = -309.78165024421395
[[ 3.         19.18632692 15.81093583 30.16883352  1.          2.22661646]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -538.1817031100221
Optimization restart 2/5, f = -310.453421756676
Optimization restart 3/5, f = -538.1817030701554
Optimization restart 4/5, f = -310.45342320850915
Optimization restart 5/5, f = -538.1817031144773
[[20.          8.6386828  12.7567158  43.79131153  1.          4.67378225]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -542.0130423200217
Optimization restart 2/5, f = -312.48083736575967
Optimization restart 3/5, f = -312.48120288489724
Optimization restart 4/5, f = -542.0130423289502
Optimization restart 5/5, f = -542.013042

Optimization restart 4/5, f = -600.2897916588098
Optimization restart 5/5, f = -600.2897916588486
[[17.         24.90490382  5.27125788 30.08464359  1.          4.35649995]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -604.1386684182226
Optimization restart 2/5, f = -604.1387449094038
Optimization restart 3/5, f = -344.0748875906437
Optimization restart 4/5, f = -604.1387449091293
Optimization restart 5/5, f = -604.1387449099523
[[ 3.         10.72766377 26.82066737 50.61076409  1.          4.48074969]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -607.4332169633428
Optimization restart 2/5, f = -607.4332208911177
Optimization restart 3/5, f = -607.4332208907488
Optimization restart 4/5, f = -346.1648862345699
Optimization restart 5/5, f = -607.4332208902923
[[20.         16.46132091 26.95417052 32.725

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = -630.0478234386553
Optimization restart 3/5, f = -357.44433558684796
Optimization restart 4/5, f = -630.047823437342
Optimization restart 5/5, f = -630.04782343865
[[ 3.          8.03272212 15.05438373 42.54506914  1.          4.73853055]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -633.7531041889553
Optimization restart 2/5, f = -633.7531037672911
Optimization restart 3/5, f = -359.44346754865137
Optimization restart 4/5, f = -633.7531041367859
Optimization restart 5/5, f = -359.443526030697
[[20.         24.72845621 26.56669847 57.55507943  1.          1.83922053]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -637.5933119830895
Optimization restart 2/5, f = -637.5933509540384


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -625.8926707681254
Optimization restart 4/5, f = -637.5933509556066
Optimization restart 5/5, f = -637.5933509546637
[[ 3.         15.37284324 19.62123885 68.21096191  3.          1.86249371]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -640.8540441830652
Optimization restart 2/5, f = -640.854044179528
Optimization restart 3/5, f = -640.8540441797672
Optimization restart 4/5, f = -362.7593223155518
Optimization restart 5/5, f = -640.8540441446555
[[20.         14.72185097  5.63366999 53.09765007  3.          1.54727455]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -644.6189323953213
Optimization restart 2/5, f = -364.8781051001955
Optimization restart 3/5, f = -644.6189324191138
Optimization restart 4/5, f = -644.6189324150902
Optimization restart 5/5, f = -644.6189324191

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -649.7376914714971
Optimization restart 3/5, f = -375.7145125631436
Optimization restart 4/5, f = -375.7139058988897
Optimization restart 5/5, f = -667.0675634976259
[[ 4.          8.15674799 26.8900371  40.3625635   3.          3.92469939]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -668.6592926956241
Optimization restart 2/5, f = -668.6592926955225
Optimization restart 3/5, f = -377.4831517977418
Optimization restart 4/5, f = -668.6592926956275
Optimization restart 5/5, f = -668.6592926939892
[[20.         19.12578284 22.67721997 56.29570694  3.          4.97448531]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -672.5518581329725
Optimization restart 2/5, f = -616.801008401813
Optimization restart 3/5, f = -672.5518883110963
Optimization restart 4/5, f = -379.4522665339

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -676.709561195742
[[ 3.         13.72628421 21.15872615 30.09217573  1.          4.8757601 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -691.600715430318
Optimization restart 2/5, f = -691.6007154366642
Optimization restart 3/5, f = -691.6007154364955
Optimization restart 4/5, f = -388.6755532982187
Optimization restart 5/5, f = -691.6007153871002
[[20.         17.36379566 26.59323492 65.13026167  3.          1.53877544]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -695.4068154789966
Optimization restart 2/5, f = -695.4070843514844


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -695.4070843934458
Optimization restart 4/5, f = -695.4070843933828
Optimization restart 5/5, f = -390.5120208091912
[[ 3.         24.11627816 21.69431256 56.16684435  1.          1.74824483]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -698.9791940497146
Optimization restart 2/5, f = -391.6242503188621
Optimization restart 3/5, f = -391.62372963095856
Optimization restart 4/5, f = -698.9791940435655
Optimization restart 5/5, f = -698.9791940496394
[[ 3.          9.13858674  5.41424681 60.92565101  3.          1.55099235]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -702.8312845201251
Optimization restart 2/5, f = -702.8312845267293
Optimization restart 3/5, f = -702.8312845270216
Optimization restart 4/5, f = -702.8312845259364
Optimization restart 5/5, f = -393.74899647

Optimization restart 4/5, f = -753.8032528964359
Optimization restart 5/5, f = -753.8032528990497
[[20.          8.39400817 19.05400373 30.4484115   1.          4.73325312]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -757.7327433670109
Optimization restart 2/5, f = -757.7330162256055
Optimization restart 3/5, f = -757.7330162256295
Optimization restart 4/5, f = -757.7330162171592
Optimization restart 5/5, f = -424.6756246457182
[[20.         24.86517827 16.95588625 54.30841251  1.          4.87536087]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -761.6302738649294
Optimization restart 2/5, f = -761.6303176079116
Optimization restart 3/5, f = -761.6303175242448
Optimization restart 4/5, f = -426.6975292924131
Optimization restart 5/5, f = -426.69752928236244
[[11.         24.72826366  5.87472587 63.51

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = -794.1805094353024
Optimization restart 5/5, f = -794.1805094107549
[[ 3.          8.53887813  5.21301452 42.23750365  3.          3.84284204]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -798.0957556017709
Optimization restart 2/5, f = -798.095792222384
Optimization restart 3/5, f = -798.0957922756623
Optimization restart 4/5, f = -448.50648706022423
Optimization restart 5/5, f = -448.50683852386055
[[15.          8.5937108  11.22746564 30.04444633  2.          1.81347191]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -800.6093880843799
Optimization restart 2/5, f = -450.61365867944266


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -800.6093880864173
Optimization restart 4/5, f = -800.6093880861503
Optimization restart 5/5, f = -800.6093880814298
[[20.          8.62102332  5.0155728  69.46639805  3.          2.7422401 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -804.5471675880619
Optimization restart 2/5, f = -452.56203823123474
Optimization restart 3/5, f = -452.56195047238845
Optimization restart 4/5, f = -452.5621204575308
Optimization restart 5/5, f = -804.5471675935239
[[20.         24.97373684 19.39646037 41.82605268  3.          1.60730239]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -808.4681279220258
Optimization restart 2/5, f = -808.4682165873071
Optimization restart 3/5, f = -454.03948536895865
Optimization restart 4/5, f = -454.03948537067276
Optimization restart 5/5, f = -808.46821

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -784.3878574210314
Optimization restart 3/5, f = -814.232988753228
Optimization restart 4/5, f = -814.2329887907646
Optimization restart 5/5, f = -458.0234967606702
[[20.         22.78110011 26.69658966 69.62542404  3.          4.91917306]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -817.938637890179
Optimization restart 2/5, f = -460.01294606564585
Optimization restart 3/5, f = -817.9386439048176
Optimization restart 4/5, f = -460.01294606564784
Optimization restart 5/5, f = -817.9386453987834
[[ 9.          8.12914721  5.27771526 31.93717349  3.          1.80113147]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -819.7196860537495
Optimization restart 2/5, f = -819.7196860546666
Optimization restart 3/5, f = -819.7196859749063
Optimization restart 4/5, f = -461.578659112

### Experimental Design - Integrated Variance Reduction

#### Model / Emulator (GP)

In [13]:
emulator_ird = GPy.models.GPRegression(init_X, init_Y)
emukit_model_ird = GPyModelWrapper(emulator_ird, n_restarts=5)
emukit_model_ird.optimize()

Optimization restart 1/5, f = -67.43039929354521
Optimization restart 2/5, f = -38.54329437168947
Optimization restart 3/5, f = -38.54329430667272
Optimization restart 4/5, f = -67.43039929590384
Optimization restart 5/5, f = -38.54329430667198


#### Acquisition Function

In [14]:
integrated_variance_reduction = IntegratedVarianceReduction(
    model=emukit_model_ird, 
    space=parameter_space, 
    num_monte_carlo_points=100
)

#### Optimizer

In [15]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [16]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ird,
    space = parameter_space,
    acquisition = integrated_variance_reduction,
    acquisition_optimizer = optimizer,
    batch_size = 1
)

In [17]:
ed_loop.run_loop(user_function_time_loss, 250)

Optimization restart 1/5, f = -67.43039929590384
Optimization restart 2/5, f = -67.43039929583665
Optimization restart 3/5, f = -38.54329430667198
Optimization restart 4/5, f = -38.54329430667198
Optimization restart 5/5, f = -38.54329430667198
[[ 5.         11.58872212  5.99043443 30.00883739  2.          3.27685996]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -71.20946055495767
Optimization restart 2/5, f = -40.38804659759489
Optimization restart 3/5, f = -40.38804659759487
Optimization restart 4/5, f = -71.20946055407197
Optimization restart 5/5, f = -40.388046597594865
[[20.         15.78620219  9.78726906 69.12174661  1.          3.50868374]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -75.25710399242175
Optimization restart 2/5, f = -42.71016914744808
Optimization restart 3/5, f = -42.710169147

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -131.84006786508985
[[20.         21.13453383 14.40460809 46.28110445  1.          3.26180362]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -136.08621041835897
Optimization restart 2/5, f = -75.61322445292028
Optimization restart 3/5, f = -136.0862104214174
Optimization restart 4/5, f = -75.6130759770798
Optimization restart 5/5, f = -75.61307593031523
[[ 3.         10.2593166   5.1291574  48.02172484  3.          4.87547831]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -131.2160799476294
Optimization restart 2/5, f = -131.21607994701537


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -127.31944928132862
Optimization restart 4/5, f = -76.6445524502221
Optimization restart 5/5, f = -131.21607994762076
[[ 3.          9.48719648 25.33907796 55.59619342  3.          2.59676086]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -133.67191479358263
Optimization restart 2/5, f = -78.84155829074797
Optimization restart 3/5, f = -131.94439387777211
Optimization restart 4/5, f = -78.8415583058123
Optimization restart 5/5, f = -78.8415582907518
[[20.         10.75985935 16.47334607 56.51903646  3.          2.99373789]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -137.72152997105215
Optimization restart 2/5, f = -137.72152997114435
Optimization restart 3/5, f = -81.03380303591264
Optimization restart 4/5, f = -137.72152997116353
Optimization restart 5/5, f = -137.72152

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -175.07566137200286
Optimization restart 4/5, f = -164.58870114141934
Optimization restart 5/5, f = -175.07566137199134
[[ 3.         22.88838571  5.72379231 60.30260253  1.          1.96338645]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -177.11502909197566
Optimization restart 2/5, f = -177.11503558835977
Optimization restart 3/5, f = -101.42449121447895
Optimization restart 4/5, f = -101.42449121763443
Optimization restart 5/5, f = -177.11503558825112
[[ 3.          9.45450561 23.32879104 43.10436527  2.          4.62622527]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -181.15518717349224
Optimization restart 2/5, f = -181.15518717497645
Optimization restart 3/5, f = -181.155187170488
Optimization restart 4/5, f = -103.42180333205634
Optimization restart 5/5, f = -103

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -219.67654195155524
[[20.         24.02701665 20.91695517 39.39115006  1.          2.30305818]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -225.43878225194487
Optimization restart 2/5, f = -129.8166497669397
Optimization restart 3/5, f = -225.4387922264424
Optimization restart 4/5, f = -211.89839419564794
Optimization restart 5/5, f = -129.81662441238365
[[ 8.          8.85511742 26.86958126 68.78781823  3.          2.59382128]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -229.2679007528525
Optimization restart 2/5, f = -229.26790075286817
Optimization restart 3/5, f = -229.2679007520143
Optimization restart 4/5, f = -229.26790075296284
Optimization restart 5/5, f = -132.04029938625786
[[19.          8.02525288 25.42622709 48.69271811  3.          2.20530485]]

User func

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -271.28643055500356
Optimization restart 5/5, f = -275.4514270727473
[[ 3.          8.90153502  7.0708962  48.40661563  3.          1.82868076]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -278.40454913362584
Optimization restart 2/5, f = -164.2640173842634
Optimization restart 3/5, f = -278.4045491625724
Optimization restart 4/5, f = -278.40454907156817
Optimization restart 5/5, f = -164.26401739488557
[[20.         24.67422984  7.25110635 30.9979579   1.          4.67667216]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -282.1069634065556
Optimization restart 2/5, f = -282.106963416382
Optimization restart 3/5, f = -282.10696341674515


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -280.45922089745375
Optimization restart 5/5, f = -166.21711440471512
[[19.          9.51877612 13.5723257  54.20801362  1.          4.65583305]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -285.9051603224995
Optimization restart 2/5, f = -285.9052778930022
Optimization restart 3/5, f = -285.905277893328
Optimization restart 4/5, f = -285.9052778932956
Optimization restart 5/5, f = -168.39030842081652
[[ 6.         24.87986998 24.32532455 68.38524792  2.          1.95229571]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -289.53361772095735
Optimization restart 2/5, f = -169.8973957966973
Optimization restart 3/5, f = -289.5341126791266
Optimization restart 4/5, f = -169.897534794737
Optimization restart 5/5, f = -289.53411267898406
[[12.         19.02100042 13.84615649 51.

[[11.          8.32690677  6.70680481 56.56659516  1.          1.66351211]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -339.3932566003733
Optimization restart 2/5, f = -339.3932566004329
Optimization restart 3/5, f = -339.39325660040004
Optimization restart 4/5, f = -199.27394951980506
Optimization restart 5/5, f = -339.39325659676445
[[ 6.         24.87792773 26.79837456 47.94099221  1.          1.67990969]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -342.9239407077433
Optimization restart 2/5, f = -200.24589338046218
Optimization restart 3/5, f = -342.92394070779557
Optimization restart 4/5, f = -342.9239407077286
Optimization restart 5/5, f = -342.9239406861174
[[ 3.         24.46759387  5.42579296 39.1896625   3.          1.65703694]]

User function time loss called with 1 inputs to simulate

Ev

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -353.12859690482856
[[11.         15.36398944 19.03918151 58.68232395  1.          4.22566454]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -356.91135686090644
Optimization restart 2/5, f = -208.27536548119056
Optimization restart 3/5, f = -356.91162135334156
Optimization restart 4/5, f = -356.9116213807572
Optimization restart 5/5, f = -208.27548411220417
[[10.         15.90540902  6.54563763 51.52872008  1.          1.60323096]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -360.22929723175963
Optimization restart 2/5, f = -360.2292972367893
Optimization restart 3/5, f = -360.22929723700935
Optimization restart 4/5, f = -360.2292972401994
Optimization restart 5/5, f = -210.4781126955439
[[ 9.         16.28085694 19.22828837 60.05953753  3.          4.98144832]]

User func

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -367.104345430265
Optimization restart 3/5, f = -220.280737781738
Optimization restart 4/5, f = -379.0152352296957
Optimization restart 5/5, f = -379.0152352210554
[[20.         12.39776513 10.5781287  42.02827079  1.          4.89852582]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -382.62163521896423
Optimization restart 2/5, f = -382.6216352186738
Optimization restart 3/5, f = -341.17954100829996
Optimization restart 4/5, f = -222.40673374777873
Optimization restart 5/5, f = -222.40673259881197
[[12.         13.46331204  5.11904479 30.85805053  2.          1.8000162 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -385.7047952639865
Optimization restart 2/5, f = -237.9803379635784
Optimization restart 3/5, f = -385.7047952673501
Optimization restart 4/5, f = -385.7047952

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -415.8391268506499
Optimization restart 4/5, f = -421.04311499313354
Optimization restart 5/5, f = -421.0431149931192
[[13.         18.59971243 18.56321636 39.358996    3.          2.14681407]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -424.85988851325385
Optimization restart 2/5, f = -380.64387423885626
Optimization restart 3/5, f = -424.85988851765273
Optimization restart 4/5, f = -424.85988851642844
Optimization restart 5/5, f = -424.85988851789097
[[20.          8.78538395 13.89860544 66.98830997  3.          4.28691042]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -428.67207158166013
Optimization restart 2/5, f = -428.6720715909941
Optimization restart 3/5, f = -428.6720714477343
Optimization restart 4/5, f = -428.6720715868489
Optimization restart 5/5, f = -428.67

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -433.6509192893424
Optimization restart 5/5, f = -446.1315627326145
[[ 9.         14.27260324 13.96578092 61.44547924  3.          4.92273687]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -450.003375833972
Optimization restart 2/5, f = -450.00337963636395
Optimization restart 3/5, f = -402.71157908686814
Optimization restart 4/5, f = -450.003379457135
Optimization restart 5/5, f = -402.71128273139914
[[ 3.         18.25768898 12.63718515 39.94940811  3.          1.97218582]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -452.6118517361928
Optimization restart 2/5, f = -452.61185173581646
Optimization restart 3/5, f = -452.61185172844347
Optimization restart 4/5, f = -452.6118517261586
Optimization restart 5/5, f = -452.61185173615115
[[20.         24.94664985 26.52092791 55

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -451.9073177801541
Optimization restart 4/5, f = -414.90457417118836
Optimization restart 5/5, f = -263.39397088475505
[[20.         18.25614279 18.06562756 38.96409545  3.          4.8797269 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -463.99845050540426


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -440.3606992661218
Optimization restart 3/5, f = -463.9984583428917
Optimization restart 4/5, f = -463.99845834189307
Optimization restart 5/5, f = -265.2382568904392
[[20.         13.90835947 16.3104066  46.53522174  1.          1.68953306]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -467.70370123931616
Optimization restart 2/5, f = -267.1870468719019
Optimization restart 3/5, f = -467.70370123664986
Optimization restart 4/5, f = -467.7037012394118
Optimization restart 5/5, f = -267.1870467483005
[[11.         24.5647459  16.3215843  39.91416302  2.          1.54495424]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -471.24313331472035
Optimization restart 2/5, f = -471.24313331456034
Optimization restart 3/5, f = -471.24313331457006
Optimization restart 4/5, f = -471.243

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -492.8522199844963
Optimization restart 4/5, f = -499.3213692314939
Optimization restart 5/5, f = -439.1084261209477
[[19.          8.01426448 26.5026286  54.27518411  1.          1.61192008]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -509.2607619001988
Optimization restart 2/5, f = -509.26076189987526
Optimization restart 3/5, f = -509.2607619001236
Optimization restart 4/5, f = -509.26076190016323


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -504.29336749398544
[[ 3.          8.28282577 12.93707497 30.04983392  1.          3.35385648]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -511.8059535634523
Optimization restart 2/5, f = -291.93591013010007
Optimization restart 3/5, f = -511.8060849981004
Optimization restart 4/5, f = -511.8060849981599
Optimization restart 5/5, f = -511.80608491211706
[[12.         24.67714786 15.84786496 60.41797665  3.          4.83245259]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -515.4455070932917
Optimization restart 2/5, f = -515.4455070963276
Optimization restart 3/5, f = -515.44550710374
Optimization restart 4/5, f = -515.4455070994843
Optimization restart 5/5, f = -515.4455070851046
[[ 3.         15.48860477  5.26073955 42.61875147  3.          1.55220716]]

User function t

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -546.1466923670728
Optimization restart 3/5, f = -548.3437819659714
Optimization restart 4/5, f = -548.343781970425
Optimization restart 5/5, f = -548.343781971312
[[ 3.         15.96677375 12.56141918 34.77902582  3.          1.67113556]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -551.7121331399046
Optimization restart 2/5, f = -551.7121331399984
Optimization restart 3/5, f = -551.7121331399321
Optimization restart 4/5, f = -551.712133139998
Optimization restart 5/5, f = -551.7121331398937
[[ 3.         17.38399847  9.68418734 67.07837904  3.          4.69331979]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -554.1444946020782
Optimization restart 2/5, f = -554.144494598989
Optimization restart 3/5, f = -481.6129890527248
Optimization restart 4/5, f = -315.5910411732936

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -548.1105856532628
Optimization restart 5/5, f = -557.822620072025
[[ 4.         19.52672878 26.96485016 65.76856436  3.          1.56419537]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -556.8835261571575
Optimization restart 2/5, f = -556.8835261746796
Optimization restart 3/5, f = -556.8835261770196
Optimization restart 4/5, f = -556.883526042799
Optimization restart 5/5, f = -556.8835261513793
[[11.          8.9007769   6.3694818  30.76478701  3.          1.64879731]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -560.5042313710949
Optimization restart 2/5, f = -319.6720524785808
Optimization restart 3/5, f = -560.5042313819079
Optimization restart 4/5, f = -560.5042313787985
Optimization restart 5/5, f = -319.6720436442214
[[15.         16.4589697  13.65940078 30.08067

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -572.7493487605662
[[10.         13.77133459  5.12438934 59.80992123  3.          1.5050741 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -578.5845498335797
Optimization restart 2/5, f = -578.584566698792
Optimization restart 3/5, f = -578.5845666973328
Optimization restart 4/5, f = -578.5845666987948
Optimization restart 5/5, f = -328.73774323114793
[[20.         19.82716098 17.07258016 45.32884865  1.          4.91754182]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -582.4784810005856
Optimization restart 2/5, f = -582.4785010398012
Optimization restart 3/5, f = -582.478501152531
Optimization restart 4/5, f = -582.478501152544
Optimization restart 5/5, f = -582.4785011510803
[[ 5.         22.59549277  5.40452883 41.18987313  1.          4.62496245]]

User function time

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -609.3641602004855
Optimization restart 3/5, f = -351.3816002517557
Optimization restart 4/5, f = -616.9044956397323
Optimization restart 5/5, f = -616.9044956401731
[[20.         20.50961687 14.28040999 68.41319045  3.          4.46396641]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -620.7457503906953
Optimization restart 2/5, f = -620.7457845434789
Optimization restart 3/5, f = -353.4771133808622
Optimization restart 4/5, f = -620.7457843237157
Optimization restart 5/5, f = -367.59216385426265
[[19.          8.26920575 25.16622551 66.95876766  3.          4.88062486]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -623.8600515341569
Optimization restart 2/5, f = -623.8602286086738
Optimization restart 3/5, f = -355.5630474431672
Optimization restart 4/5, f = -623.86022885

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -615.7530191303013
[[ 3.         16.40164931 17.43627324 35.49708643  3.          4.76806799]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -630.3883380085343
Optimization restart 2/5, f = -630.3885820351586
Optimization restart 3/5, f = -630.3885820353389
Optimization restart 4/5, f = -630.388582034691
Optimization restart 5/5, f = -630.3885820303464
[[12.         18.35287192 26.81940957 63.26268615  1.          4.36782583]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -634.1961575592843
Optimization restart 2/5, f = -634.196254832006
Optimization restart 3/5, f = -360.18622101606513
Optimization restart 4/5, f = -634.1962548337551
Optimization restart 5/5, f = -634.1962546654527
[[20.         15.57263934 14.13364438 57.9099539   1.          1.86409152]]

User function tim

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -653.3993962282021
Optimization restart 3/5, f = -377.14242073738
Optimization restart 4/5, f = -668.5953563926238


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -665.6558381324288
[[20.         24.29606498 19.47442947 33.88671874  1.          4.58459562]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -672.3906374399864
Optimization restart 2/5, f = -672.3909774631248
Optimization restart 3/5, f = -672.3909774580128
Optimization restart 4/5, f = -672.3909773476794
Optimization restart 5/5, f = -672.3909774641015
[[19.         24.08914795  7.02721879 48.16088544  1.          4.79483607]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -676.1440297931243
Optimization restart 2/5, f = -676.1440297872609
Optimization restart 3/5, f = -676.1440297953633
Optimization restart 4/5, f = -676.1440297922512
Optimization restart 5/5, f = -380.73500492563693
[[20.         14.62876345 19.77759315 40.05903078  2.          4.79394933]]

User function t

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -660.5413171678896
[[10.         16.88092312  5.73757902 57.57976998  3.          4.23787831]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -683.3335945431747
Optimization restart 2/5, f = -683.333594544417
Optimization restart 3/5, f = -683.333594541584
Optimization restart 4/5, f = -384.4615165172065
Optimization restart 5/5, f = -683.3335945444068
[[ 9.         20.08002622  6.40402024 69.60009325  1.          1.58206638]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -687.0516751699737
Optimization restart 2/5, f = -687.0517493733882
Optimization restart 3/5, f = -687.0517493762309
Optimization restart 4/5, f = -386.7032666042092
Optimization restart 5/5, f = -687.0517493535623
[[ 7.         18.63538327  9.2708068  37.19697469  3.          1.66496853]]

User function time

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -714.368946273355
Optimization restart 4/5, f = -406.01369992310083
Optimization restart 5/5, f = -406.01369990549426
[[11.         18.86965429  8.67134311 30.67897172  1.          3.2057884 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -726.3916545492581
Optimization restart 2/5, f = -408.0841811333272
Optimization restart 3/5, f = -726.391654548935
Optimization restart 4/5, f = -726.3916545069803
Optimization restart 5/5, f = -726.3916545490436
[[ 9.         24.90916347 15.31665166 54.11550338  1.          1.6664815 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -730.267651968597
Optimization restart 2/5, f = -730.2676817091293
Optimization restart 3/5, f = -409.90283630373943


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = -730.2676827063574
Optimization restart 5/5, f = -730.2676827139036
[[20.         22.91463486 23.38070304 31.07060097  1.          3.38050629]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -734.0902444989259
Optimization restart 2/5, f = -734.0903701204539
Optimization restart 3/5, f = -411.2557790168397
Optimization restart 4/5, f = -734.0903701220932
Optimization restart 5/5, f = -734.0903701219416
[[20.         12.70852554 11.73166751 30.44083214  1.          4.4677533 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -737.9815710888003
Optimization restart 2/5, f = -737.9815711034472
Optimization restart 3/5, f = -737.9815711046568
Optimization restart 4/5, f = -737.9815710988642
Optimization restart 5/5, f = -737.9815711046572
[[20.          8.13095664  5.15896193 67.018

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = -741.539971546309
Optimization restart 3/5, f = -741.539971552928
Optimization restart 4/5, f = -741.5399715530035
Optimization restart 5/5, f = -741.539971552811
[[16.         14.42019879  5.09299644 58.36350875  1.          1.57853281]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -745.3115052981157
Optimization restart 2/5, f = -745.3121052430181


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -731.8623760512722
Optimization restart 4/5, f = -745.3121079722405
Optimization restart 5/5, f = -417.44503316170244
[[ 3.         24.37050232 25.92769428 32.42493869  1.          2.31968194]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -749.0358527515476
Optimization restart 2/5, f = -749.0360703696042
Optimization restart 3/5, f = -417.33013703704654
Optimization restart 4/5, f = -749.0360703685412
Optimization restart 5/5, f = -749.0360703696016
[[ 3.          8.58397894 11.07430606 31.06690393  1.          1.84706552]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -751.3770031196686
Optimization restart 2/5, f = -751.3770073696787
Optimization restart 3/5, f = -751.377007346396
Optimization restart 4/5, f = -751.3770073939962
Optimization restart 5/5, f = -751.37700739

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -757.2801342611822
Optimization restart 5/5, f = -768.7860588213034
[[ 3.         17.74544385 26.99631822 63.13486     1.          4.8468495 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -772.6162094574837
Optimization restart 2/5, f = -430.72926883561513
Optimization restart 3/5, f = -430.7292728016615
Optimization restart 4/5, f = -430.7292688694475
Optimization restart 5/5, f = -772.6167269542259
[[20.         24.27545351 26.58660538 43.36757953  1.          1.55870956]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -776.4103739735102
Optimization restart 2/5, f = -776.4104521563569
Optimization restart 3/5, f = -776.4104521525351
Optimization restart 4/5, f = -776.4104521558932
Optimization restart 5/5, f = -776.4104521563527
[[10.         15.48714662 21.55892371 44.10

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -823.9876756361762
Optimization restart 3/5, f = -463.065802049779
Optimization restart 4/5, f = -827.9216393663904
Optimization restart 5/5, f = -827.9216392779564
[[ 3.         11.10164981 12.00819124 35.74523947  3.          4.9855956 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -830.8138122272103
Optimization restart 2/5, f = -465.00980089812464
Optimization restart 3/5, f = -709.8278784183763
Optimization restart 4/5, f = -830.8138122185965
Optimization restart 5/5, f = -830.8138121919378
[[14.         20.44435825 26.29125675 30.44564645  3.          2.4842664 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -834.4330694866426
Optimization restart 2/5, f = -834.4330694870378
Optimization restart 3/5, f = -834.4330694811518
Optimization restart 4/5, f = -834.433069487

 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -835.8999557290584
Optimization restart 3/5, f = -846.0126621974962
Optimization restart 4/5, f = -846.0126621950936
Optimization restart 5/5, f = -471.36509782657583
[[14.          8.01889895 15.31481639 32.00037208  1.          4.96250813]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -849.8347294995328
Optimization restart 2/5, f = -849.8347405154428
Optimization restart 3/5, f = -849.8347405154785
Optimization restart 4/5, f = -849.8347405165757
Optimization restart 5/5, f = -473.31879721082936
[[20.         20.13861249 19.12064368 44.81978578  3.          1.50927049]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -853.3088732610246
Optimization restart 2/5, f = -853.3088732699964
Optimization restart 3/5, f = -474.8048560659156
Optimization restart 4/5, f = -523.8814133

### Random GP

Supervised learning

In [18]:
emulator_rnd = GPy.models.GPRegression(train_X, train_Y)
emukit_model_rnd = GPyModelWrapper(emulator_rnd, n_restarts=50)
emukit_model_rnd.optimize()
emulator_rnd

Optimization restart 1/50, f = -960.918285427231
Optimization restart 2/50, f = -511.62741978109585
Optimization restart 3/50, f = -960.9182854551038
Optimization restart 4/50, f = -960.9182854540743
Optimization restart 5/50, f = -511.6274077783679
Optimization restart 6/50, f = -511.6274047256805
Optimization restart 7/50, f = -960.918285420086
Optimization restart 8/50, f = -960.9182854551186
Optimization restart 9/50, f = -960.9182854521168
Optimization restart 10/50, f = -960.9182854478145
Optimization restart 11/50, f = -960.9182854549638
Optimization restart 12/50, f = -960.9182854550697
Optimization restart 13/50, f = -511.6274047394052
Optimization restart 14/50, f = -960.9182854549883
Optimization restart 15/50, f = -960.9182854548042
Optimization restart 16/50, f = -960.9182854549969
Optimization restart 17/50, f = -960.9182854538171
Optimization restart 18/50, f = -960.9182853683776


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 19/50, f = -950.1615392299846
Optimization restart 20/50, f = -511.6274047799458
Optimization restart 21/50, f = -960.9182854551166
Optimization restart 22/50, f = -960.9182854290888
Optimization restart 23/50, f = -960.9182854540213
Optimization restart 24/50, f = -960.9182853502728
Optimization restart 25/50, f = -960.9182854548933
Optimization restart 26/50, f = -960.9182854504681
Optimization restart 27/50, f = -511.6274167340782
Optimization restart 28/50, f = -960.9182854323303
Optimization restart 29/50, f = -511.62780951942483
Optimization restart 30/50, f = -511.6274047256444
Optimization restart 31/50, f = -511.627405169756
Optimization restart 32/50, f = -960.9182854487765
Optimization restart 33/50, f = -960.9182854551025
Optimization restart 34/50, f = -511.62748091487185
Optimization restart 35/50, f = -960.918285446656
Optimization restart 36/50, f = -511.62740472563985
Optimization restart 37/50, f = -511.6276665837537
Optimization restart 38/50, f 

### Evaluate

Evaluate RMSE of each model on our test set of 50 randomly selected points.

In [19]:
pred_Y, pred_Y_variance = emukit_model_ed.predict(test_X)
mse_ed = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Model Variance RMSE: ', mse_ed)

Experimental Design w/ Model Variance RMSE:  0.008533233040113455


In [20]:
pred_Y, pred_Y_variance = emukit_model_ird.predict(test_X)
mse_ird = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Integrated Variance Reduction RMSE: ', mse_ird)

Experimental Design w/ Integrated Variance Reduction RMSE:  0.0060967586281770545


In [21]:
pred_Y, pred_Y_variance = emukit_model_rnd.predict(test_X)
mse_rnd = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Random GP RMSE: ', mse_rnd)

Random GP RMSE:  0.006403011859194119


In [22]:
p = 1 - (mse_ed/mse_rnd)
f'Experimental Design w/ Model Variance is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Model Variance is -33.269% better than training on random points.'

In [23]:
p = 1 - (mse_ird/mse_rnd)
f'Experimental Design w/ Integrated Variance Reduction is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Integrated Variance Reduction is 4.783% better than training on random points.'

### Save Models

In [25]:
with open(f'experimental_design_new_outputs/models/model_variance_20_init_points_250_loops_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_ed, f)

with open(f'experimental_design_new_outputs/models/integrated_variance_reduction_20_init_points_250_loops_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_ird, f)
        
with open(f'experimental_design_new_outputs/models/270_random_points_supervised_GP_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_rnd, f)