In [1]:
%cd ../

/Users/harrysonghurst/Documents/Coursework/L48 Machine Learning and the Physical World/TrafficEmu copy


In [2]:
# If you get a SciPy error when installing Emukit, build it from source:

# git clone https://github.com/amzn/Emukit.git
# cd Emukit
# pip install -r requirements/requirements.txt
# python setup.py develop

In [3]:
import numpy as np
import pickle
import emukit as ek
import GPy

from emukit.model_wrappers import GPyModelWrapper
from emukit.experimental_design.experimental_design_loop import ExperimentalDesignLoop
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.core.initial_designs import RandomDesign, latin_design
from emukit.experimental_design.acquisitions import ModelVariance, IntegratedVarianceReduction
from emukit.core.loop import UserFunctionWrapper
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.bayesian_optimization.loops import BayesianOptimizationLoop
from emukit.core.optimization import GradientAcquisitionOptimizer

from sumo_grid_simulation.grid_simulation import Simulator
import experimental_design.config as config

### Pseudocode

Fitting a gaussian process to a simulator using Emukit takes the following form (taken from L48 lectures):

```
initialize GP with some randomly chosen points
while stopping condition is not met:
    compute candidate point(s) using GP and acquisition funciton (model_variance) -> new point
    evaluate this new point with our simulator/user function -> observation
    update model with new observation -> new GP
```

### Simulator

In [4]:
simulator = Simulator(end_time=300)

### User Function
 
This is the function we want to understand. Namedly, how are CO2 emissions and timeLoss (the time lost due to driving below the ideal speed) affected by the following parameters: 

```
gridSize: the size of the grid network where the simulation is carried out
edgeMaxSpeed: legal speed limit in m/s - this can be exceeded (11.11 == 40km/h)
maxSpeed: the absolute maximum velocity of any vehicle in m/s (55.55 == 200 km/h)
edgeLength: length of the roads between intersections in meters
numLanes: number of lanes per road
accel: The acceleration ability of vehicles in m/s^2.
```

*A complete list of parmeters analysed is discussed in our report.*

In [5]:
def user_function_co2(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function time loss called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.005
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * 10
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average co2 / average route duration
        CO2 = s['CO2']/s['num_emissions_samples']
        # average emissions / average route length
        result.append(CO2/s['duration'])
        i += 1
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

### Model Inputs / parameter space

In [6]:
gridSize = DiscreteParameter('gridSize', domain=[3, 4, 5, 6, 7, 8, 9, 10])
edgeMaxSpeed = ContinuousParameter('edgeMaxSpeed', min_value=8, max_value=20)  # 28.8 km/h to 90 km/h
numberOfLanes = DiscreteParameter('numberOfLanes', domain=[1, 2, 3])
accel = ContinuousParameter('accel', 1., 3.)

parameter_space = ParameterSpace([gridSize, edgeMaxSpeed, numberOfLanes, accel])

### Get init, test, and train points

Train points are used to optimize a GP without experimental design - to verify experimental design works.

In [9]:
design = RandomDesign(parameter_space)
init_X = design.get_samples(20)
init_Y = user_function_co2(init_X)

design = RandomDesign(parameter_space)
test_X = design.get_samples(50)
test_Y = user_function_co2(test_X)

design = RandomDesign(parameter_space)
train_X = design.get_samples(250)
train_Y = user_function_co2(train_X)

[[ 6.         19.02017817  1.          1.31260122]
 [ 5.         16.49778617  1.          1.72897976]
 [ 7.         13.74056629  3.          2.59172409]
 [ 8.          9.69058353  3.          1.19613451]
 [ 5.         14.44633812  3.          2.06263358]
 [ 8.         18.89744143  3.          1.92112732]
 [ 5.         19.6047041   3.          1.84365678]
 [10.         12.12637465  3.          2.78286927]
 [ 8.         15.05442344  2.          1.70181205]
 [ 6.         16.7079148   2.          1.83815463]
 [ 3.         12.37940295  3.          2.62570956]
 [ 6.         17.35444002  2.          1.0341496 ]
 [ 7.         10.05389895  1.          2.89729229]
 [ 6.          9.48228134  3.          2.95066113]
 [ 8.         13.81777898  3.          2.27152095]
 [ 8.         10.30946286  2.          2.38940478]
 [ 5.         10.22267967  3.          1.45374008]
 [ 4.         15.34765972  2.          1.76085092]
 [ 5.         10.72628409  1.          1.94130258]
 [ 5.         16.13288434  3.  

 Retrying in 1 seconds

Evaluating input: 2 of 250

 Retrying in 1 seconds

Evaluating input: 3 of 250

 Retrying in 1 seconds

Evaluating input: 4 of 250

 Retrying in 1 seconds

Evaluating input: 5 of 250

 Retrying in 1 seconds

Evaluating input: 6 of 250

 Retrying in 1 seconds

Evaluating input: 7 of 250

 Retrying in 1 seconds

Evaluating input: 8 of 250

 Retrying in 1 seconds

Evaluating input: 9 of 250

 Retrying in 1 seconds

Evaluating input: 10 of 250

 Retrying in 1 seconds

Evaluating input: 11 of 250

 Retrying in 1 seconds

Evaluating input: 12 of 250

 Retrying in 1 seconds

Evaluating input: 13 of 250

 Retrying in 1 seconds

Evaluating input: 14 of 250

 Retrying in 1 seconds

Evaluating input: 15 of 250

 Retrying in 1 seconds

Evaluating input: 16 of 250

 Retrying in 1 seconds

Evaluating input: 17 of 250

 Retrying in 1 seconds

Evaluating input: 18 of 250

 Retrying in 1 seconds

Evaluating input: 19 of 250

 Retrying in 1 seconds

Evaluating input: 20 of 250

 

 Retrying in 1 seconds

Evaluating input: 156 of 250

 Retrying in 1 seconds

Evaluating input: 157 of 250

 Retrying in 1 seconds

Evaluating input: 158 of 250

 Retrying in 1 seconds

Evaluating input: 159 of 250

 Retrying in 1 seconds

Evaluating input: 160 of 250

 Retrying in 1 seconds

Evaluating input: 161 of 250

 Retrying in 1 seconds

Evaluating input: 162 of 250

 Retrying in 1 seconds

Evaluating input: 163 of 250

 Retrying in 1 seconds

Evaluating input: 164 of 250

 Retrying in 1 seconds

Evaluating input: 165 of 250

 Retrying in 1 seconds

Evaluating input: 166 of 250

 Retrying in 1 seconds

Evaluating input: 167 of 250

 Retrying in 1 seconds

Evaluating input: 168 of 250

 Retrying in 1 seconds

Evaluating input: 169 of 250

 Retrying in 1 seconds

Evaluating input: 170 of 250

 Retrying in 1 seconds

Evaluating input: 171 of 250

 Retrying in 1 seconds

Evaluating input: 172 of 250

 Retrying in 1 seconds

Evaluating input: 173 of 250

 Retrying in 1 seconds

Eval

### Experimental Design - Model Variance

#### Model / Emulator (GP)

Our surrogate model is our emulator. In this case, a gaussian process.

In [10]:
emulator_ed = GPy.models.GPRegression(init_X, init_Y)
emukit_model_ed = GPyModelWrapper(emulator_ed, n_restarts=5)
emukit_model_ed.optimize()
emulator_ed

Optimization restart 1/5, f = 94.28493209156616
Optimization restart 2/5, f = 94.28493210143097
Optimization restart 3/5, f = 94.28493209120934
Optimization restart 4/5, f = 94.28493209704962
Optimization restart 5/5, f = 94.28493218443478


#### Acquisition Function

In [11]:
model_variance = ModelVariance(model=emukit_model_ed)

#### Optimizer

In [12]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [13]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ed,
    space = parameter_space,
    acquisition = model_variance,
    acquisition_optimizer = optimizer,
    update_interval = 1,
    batch_size = 5
)

In [14]:
ed_loop.run_loop(user_function_co2, 50)

Optimization restart 1/5, f = 94.28493209120934
Optimization restart 2/5, f = 94.28493209120747
Optimization restart 3/5, f = 94.28493209178791
Optimization restart 4/5, f = 94.28493209126802
Optimization restart 5/5, f = 98.16130356665495


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


[[10. 20.  1.  3.]
 [ 3.  8.  1.  1.]
 [10.  8.  1.  1.]
 [ 3. 20.  1.  3.]
 [10. 20.  1.  1.]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 1/5, f = 122.08807990759045
Optimization restart 2/5, f = 122.08807209097736
Optimization restart 3/5, f = 122.08807209050556
Optimization restart 4/5, f = 131.42163913619584
Optimization restart 5/5, f = 122.08807212451238
[[ 3. 20.  3.  1.]
 [ 3.  8.  3.  3.]
 [10.  8.  3.  1.]
 [10. 20.  3.  3.]
 [10.  8.  1.  3.]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 144.28719988469717
Optimization restart 2/5, f = 144.2030335586252
Optimization restart 3/5, f = 144.20303355561413
Optimization restart 4/5, f = 144.20303356699748
Optimization restart 5/5, f = 180.95749488722555
[[10.         13.80040276  1.          1.        ]
 [ 3.         14.23473981  1.          1.        ]
 [ 3.         20.          3.          3.        ]
 [10.         20.          3.          1.        ]
 [ 3.          8.          1.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 1/5, f = 164.43861220975668
Optimization restart 2/5, f = 183.8155989249987
Optimization restart 3/5, f = 168.5790485806737
Optimization restart 4/5, f = 164.40794318591162
Optimization restart 5/5, f = 164.40794311268263
[[10.         15.73072366  1.          3.        ]
 [10.          8.          3.          3.        ]
 [ 3.          8.          3.          1.        ]
 [ 3.         14.53250944  1.          3.        ]
 [ 3.         20.          1.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 183.9670264604233
Optimization restart 2/5, f = 183.9604519240142
Optimization restart 3/5, f = 183.96045191687625
Optimization restart 4/5, f = 183.96045194550456
Optimization restart 5/5, f = 183.9604519163051
[[10.         15.90260195  3.          1.        ]
 [ 7.          8.          1.          1.        ]
 [ 7.         20.          1.          3.        ]
 [ 3.         12.49800502  3.          1.        ]
 [ 3.         16.88612241  3.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 202.68505343529807
Optimization restart 2/5, f = 202.67772255627688
Optimization restart 3/5, f = 202.6777225562376
Optimization restart 4/5, f = 202.6777225569852
Optimization restart 5/5, f = 202.67772255633238
[[10.         11.52927346  1.          3.        ]
 [10.         11.40581568  3.          1.        ]
 [ 7.          8.          3.          3.        ]
 [ 3.         20.          1.          1.        ]
 [10.         16.89603415  3.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 220.3539841141572
Optimization restart 2/5, f = 267.8849780623735
Optimization restart 3/5, f = 244.95443998000738
Optimization restart 4/5, f = 220.35159782247612
Optimization restart 5/5, f = 220.3515978225709
[[10.          8.          1.          3.        ]
 [ 3.          8.          3.          1.        ]
 [ 3.          8.          1.          3.        ]
 [10.         20.          1.          1.        ]
 [ 3.         11.12831296  1.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 237.6123483190724
Optimization restart 2/5, f = 217.79287013989645
Optimization restart 3/5, f = 237.60929245654006
Optimization restart 4/5, f = 217.79285056049588
Optimization restart 5/5, f = 217.79284371313796
[[10.         17.5192432   1.          1.        ]
 [ 7.         12.45621803  1.          1.        ]
 [ 3.         17.65183519  1.          1.03303886]
 [ 7.         13.46639581  1.          3.        ]
 [ 3.         10.80673926  1.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 240.56569287856553
Optimization restart 2/5, f = 254.0811430426424
Optimization restart 3/5, f = 240.50067454575856
Optimization restart 4/5, f = 240.5006684351022
Optimization restart 5/5, f = 254.08114305264752
[[ 5.          8.          3.          1.        ]
 [ 8.         17.54407679  1.          3.        ]
 [10.         10.30090792  1.          1.        ]
 [ 3.         16.04772055  3.          1.        ]
 [ 6.          8.01694305  1.          2.81862575]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 261.5896819989531
Optimization restart 2/5, f = 261.3541193188762
Optimization restart 3/5, f = 271.63963641669466
Optimization restart 4/5, f = 271.63963641234903
Optimization restart 5/5, f = 271.6396364113636
[[ 6.         18.48463402  3.          3.        ]
 [ 4.         18.22157348  1.          3.        ]
 [ 3.          9.33831359  2.          2.03143568]
 [ 7.         20.          3.          1.        ]
 [10.          9.79720473  3.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 294.4981340378937
Optimization restart 2/5, f = 309.414705538984
Optimization restart 3/5, f = 309.4147055391012
Optimization restart 4/5, f = 309.41470553891776
Optimization restart 5/5, f = 309.4147055398482
[[ 7.         13.24033813  3.          1.        ]
 [10.         18.36926866  2.          3.        ]
 [ 3.         18.42223566  3.          1.71621884]
 [ 8.         20.          1.          1.        ]
 [ 8.         20.          3.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 1/5, f = 315.1842060639418
Optimization restart 2/5, f = 395.2514802544615
Optimization restart 3/5, f = 329.9449438191334
Optimization restart 4/5, f = 329.9449438174459
Optimization restart 5/5, f = 329.9449438174116
[[ 5.          9.1959122   1.          1.        ]
 [ 3.         10.05908183  3.          3.        ]
 [ 8.         16.16078661  3.          3.        ]
 [ 5.         12.20713472  2.          3.        ]
 [ 5.         13.74158171  1.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 335.32143685068894
Optimization restart 2/5, f = 348.38506877635217
Optimization restart 3/5, f = 348.38506877620796
Optimization restart 4/5, f = 348.38506877583427
Optimization restart 5/5, f = 348.3850687753261
[[10.         14.31874799  2.          3.        ]
 [ 3.         17.15964178  1.          3.        ]
 [ 9.          8.          2.          1.94526436]
 [ 8.         16.26020514  1.          1.        ]
 [ 8.         17.04233999  3.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 363.0433656905083
Optimization restart 2/5, f = 367.99272275549447
Optimization restart 3/5, f = 367.9927224269056
Optimization restart 4/5, f = 360.85784768830877
Optimization restart 5/5, f = 367.9927224297468
[[ 5.         15.30381708  1.          3.        ]
 [ 8.          9.68419647  1.          1.        ]
 [10.         18.14932997  3.          1.        ]
 [ 8.          8.          1.          3.        ]
 [ 8.         11.44378731  3.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 381.0654936539378
Optimization restart 2/5, f = 386.6244716009053
Optimization restart 3/5, f = 386.62447160207364
Optimization restart 4/5, f = 386.62447161585396
Optimization restart 5/5, f = 381.06463163221844
[[ 3.         14.53495695  3.          3.        ]
 [ 3.         10.03980734  3.          1.        ]
 [ 5.         20.          1.          1.        ]
 [ 5.         19.98789323  1.          2.94204995]
 [10.         13.53867837  3.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 407.2581464239165
Optimization restart 2/5, f = 404.9235085697463
Optimization restart 3/5, f = 404.9235086544318
Optimization restart 4/5, f = 507.1814373356749
Optimization restart 5/5, f = 404.92350856974645
[[ 3. 20.  3.  3.]
 [10. 20.  1.  3.]
 [10.  8.  3.  1.]
 [ 3.  8.  1.  1.]
 [10. 20.  3.  3.]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 423.1654499199487
Optimization restart 2/5, f = 423.1654234344898


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = 423.16542343640236
Optimization restart 4/5, f = 423.16542343376227
Optimization restart 5/5, f = 423.1654234337835
[[10.  8.  1.  1.]
 [ 3. 20.  3.  1.]
 [ 3.  8.  3.  3.]
 [ 3. 20.  1.  3.]
 [ 3. 20.  1.  1.]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 442.35876047262093
Optimization restart 2/5, f = 442.34982399683724
Optimization restart 3/5, f = 442.3498240329097
Optimization restart 4/5, f = 427.5906725212269
Optimization restart 5/5, f = 442.34982399541116
[[ 5.         17.59128497  2.          1.30941877]
 [ 5.         16.33757613  2.          2.55330803]
 [ 7.          9.67816069  1.          2.76945236]
 [ 7.         19.68629055  2.          2.09807673]
 [ 7.         11.47594744  3.          2.19805138]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 458.027140628336
Optimization restart 2/5, f = 459.52300688057096
Optimization restart 3/5, f = 459.5230068799858
Optimization restart 4/5, f = 459.5230076073342
Optimization restart 5/5, f = 458.027675622011
[[ 5.          8.1166476   2.          2.82038366]
 [ 3.         16.88343083  1.          2.89663943]
 [ 9.         15.85062598  3.          1.59468773]
 [ 3.         17.26501249  1.          1.881818  ]
 [ 5.         15.1071047   3.          2.41341754]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 1/5, f = 490.12989791750266
Optimization restart 2/5, f = 612.965585184266
Optimization restart 3/5, f = 504.0148178126673
Optimization restart 4/5, f = 477.354113419603
Optimization restart 5/5, f = 389.919932276107
[[ 9.         12.07331556  1.          1.        ]
 [ 5.         12.16368105  3.          1.        ]
 [ 9.         13.48367937  1.          3.        ]
 [ 4.         12.6787184   1.          2.14808359]
 [ 9.          9.65821354  1.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 415.0674018255847
Optimization restart 2/5, f = 497.77333597353584
Optimization restart 3/5, f = 415.06725767189806
Optimization restart 4/5, f = 497.7733360470798


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = 497.77333597353277
[[ 7.          8.          3.          1.        ]
 [ 7.         15.53150696  1.          3.        ]
 [ 7.         14.71076055  1.          1.        ]
 [ 7.         15.26868275  3.          1.        ]
 [ 4.          9.42474305  1.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 437.26090378346447
Optimization restart 2/5, f = 437.244161127831
Optimization restart 3/5, f = 515.2903709519841
Optimization restart 4/5, f = 515.2903711742756
Optimization restart 5/5, f = 515.290370960533
[[10.         15.65253057  1.          1.        ]
 [ 6.         17.83234831  1.          3.        ]
 [ 9.         18.87819016  1.          1.90589731]
 [ 6.         20.          3.          3.        ]
 [ 3.         14.28626328  3.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 461.42799401617987
Optimization restart 2/5, f = 542.665543351245
Optimization restart 3/5, f = 542.6655433521844
Optimization restart 4/5, f = 542.6655433516754
Optimization restart 5/5, f = 542.6655433512282
[[10.          9.69529188  3.          1.41701621]
 [ 6.         10.45642085  2.          1.        ]
 [10.         14.89104021  3.          3.        ]
 [ 8.         11.68933122  3.          1.        ]
 [ 8.         18.59113841  2.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 482.2764542244846
Optimization restart 2/5, f = 561.0196759360385
Optimization restart 3/5, f = 561.0196759301425
Optimization restart 4/5, f = 561.0196759306853
Optimization restart 5/5, f = 561.0196759311741
[[ 5.         11.14398248  3.          3.        ]
 [ 6.         18.48999768  3.          1.        ]
 [ 8.          8.99506915  3.          3.        ]
 [ 4.         18.52218028  3.          3.        ]
 [ 4.          8.          1.          1.70829891]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 505.87111811171366
Optimization restart 2/5, f = 590.4481363541324
Optimization restart 3/5, f = 590.4481363533321
Optimization restart 4/5, f = 740.9460883858495


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 590.4481363533989
[[10.         16.76047388  2.          2.05839053]
 [10.         12.32253102  2.          1.80040842]
 [ 8.         11.84204017  1.          3.        ]
 [ 9.         18.13825375  3.          3.        ]
 [ 3.         12.60790988  1.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 528.5386224492984
Optimization restart 2/5, f = 609.0871239784065
Optimization restart 3/5, f = 609.0871239786638
Optimization restart 4/5, f = 609.0871239785375
Optimization restart 5/5, f = 609.0871239784748
[[ 3.         19.31930246  2.          2.07599732]
 [10.         17.6682925   1.          3.        ]
 [ 5.         13.32468548  3.          3.        ]
 [10.          9.29161443  1.          2.1489891 ]
 [ 4.         11.26639475  2.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 550.2843251528038
Optimization restart 2/5, f = 550.2437590444266
Optimization restart 3/5, f = 628.2215879811092
Optimization restart 4/5, f = 628.2215879814185
Optimization restart 5/5, f = 550.2438279573137
[[ 3.         15.90631557  1.          1.        ]
 [ 9.         20.          2.          1.91710903]
 [ 4.          9.00029773  3.          2.31309947]
 [ 3.         13.22422305  2.          1.90573006]
 [ 9.         14.0791024   1.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 573.341507513765
Optimization restart 2/5, f = 646.5758124408147
Optimization restart 3/5, f = 646.5758124385435
Optimization restart 4/5, f = 646.5758124380956
Optimization restart 5/5, f = 646.5758124495258
[[ 3.          9.79178516  1.          1.14412366]
 [ 4.          9.00509185  2.          1.01251958]
 [ 5.         11.81578853  1.          1.        ]
 [10.         14.12023477  1.          2.19261206]
 [ 9.          9.06525305  2.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 592.927718601837
Optimization restart 2/5, f = 664.143898469647
Optimization restart 3/5, f = 664.1438984689154
Optimization restart 4/5, f = 664.1438984688111
Optimization restart 5/5, f = 664.1438985324259
[[ 6.          8.          2.          1.79410612]
 [ 4.         18.67192439  3.          1.        ]
 [ 6.         13.23491892  2.          1.88120114]
 [ 9.         15.73722268  1.          2.50125644]
 [ 4.         18.76935436  1.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 618.865640685175
Optimization restart 2/5, f = 688.8361393656231
Optimization restart 3/5, f = 688.8361393577253
Optimization restart 4/5, f = 688.8361393585265
Optimization restart 5/5, f = 688.8361398131375
[[ 6.         12.11477606  1.          3.        ]
 [ 6.         16.59973939  3.          3.        ]
 [ 5.         15.18274274  2.          1.        ]
 [ 8.         12.69124966  2.          3.        ]
 [10.         18.87689848  3.          2.15383015]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 642.7192445525832
Optimization restart 2/5, f = 711.9534492135559
Optimization restart 3/5, f = 711.9534492122418
Optimization restart 4/5, f = 711.9534492131829
Optimization restart 5/5, f = 711.9534492122361
[[ 4.         20.          2.          3.        ]
 [ 6.          9.20439987  3.          1.        ]
 [ 9.         20.          1.          3.        ]
 [10.         10.41014742  2.          3.        ]
 [ 7.         17.72535276  1.          1.59647075]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 668.9409159428284
Optimization restart 2/5, f = 739.2965906975392
Optimization restart 3/5, f = 739.2965906860876
Optimization restart 4/5, f = 739.2965906856883
Optimization restart 5/5, f = 739.2965906892429
[[ 9.         10.98158048  3.          2.0632333 ]
 [ 5.         13.58135255  1.          3.        ]
 [ 7.         11.01495558  1.          1.6911509 ]
 [10.          8.73221987  2.          3.        ]
 [ 9.         20.          3.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 689.5071081501673
Optimization restart 2/5, f = 757.6626151844873
Optimization restart 3/5, f = 757.6626151744317
Optimization restart 4/5, f = 757.6626165440222
Optimization restart 5/5, f = 757.6626151949382
[[ 3.         11.19041458  2.          2.04582473]
 [ 9.         14.30602525  3.          1.        ]
 [ 9.          8.          1.          1.        ]
 [ 7.         18.68570846  2.          3.        ]
 [ 4.         13.39936899  2.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 708.2359949694214
Optimization restart 2/5, f = 776.8885781614698
Optimization restart 3/5, f = 776.841793322247
Optimization restart 4/5, f = 776.8417933222266
Optimization restart 5/5, f = 776.8417933222528
[[10.         19.13381799  2.          1.07244047]
 [ 3.         17.58263076  2.          1.        ]
 [ 3.         18.53779125  2.          3.        ]
 [ 5.          8.13474072  3.          2.81038272]
 [ 6.         14.82551346  2.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 732.4076781435808
Optimization restart 2/5, f = 796.9224694118142
Optimization restart 3/5, f = 796.9224694108713


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = 796.92246941384
Optimization restart 5/5, f = 796.9224694135742
[[ 9.         10.89015913  1.          1.96786161]
 [ 9.         13.54803979  3.          3.        ]
 [ 4.         20.          1.          1.96811929]
 [ 9.          8.          3.          1.        ]
 [ 9.         16.84201042  2.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 763.1719170290039
Optimization restart 2/5, f = 821.2290227111068
Optimization restart 3/5, f = 821.2290226309124
Optimization restart 4/5, f = 821.22902263081
Optimization restart 5/5, f = 821.2290226308709
[[ 6.         14.80033265  1.          2.02934594]
 [ 4.         10.25316725  2.          3.        ]
 [ 9.         12.97460001  2.          1.        ]
 [ 5.         20.          2.          1.        ]
 [ 9.         10.87750082  2.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 783.8553685287138
Optimization restart 2/5, f = 840.9811209977977
Optimization restart 3/5, f = 840.9811211043565
Optimization restart 4/5, f = 840.981121167777
Optimization restart 5/5, f = 840.9811209974522
[[ 9.         16.52689567  2.          3.        ]
 [10.         14.72812925  2.          1.50921628]
 [ 4.         11.96994591  3.          2.0110913 ]
 [ 8.         13.13414713  1.          1.92899271]
 [ 4.         13.91063675  2.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 810.3295547793409
Optimization restart 2/5, f = 861.3041439656349
Optimization restart 3/5, f = 861.3041439663867
Optimization restart 4/5, f = 861.3041439952956
Optimization restart 5/5, f = 861.3041439655171
[[ 4.         16.66326037  3.          3.        ]
 [ 7.         17.41730483  3.          2.34774312]
 [ 8.          8.          3.          2.11353846]
 [ 3.         12.69783185  1.          1.        ]
 [ 3.         15.65968857  3.          2.11426683]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 837.2484533895448
Optimization restart 2/5, f = 885.5569995525077
Optimization restart 3/5, f = 885.5569995535941
Optimization restart 4/5, f = 885.5569995523623
Optimization restart 5/5, f = 885.5569995675492
[[ 8.         14.69177258  2.          3.        ]
 [ 6.          9.77311287  2.          3.        ]
 [ 7.          8.83116355  2.          1.        ]
 [ 6.         16.20090602  1.          1.        ]
 [10.         13.65294186  3.          2.22139994]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 856.732294503591
Optimization restart 2/5, f = 905.4469074776958
Optimization restart 3/5, f = 905.4469074846853
Optimization restart 4/5, f = 905.4469074601257


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = 905.4469074604864
[[ 3.         15.63730809  2.          3.        ]
 [ 5.         18.98358727  2.          3.        ]
 [ 4.         11.35503699  1.          3.        ]
 [ 3.          8.          2.          1.96143724]
 [10.         11.90262829  1.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 887.1365756041495
Optimization restart 2/5, f = 924.8807541201179
Optimization restart 3/5, f = 924.880754127525
Optimization restart 4/5, f = 924.8807541199926
Optimization restart 5/5, f = 924.8807541200206
[[ 4.         16.85424836  1.          1.        ]
 [ 9.         18.02960273  1.          1.        ]
 [ 6.         12.24619503  3.          3.        ]
 [ 5.          8.          1.          1.        ]
 [ 4.         15.03482903  3.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 917.2887770889412
Optimization restart 2/5, f = 948.2118670887753
Optimization restart 3/5, f = 948.2118670889514
Optimization restart 4/5, f = 948.2118670965242
Optimization restart 5/5, f = 948.2118670898385
[[10.         12.96979408  1.          3.        ]
 [ 7.         15.4212951   3.          2.29065637]
 [ 8.         17.52763673  2.          2.06734894]
 [ 6.         11.05708159  3.          1.        ]
 [ 4.         15.1436789   1.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 937.6430472638463
Optimization restart 2/5, f = 968.4783010599213
Optimization restart 3/5, f = 968.4783010599289
Optimization restart 4/5, f = 968.478301060774
Optimization restart 5/5, f = 968.4783010599891
[[ 4.         17.11637203  3.          1.        ]
 [ 6.         14.08935345  3.          1.        ]
 [ 9.         11.73448925  2.          3.        ]
 [ 5.          9.00778989  1.          2.16938764]
 [ 8.          8.64472175  1.          1.94398929]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 960.0766374926168
Optimization restart 2/5, f = 988.569779651511
Optimization restart 3/5, f = 988.569779652809


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1000.5373176252655
Optimization restart 5/5, f = 988.5697796513927
[[ 7.         20.          1.          1.        ]
 [ 7.         16.7804732   2.          3.        ]
 [ 9.          8.          3.          3.        ]
 [ 3.         18.92741637  1.          2.19499283]
 [ 3.          8.84985764  2.          2.98390763]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 979.1271118120703
Optimization restart 2/5, f = 1007.6270365417212
Optimization restart 3/5, f = 1007.6270365416889
Optimization restart 4/5, f = 1007.6270365417911
Optimization restart 5/5, f = 1007.6270365493021
[[ 9.          8.84999367  3.          2.19163322]
 [ 5.         17.8067599   3.          2.14077763]
 [ 7.         11.78538264  2.          1.        ]
 [ 8.         18.98411934  1.          3.        ]
 [ 9.         17.49510947  3.          1.81983911]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1000.3631960533289
Optimization restart 2/5, f = 1027.6742082321985
Optimization restart 3/5, f = 1027.674208232292


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1108.3453332631257
Optimization restart 5/5, f = 1027.6742082953747
[[ 9.         12.54327741  3.          1.83596183]
 [ 4.         20.          3.          1.92510131]
 [10.         18.88930035  1.          2.04335399]
 [ 7.         10.53917065  3.          3.        ]
 [ 7.          8.          2.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1021.3746302836746
Optimization restart 2/5, f = 1049.623875134638
Optimization restart 3/5, f = 1049.6238751206956
Optimization restart 4/5, f = 1049.6238751208261
Optimization restart 5/5, f = 1049.6238751210867
[[ 6.         16.67622339  3.          1.        ]
 [ 6.         20.          1.          2.03009519]
 [ 3.         11.77532209  2.          3.        ]
 [ 7.          9.11030807  3.          2.09861085]
 [ 3.          8.93923694  1.          2.25344551]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1042.847500877594
Optimization restart 2/5, f = 1068.7569374630023


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = 1076.764070334421
Optimization restart 4/5, f = 1068.7569374635782
Optimization restart 5/5, f = 1068.75693746354
[[ 6.          9.6816135   1.          1.        ]
 [ 7.         13.83312183  2.          1.        ]
 [ 4.         14.41047297  1.          2.12181727]
 [ 4.          8.          3.          1.86744701]
 [ 4.          9.27086135  3.          1.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1061.9498561003136
Optimization restart 2/5, f = 1088.6573101948802
Optimization restart 3/5, f = 1088.657310197989
Optimization restart 4/5, f = 1088.6573101918057
Optimization restart 5/5, f = 1088.6573159228255
[[ 9.         17.05353359  1.          1.91201651]
 [10.         10.50268733  2.          1.74179157]
 [ 5.         18.19201363  1.          2.02165067]
 [ 9.         19.42010661  2.          3.        ]
 [ 7.         11.53023639  2.          3.        ]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1085.0060696704422
Optimization restart 2/5, f = 1108.0195078573688
Optimization restart 3/5, f = 1108.0195078555885
Optimization restart 4/5, f = 1108.0195078512718
Optimization restart 5/5, f = 1108.0195078512052
[[ 8.         20.          1.          2.0968396 ]
 [ 9.         18.70020869  3.          1.        ]
 [ 4.         17.32103883  2.          3.        ]
 [ 5.         20.          3.          1.        ]
 [10.          8.          2.          1.90728634]]

User function time loss called with 5 inputs to simulate

Evaluating input: 1 of 5

 Retrying in 1 seconds

Evaluating input: 2 of 5

 Retrying in 1 seconds

Evaluating input: 3 of 5

 Retrying in 1 seconds

Evaluating input: 4 of 5

 Retrying in 1 seconds

Evaluating input: 5 of 5

 Retrying in 1 seconds


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1105.7424864437678
Optimization restart 2/5, f = 1131.1336206738315
Optimization restart 3/5, f = 1131.1336206756853
Optimization restart 4/5, f = 1131.1336206733947
Optimization restart 5/5, f = 1131.1336206738379


### Experimental Design - Integrated Variance Reduction

#### Model / Emulator (GP)

In [19]:
emulator_ird = GPy.models.GPRegression(init_X, init_Y, noise_var=1e-10)
emukit_model_ird = GPyModelWrapper(emulator_ird, n_restarts=5)
emukit_model_ird.optimize()

Optimization restart 1/5, f = 105.51770371225868
Optimization restart 2/5, f = 94.28493209147018
Optimization restart 3/5, f = 94.28494224818732
Optimization restart 4/5, f = 94.28493209141652
Optimization restart 5/5, f = 94.2849324900023


#### Acquisition Function

In [20]:
integrated_variance_reduction = IntegratedVarianceReduction(model=emukit_model_ird, space=parameter_space)

#### Optimizer

In [21]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [22]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ird,
    space = parameter_space,
    acquisition = integrated_variance_reduction,
    acquisition_optimizer = optimizer,
    update_interval = 1,
    batch_size = 10
)

In [23]:
ed_loop.run_loop(user_function_co2, 10)

Optimization restart 1/5, f = 94.28493209141652
Optimization restart 2/5, f = 94.28493215235721
Optimization restart 3/5, f = 98.1627073518468
Optimization restart 4/5, f = 98.16124984627456
Optimization restart 5/5, f = 97.53944354199507


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[10.         19.649408    1.          2.82442587]
 [10.          8.          1.          1.        ]
 [ 3.          8.          1.          1.        ]
 [ 3.         20.          1.          3.        ]
 [10.         15.18994624  1.          1.        ]
 [10.         20.          3.          1.        ]
 [ 3.          8.          1.          3.        ]
 [10.         14.51663953  1.          3.        ]
 [10.          8.          3.          3.        ]
 [ 3.         20.          3.          1.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retrying in 1 seconds

Evaluating input: 5 of 10

 Retrying in 1 seconds

Evaluating input: 6 of 10

 Retrying in 1 seconds

Evaluating input: 7 of 10

 Retrying in 1 seconds

Evaluating input: 8 of 10

 Retrying in 1 seconds

Evaluating input: 9 o

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 143.559847390387
Optimization restart 2/5, f = 143.5598473900277
Optimization restart 3/5, f = 143.55984739116525
Optimization restart 4/5, f = 156.53992937810838
Optimization restart 5/5, f = 143.55984739636386


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[ 3.         13.75376085  1.          1.        ]
 [ 3.          8.          3.          1.062149  ]
 [ 3.         16.89355994  3.          3.        ]
 [10.         13.31242299  3.          1.        ]
 [10.         18.08528736  3.          3.        ]
 [ 3.         13.67904885  1.          3.        ]
 [ 7.         20.          1.          3.        ]
 [ 7.         10.38717376  1.          1.        ]
 [10.         10.75739701  1.          3.        ]
 [ 3.         12.52164138  3.          1.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retrying in 1 seconds

Evaluating input: 5 of 10

 Retrying in 1 seconds

Evaluating input: 6 of 10

 Retrying in 1 seconds

Evaluating input: 7 of 10

 Retrying in 1 seconds

Evaluating input: 8 of 10

 Retrying in 1 seconds

Evaluating input: 9 o

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 182.79430870276076
Optimization restart 2/5, f = 182.78225699081497
Optimization restart 3/5, f = 182.78225700354983
Optimization restart 4/5, f = 182.7822569906148
Optimization restart 5/5, f = 182.7822569906308
[[10.         19.1272604   1.          1.        ]
 [ 3.         18.70985862  1.          1.        ]
 [ 7.          8.          1.          3.        ]
 [ 7.          8.          3.          1.        ]
 [ 7.         16.09052353  1.          3.        ]
 [ 3.          8.          3.          3.        ]
 [ 6.         20.          3.          3.        ]
 [10.         11.95074563  1.          1.        ]
 [10.         16.56041976  3.          3.        ]
 [ 3.         12.43241758  1.          3.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retry

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 224.2127795264439
Optimization restart 2/5, f = 224.15010075830335
Optimization restart 3/5, f = 224.1501007583271
Optimization restart 4/5, f = 224.15010075888466
Optimization restart 5/5, f = 224.15010076104323
[[10.         10.06821884  3.          1.        ]
 [ 3.         17.63020669  3.          3.        ]
 [ 6.         11.24637695  1.          1.17493951]
 [10.         16.33176494  3.          1.        ]
 [ 7.         16.2651607   1.          3.        ]
 [ 3.         14.88532334  3.          1.        ]
 [10.          8.          1.          3.        ]
 [ 7.         20.          1.          1.        ]
 [ 6.         11.06278806  3.          3.        ]
 [ 3.         17.43678964  1.          3.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retry

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 262.4384620926675
Optimization restart 2/5, f = 262.43830572317825
Optimization restart 3/5, f = 262.43830571847064
Optimization restart 4/5, f = 262.43830593913134
Optimization restart 5/5, f = 262.4383057185531
[[ 3.         11.35321504  1.          1.        ]
 [10.         15.668591    1.          1.68729851]
 [ 7.         16.73924812  3.          1.        ]
 [ 6.          8.          1.          1.        ]
 [ 3.         11.06670658  3.          3.        ]
 [ 3.         20.          1.          1.        ]
 [10.          8.          3.          1.        ]
 [ 7.         13.25250245  1.          1.        ]
 [10.         20.          3.          3.        ]
 [10.         11.96459996  3.          3.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retry

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 297.42552373803244
Optimization restart 2/5, f = 297.41638163540307
Optimization restart 3/5, f = 297.4163816353827
Optimization restart 4/5, f = 297.41638163549464
Optimization restart 5/5, f = 297.4163817337617
[[ 7.         16.04191418  1.          3.        ]
 [10.         11.45458236  1.          2.24607948]
 [ 3.         20.          3.          3.        ]
 [ 6.         11.13516529  3.          1.        ]
 [ 7.          8.          3.          3.        ]
 [10.         20.          1.          3.        ]
 [ 3.         16.15261348  1.          1.        ]
 [ 7.         20.          3.          1.        ]
 [ 3.         10.86990839  1.          3.        ]
 [ 7.         16.57691314  3.          3.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retry

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 332.89285212792356
Optimization restart 2/5, f = 332.8605877264117
Optimization restart 3/5, f = 332.8605878673987
Optimization restart 4/5, f = 332.8605877221114
Optimization restart 5/5, f = 332.8605877311028
[[10.         17.12453449  1.          1.        ]
 [ 6.         11.27953668  1.          2.31015585]
 [ 3.         10.27674768  3.          1.        ]
 [ 3.         17.13590538  3.          1.        ]
 [10.         15.66770799  3.          1.        ]
 [ 6.         17.35020249  1.          2.2547205 ]
 [ 6.          8.          1.          2.06098534]
 [10.         14.96429508  1.          3.        ]
 [10.         10.44449349  1.          1.        ]
 [ 6.         12.30627388  3.          3.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retryin

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 375.1106480601665
Optimization restart 2/5, f = 375.1103777092269
Optimization restart 3/5, f = 375.11037770821497
Optimization restart 4/5, f = 375.1103777081905
Optimization restart 5/5, f = 375.110377708246
[[10.         10.99107439  3.          3.        ]
 [ 3.         16.57174804  1.          3.        ]
 [ 7.         12.40870011  3.          1.        ]
 [ 7.         20.          1.          1.        ]
 [ 3.          8.          3.          3.        ]
 [ 3.         10.72051726  1.          1.        ]
 [ 7.         17.832488    3.          3.        ]
 [ 7.         11.92585295  1.          2.20080704]
 [ 3.         13.89946027  3.          3.        ]
 [ 6.          8.          3.          1.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retrying

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 409.1744191436138
Optimization restart 2/5, f = 409.170929500101
Optimization restart 3/5, f = 409.1709295375549
Optimization restart 4/5, f = 409.1709294997474


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = 409.1709294997376
[[ 7.         15.09233615  1.          1.        ]
 [ 5.         20.          1.          3.        ]
 [10.         16.96290972  3.          1.98567879]
 [ 5.         11.07096892  2.          2.21986925]
 [ 3.         17.49689585  3.          1.        ]
 [ 8.         11.23359782  2.          1.97327673]
 [10.          8.          3.          2.34436709]
 [10.         20.          1.          1.        ]
 [ 3.          8.          1.          3.        ]
 [10.          8.          1.          1.        ]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retrying in 1 seconds

Evaluating input: 5 of 10

 Retrying in 1 seconds

Evaluating input: 6 of 10

 Retrying in 1 seconds

Evaluating input: 7 of 10

 Retrying in 1 seconds

Evaluating input: 8 of 1

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 443.96629441491234
Optimization restart 2/5, f = 443.9646136124979
Optimization restart 3/5, f = 443.9646136128255


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 563.883577606943
Optimization restart 5/5, f = 443.96461361248
[[ 8.         17.3390901   2.          2.07169948]
 [ 4.         15.27772899  1.          1.86095564]
 [ 8.         13.79482997  3.          1.        ]
 [ 8.         11.82501342  1.          3.        ]
 [ 3.         10.76249101  3.          1.73714911]
 [ 6.         20.          3.          1.91452215]
 [10.         16.84717963  1.          2.49942394]
 [10.         11.39329005  2.          1.82824423]
 [ 5.         15.05058632  3.          3.        ]
 [ 5.         10.42278225  2.          2.09441223]]

User function time loss called with 10 inputs to simulate

Evaluating input: 1 of 10

 Retrying in 1 seconds

Evaluating input: 2 of 10

 Retrying in 1 seconds

Evaluating input: 3 of 10

 Retrying in 1 seconds

Evaluating input: 4 of 10

 Retrying in 1 seconds

Evaluating input: 5 of 10

 Retrying in 1 seconds

Evaluating input: 6 of 10

 Retrying in 1 seconds

Evaluating input: 7 of 10

 Re

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 486.87883042983054
Optimization restart 2/5, f = 486.8517483024623
Optimization restart 3/5, f = 486.8517483088396
Optimization restart 4/5, f = 486.8517483025067
Optimization restart 5/5, f = 604.8805271200446


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


### Random GP

Supervised learning

In [15]:
emulator_rnd = GPy.models.GPRegression(train_X, train_Y)
emukit_model_rnd = GPyModelWrapper(emulator_rnd, n_restarts=5)
emukit_model_rnd.optimize()
emulator_rnd

Optimization restart 1/5, f = 1054.7799404405848
Optimization restart 2/5, f = 1054.7799391494045
Optimization restart 3/5, f = 1054.779939149284
Optimization restart 4/5, f = 1054.7799393865603
Optimization restart 5/5, f = 1054.7799391493022


### Evaluate

Evaluate RMSE of each model on our test set of 50 randomly selected points.

In [16]:
pred_Y, pred_Y_variance = emukit_model_ed.predict(test_X)
mse_ed = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Model Variance RMSE: ', mse_ed)

Experimental Design w/ Model Variance RMSE:  8.970729554163452


In [24]:
pred_Y, pred_Y_variance = emukit_model_ird.predict(test_X)
mse_ird = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Integrated Variance Reduction RMSE: ', mse_ird)

Experimental Design w/ Integrated Variance Reduction RMSE:  13.264605946984197


In [17]:
pred_Y, pred_Y_variance = emukit_model_rnd.predict(test_X)
mse_rnd = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Random GP RMSE: ', mse_rnd)

Random GP RMSE:  13.405015625476608


In [18]:
p = 1 - (mse_ed/mse_rnd)
f'Experimental Design w/ Model Variance is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Model Variance is 33.079% better than training on random points.'

In [25]:
p = 1 - (mse_ird/mse_rnd)
f'Experimental Design w/ Integrated Variance Reduction is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Integrated Variance Reduction is 1.047% better than training on random points.'

### Save Models

In [28]:
with open(f'experimental_design/models/model_variance_20_init_points_250_loops_co2.pkl', "wb") as f:
     pickle.dump(emukit_model_ed, f)

with open(f'experimental_design/models/integrated_variance_reduction_20_init_points_10_loops_co2.pkl', "wb") as f:
     pickle.dump(emukit_model_ird, f)
        
with open(f'experimental_design/models/250_random_points_supervised_GP_co2.pkl', "wb") as f:
     pickle.dump(emukit_model_rnd, f)