In [1]:
%cd ../

/Users/harrysonghurst/Documents/Coursework/L48 Machine Learning and the Physical World/TrafficEmu


In [2]:
# If you get a SciPy error when installing Emukit, build it from source:

# git clone https://github.com/amzn/Emukit.git
# cd Emukit
# pip install -r requirements/requirements.txt
# python setup.py develop

In [3]:
import numpy as np
import pickle
import emukit as ek
import GPy

from emukit.model_wrappers import GPyModelWrapper
from emukit.experimental_design.experimental_design_loop import ExperimentalDesignLoop
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.core.initial_designs import RandomDesign, latin_design
from emukit.experimental_design.acquisitions import ModelVariance, IntegratedVarianceReduction
from emukit.core.loop import UserFunctionWrapper
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.bayesian_optimization.loops import BayesianOptimizationLoop
from emukit.core.optimization import GradientAcquisitionOptimizer

from sumo_grid_simulation.grid_simulation import Simulator
import experimental_design.config as config

### Pseudocode

Fitting a gaussian process to a simulator using Emukit takes the following form (taken from L48 lectures):

```
initialize GP with some randomly chosen points
while stopping condition is not met:
    compute candidate point(s) using GP and acquisition funciton (model_variance) -> new point
    evaluate this new point with our simulator/user function -> observation
    update model with new observation -> new GP
```

### Simulator

In [5]:
simulator = Simulator(end_time=300)

### User Function
 
This is the function we want to understand. Namedly, how are CO2 emissions and timeLoss (the time lost due to driving below the ideal speed) affected by the following parameters: 

```
gridSize: the size of the grid network where the simulation is carried out
edgeMaxSpeed: legal speed limit in m/s - this can be exceeded (11.11 == 40km/h)
maxSpeed: the absolute maximum velocity of any vehicle in m/s (55.55 == 200 km/h)
edgeLength: length of the roads between intersections in meters
numLanes: number of lanes per road
accel: The acceleration ability of vehicles in m/s^2.
```

*A complete list of parmeters analysed is discussed in our report.*

In [6]:
def user_function_time_loss(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function time loss called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, maxSpeed, edgeLength, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.005
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * edgeLength / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            maxSpeed      = maxSpeed,
            edgeLength    = edgeLength,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average time loss / average route duration
        result.append(s['timeLoss']/s['duration'])
        i += 1
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

### Model Inputs / parameter space

In [7]:
parameter_space = config.get_parameter_space()

### Get init, test, and train points

Train points are used to optimize a GP without experimental design - to verify experimental design works.

In [8]:
design = RandomDesign(parameter_space)
init_X = design.get_samples(20)
init_Y = user_function_time_loss(init_X)

design = RandomDesign(parameter_space)
test_X = design.get_samples(50)
test_Y = user_function_time_loss(test_X)

design = RandomDesign(parameter_space)
train_X = design.get_samples(270)
train_Y = user_function_time_loss(train_X)

[[18.         22.78911208  6.63935858 54.19967041  2.          2.55857348]
 [ 7.         15.27093135 12.32432809 39.05614891  1.          3.31556836]
 [12.          9.06669986 25.68186945 52.4123406   2.          4.56258435]
 [17.         17.9305433  24.89615228 61.57427586  2.          3.80957295]
 [14.         19.0021036  22.44166005 38.76229273  1.          3.13751616]
 [13.         18.69157052 25.76700268 68.51499285  3.          2.93306007]
 [ 9.         21.06271216  5.87407525 59.44067738  2.          4.98559951]
 [10.         23.78793233 17.59953708 42.91597458  3.          2.05725981]
 [19.         12.41298343 22.22918169 32.10938704  3.          1.76951929]
 [ 3.          9.50892476  5.66519584 49.80634504  2.          4.27472206]
 [15.         12.75362243 25.67356262 53.35041656  2.          3.30788967]
 [13.         13.02747163 22.24663498 53.77147656  2.          3.10806111]
 [12.         14.99884902 16.73085885 55.96170769  3.          2.165224  ]
 [10.         17.36780815


Evaluating input: 36 of 50

 Retrying in 1 seconds

Evaluating input: 37 of 50

 Retrying in 1 seconds

Evaluating input: 38 of 50

 Retrying in 1 seconds

Evaluating input: 39 of 50

 Retrying in 1 seconds

Evaluating input: 40 of 50

 Retrying in 1 seconds

Evaluating input: 41 of 50

 Retrying in 1 seconds

Evaluating input: 42 of 50

 Retrying in 1 seconds

Evaluating input: 43 of 50

 Retrying in 1 seconds

Evaluating input: 44 of 50

 Retrying in 1 seconds

Evaluating input: 45 of 50

 Retrying in 1 seconds

Evaluating input: 46 of 50

 Retrying in 1 seconds

Evaluating input: 47 of 50

 Retrying in 1 seconds

Evaluating input: 48 of 50

 Retrying in 1 seconds

Evaluating input: 49 of 50

 Retrying in 1 seconds

Evaluating input: 50 of 50

 Retrying in 1 seconds
[[15.          9.58883366 22.81123894 37.97311593  3.          4.47357999]
 [16.         14.60743304 10.06974995 32.07998251  3.          1.74326609]
 [11.         20.67346781 11.54124217 45.47143814  2.          2.43013


Evaluating input: 131 of 270

 Retrying in 1 seconds

Evaluating input: 132 of 270

 Retrying in 1 seconds

Evaluating input: 133 of 270

 Retrying in 1 seconds

Evaluating input: 134 of 270

 Retrying in 1 seconds

Evaluating input: 135 of 270

 Retrying in 1 seconds

Evaluating input: 136 of 270

 Retrying in 1 seconds

Evaluating input: 137 of 270

 Retrying in 1 seconds

Evaluating input: 138 of 270

 Retrying in 1 seconds

Evaluating input: 139 of 270

 Retrying in 1 seconds

Evaluating input: 140 of 270

 Retrying in 1 seconds

Evaluating input: 141 of 270

 Retrying in 1 seconds

Evaluating input: 142 of 270

 Retrying in 1 seconds

Evaluating input: 143 of 270

 Retrying in 1 seconds

Evaluating input: 144 of 270

 Retrying in 1 seconds

Evaluating input: 145 of 270

 Retrying in 1 seconds

Evaluating input: 146 of 270

 Retrying in 1 seconds

Evaluating input: 147 of 270

 Retrying in 1 seconds

Evaluating input: 148 of 270

 Retrying in 1 seconds

Evaluating input: 149 of 27

### Experimental Design - Model Variance

#### Model / Emulator (GP)

Our surrogate model is our emulator. In this case, a gaussian process.

In [9]:
emulator_ed = GPy.models.GPRegression(init_X, init_Y)
emukit_model_ed = GPyModelWrapper(emulator_ed, n_restarts=5)
emukit_model_ed.optimize()
emulator_ed

Optimization restart 1/5, f = -22.106309144390245
Optimization restart 2/5, f = 3.7397078516329305
Optimization restart 3/5, f = 3.7397078516357496
Optimization restart 4/5, f = 3.739707851579622
Optimization restart 5/5, f = -22.10630914438997


#### Acquisition Function

In [10]:
model_variance = ModelVariance(model=emukit_model_ed)

#### Optimizer

In [11]:
optimizer = GradientAcquisitionOptimizer(parameter_space)


#### Experimental Design Loop

In [12]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ed,
    space = parameter_space,
    acquisition = model_variance,
    acquisition_optimizer = optimizer,
    batch_size = 1
)

In [13]:
ed_loop.run_loop(user_function_time_loss, 250)

Optimization restart 1/5, f = -22.106309144390245
Optimization restart 2/5, f = 3.7397078516329305
Optimization restart 3/5, f = -22.106309144353034
Optimization restart 4/5, f = 3.7397078516440487
Optimization restart 5/5, f = -22.106309138518387
[[ 3.   8.   5.  70.   3.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -22.302192391265784
Optimization restart 2/5, f = -22.302192390417634
Optimization restart 3/5, f = 3.4659891994882948
Optimization restart 4/5, f = -22.302192379415366
Optimization restart 5/5, f = 3.4659891995137944
[[ 3.   8.  27.  30.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -22.947883366553388
Optimization restart 2/5, f = -22.947883366541895
Optimization restart 3/5, f = 3.4235159386747007
Optimization restart 4/5, f = 3.42351593867917
Optimization restart 5/5

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -27.11035471014295
Optimization restart 2/5, f = 3.860171986434299
Optimization restart 3/5, f = 3.8601767951413457
Optimization restart 4/5, f = 3.8601651204937415
Optimization restart 5/5, f = 3.860173280894811
[[20.  25.  27.  30.   3.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -27.245470094283263
Optimization restart 2/5, f = -27.245470094655886
Optimization restart 3/5, f = -27.24547009465366
Optimization restart 4/5, f = 5.8739720481757605
Optimization restart 5/5, f = 5.873972046029381
[[ 3.   8.   5.  30.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -28.34033012416145
Optimization restart 2/5, f = 5.642860602464001
Optimization restart 3/5, f = -28.340330124284947
Optimization restart 4/5, f = -28.340330124285018
Optimiz

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -31.118134137740267
Optimization restart 2/5, f = -31.118134137756947
Optimization restart 3/5, f = -31.11813413775006
Optimization restart 4/5, f = 7.283810572621132
Optimization restart 5/5, f = -31.11813413775873
[[20.          8.          5.         47.89180892  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -32.075372055826605
Optimization restart 2/5, f = 7.344936893735273
Optimization restart 3/5, f = -32.07537205430241
Optimization restart 4/5, f = 7.3449367198931625
Optimization restart 5/5, f = 7.344936893731418
[[ 3.         25.         17.92841205 70.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -33.88697055119516
Optimization restart 2/5, f = -33.88697055121459
Optimization restart 

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -45.480534922813625
Optimization restart 2/5, f = 12.877704260426924
Optimization restart 3/5, f = 12.87770426042674
Optimization restart 4/5, f = 12.877703314876925
Optimization restart 5/5, f = 12.877704260426203
[[20.          8.         18.15460223 70.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -47.187636200772616
Optimization restart 2/5, f = 12.807671277070042
Optimization restart 3/5, f = 12.807671277070138
Optimization restart 4/5, f = 12.807671277070021
Optimization restart 5/5, f = 12.807671277045237
[[ 3.         25.          5.         54.56298083  1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -48.887841542036924
Optimization restart 2/5, f = 12.616952989698056
Optimization restar

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -56.024884424892235
Optimization restart 2/5, f = -56.024884421767624
Optimization restart 3/5, f = 13.96165226291911
Optimization restart 4/5, f = -56.024884424886736
Optimization restart 5/5, f = -56.024884420916656
[[20.          8.          5.         57.73357697  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -57.01943136620054
Optimization restart 2/5, f = 13.752626395627324
Optimization restart 3/5, f = 13.75262639562677
Optimization restart 4/5, f = 13.752626395626777
Optimization restart 5/5, f = 13.752626395626773
[[14.   8.   5.  70.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -58.7496883663285
Optimization restart 2/5, f = -58.74968836635716
Optimization restart 3/5, f = 13.531456504720065
Optimization 

 Retrying in 1 seconds
Optimization restart 1/5, f = -85.03451226113134
Optimization restart 2/5, f = 19.756014738506458
Optimization restart 3/5, f = -85.03451226117429
Optimization restart 4/5, f = 19.75601473850643
Optimization restart 5/5, f = 19.756014738506458
[[20.  8. 27. 70.  1.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -86.62191013349815
Optimization restart 2/5, f = -86.62191013340063
Optimization restart 3/5, f = -86.62191013140685
Optimization restart 4/5, f = 19.681276361583897
Optimization restart 5/5, f = 19.68127636089431
[[20.          8.         17.93727593 51.56363469  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -88.64465570067249
Optimization restart 2/5, f = 19.515821560587447
Optimization restart 3/5, f = -88.64465570097246
Optimization restart 4

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[ 3.         15.89155359  5.         36.9974982   3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -91.58217836572649
Optimization restart 2/5, f = -91.58217836774139
Optimization restart 3/5, f = -91.58217836774159
Optimization restart 4/5, f = -91.582178367714
Optimization restart 5/5, f = 19.486220047645986
[[ 3.          8.         18.98561395 34.55122273  1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -93.52729237455422
Optimization restart 2/5, f = -93.52729237670913
Optimization restart 3/5, f = -93.52729237672398
Optimization restart 4/5, f = -93.52729237152236
Optimization restart 5/5, f = -93.52729237672062
[[20.         14.89453635  5.         70.          3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluatin

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -100.18436263808823
Optimization restart 2/5, f = 21.225252753554685
Optimization restart 3/5, f = -100.18436266576764
Optimization restart 4/5, f = -100.18436266576923
Optimization restart 5/5, f = -100.18436266576025
[[11.          8.         20.92293962 30.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -102.15084787535916
Optimization restart 2/5, f = -102.15084787541127
Optimization restart 3/5, f = 21.225612535971074
Optimization restart 4/5, f = 21.225631847700477
Optimization restart 5/5, f = -102.15084787541318
[[ 3.         25.          9.30895725 30.          3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -101.9366984022893
Optimization restart 2/5, f = -101.9366984042297
Optimization r

[[20.   8.  27.  70.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -127.5830964867719
Optimization restart 2/5, f = -127.5830964869453
Optimization restart 3/5, f = 24.08611539046739
Optimization restart 4/5, f = -127.58309648701325
Optimization restart 5/5, f = -127.58309648702509
[[20.         25.         27.         49.23550392  3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -129.47887155095054
Optimization restart 2/5, f = -129.47899201571045
Optimization restart 3/5, f = -129.4789920133411
Optimization restart 4/5, f = -129.4789920157734
Optimization restart 5/5, f = 25.07247172946402
[[ 3.          8.         27.         42.66762109  3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 second

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -131.4202537777286
[[15.          8.         11.01846942 70.          1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -133.5231349197988
Optimization restart 2/5, f = -133.52313492162767
Optimization restart 3/5, f = -133.5231349217483
Optimization restart 4/5, f = -133.52313492133695


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -133.52313492123656
[[20.         15.64955255 16.28231566 70.          3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -132.6544158197275
Optimization restart 2/5, f = -132.65441581643825
Optimization restart 3/5, f = 25.10190206249112
Optimization restart 4/5, f = -132.65441581972152
Optimization restart 5/5, f = -132.65441580510702
[[ 3.         15.85172304 18.23219491 70.          1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -130.51340172570642
Optimization restart 2/5, f = -130.51340172625112
Optimization restart 3/5, f = -130.51340172599024
Optimization restart 4/5, f = -130.51340172619564
Optimization restart 5/5, f = -130.51340172607394
[[ 3.          8.          5.         54.14224781  3.          1.5       ]]

User fun

 Retrying in 1 seconds
Optimization restart 1/5, f = -160.59495771614257
Optimization restart 2/5, f = -132.6540118807598
Optimization restart 3/5, f = -160.59495771614237
Optimization restart 4/5, f = -132.65401188100714
Optimization restart 5/5, f = -132.65401188082876
[[20.  25.   5.  30.   3.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -161.9156801207622
Optimization restart 2/5, f = -132.32506058460228
Optimization restart 3/5, f = -132.3250605842632
Optimization restart 4/5, f = -132.32495872012268
Optimization restart 5/5, f = -132.32506058428325
[[20.  8. 27. 30.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -163.89613434851162
Optimization restart 2/5, f = -140.26988794527438
Optimization restart 3/5, f = -140.26988794466357
Optimization restart 4/5, f = -140.269887945267
Opti

[[20.         22.04363868 27.         30.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -194.0454570871612
Optimization restart 2/5, f = -158.71403613918488
Optimization restart 3/5, f = -158.71403590716346
Optimization restart 4/5, f = -158.71403614065662
Optimization restart 5/5, f = -158.71403614091736
[[12.          8.          5.         41.70635993  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -195.8123579465518
Optimization restart 2/5, f = -195.812357946592
Optimization restart 3/5, f = -159.99651399610866
Optimization restart 4/5, f = -159.99651289171362
Optimization restart 5/5, f = -159.99651386415837
[[ 3.         14.36500793  5.         61.99204872  3.          5.        ]]

User function time loss called with 1 inputs to simulate

E

 Retrying in 1 seconds
Optimization restart 1/5, f = -229.12462459390275
Optimization restart 2/5, f = -201.93075395507617
Optimization restart 3/5, f = -201.93075369518382
Optimization restart 4/5, f = -201.93075395570466
Optimization restart 5/5, f = -201.9307539512737
[[10.         21.94306218  5.         30.          3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -230.00324537985938
Optimization restart 2/5, f = -203.50175105431367
Optimization restart 3/5, f = -203.5017510241825
Optimization restart 4/5, f = -203.50175105380882
Optimization restart 5/5, f = -203.50175105306684
[[15.        15.1386178  5.        30.         1.         5.       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -232.23730359644725
Optimization restart 2/5, f = -205.94065333189928
Optimization rest

Optimization restart 3/5, f = -264.58471802984286
Optimization restart 4/5, f = -238.4587110295406
Optimization restart 5/5, f = -238.45871059232056
[[20.         25.         17.77901904 30.          3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -265.6319289644282
Optimization restart 2/5, f = -239.49928718732787
Optimization restart 3/5, f = -239.49928547626956
Optimization restart 4/5, f = -239.49919466955453
Optimization restart 5/5, f = -239.49928742972665
[[ 3.         17.36803197 27.         30.          1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -267.2381190463238
Optimization restart 2/5, f = -241.15968529089747
Optimization restart 3/5, f = -241.15969120939377
Optimization restart 4/5, f = -267.23811904825664
Optimization restart 5/5, f = -241.

Optimization restart 5/5, f = -275.46017536204744
[[ 3.  8.  5. 30.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -298.9512893600262
Optimization restart 2/5, f = -274.41952092657795
Optimization restart 3/5, f = -274.4195203956084
Optimization restart 4/5, f = -274.419519987752
Optimization restart 5/5, f = -274.41951899696625
[[14.         13.44350625  5.         70.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -301.2525960340348
Optimization restart 2/5, f = -277.0629869386065
Optimization restart 3/5, f = -277.06311365455355
Optimization restart 4/5, f = -277.06311367771843
Optimization restart 5/5, f = -277.0631136778795
[[12.        25.        27.        40.4609318  1.         1.5      ]]

User function time loss called with 1 inputs to simulate

Evaluati

 Retrying in 1 seconds
Optimization restart 1/5, f = -326.5466402944253
Optimization restart 2/5, f = -271.7528360577147
Optimization restart 3/5, f = -271.75306988641114
Optimization restart 4/5, f = -326.5467326782584
Optimization restart 5/5, f = -271.7530751337745
[[ 3.         25.          5.         40.25914954  1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -328.8353596145979
Optimization restart 2/5, f = -273.7009749603001
Optimization restart 3/5, f = -273.7009776192416
Optimization restart 4/5, f = -273.7009781828091
Optimization restart 5/5, f = -273.70097818298336
[[20.         18.55319532 15.06375037 70.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -330.5848256164804
Optimization restart 2/5, f = -275.97381819265337
Optimization resta

Optimization restart 2/5, f = -314.84389232976207
Optimization restart 3/5, f = -361.9143846342491
Optimization restart 4/5, f = -361.914384721991
Optimization restart 5/5, f = -314.84309883162837
[[20.         25.         27.         54.18098789  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -364.3006061887793
Optimization restart 2/5, f = -364.3006061944408
Optimization restart 3/5, f = -364.300606195183
Optimization restart 4/5, f = -317.47944388593595
Optimization restart 5/5, f = -317.47944388786095
[[ 3.         25.         19.64475009 37.0200167   3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -366.690522003715
Optimization restart 2/5, f = -319.2729798757874
Optimization restart 3/5, f = -319.27297808221573
Optimization restart 4/5, f = -319.2729798

Optimization restart 3/5, f = -401.3487008777911
Optimization restart 4/5, f = -401.3487008707281
Optimization restart 5/5, f = -340.94613576434966
[[12.         25.         12.20508415 58.04035445  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -403.05140202089547
Optimization restart 2/5, f = -343.1173322439935
Optimization restart 3/5, f = -343.11733271139076
Optimization restart 4/5, f = -343.1173297060557
Optimization restart 5/5, f = -343.11733271131834
[[11.         18.48822497 27.         48.64616672  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -405.50704865479173
Optimization restart 2/5, f = -405.5071357162651
Optimization restart 3/5, f = -345.0637110657958
Optimization restart 4/5, f = -405.5071357092812
Optimization restart 5/5, f = -345.0637

### Experimental Design - Integrated Variance Reduction

#### Model / Emulator (GP)

In [14]:
emulator_ird = GPy.models.GPRegression(init_X, init_Y)
emukit_model_ird = GPyModelWrapper(emulator_ird, n_restarts=5)
emukit_model_ird.optimize()

Optimization restart 1/5, f = -22.106309144390245
Optimization restart 2/5, f = -22.106309144380933
Optimization restart 3/5, f = -22.10630914436508
Optimization restart 4/5, f = 3.7397078512365187
Optimization restart 5/5, f = -22.106309144381058


#### Acquisition Function

In [15]:
integrated_variance_reduction = IntegratedVarianceReduction(
    model=emukit_model_ird, 
    space=parameter_space, 
    num_monte_carlo_points=100
)

#### Optimizer

In [16]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [17]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ird,
    space = parameter_space,
    acquisition = integrated_variance_reduction,
    acquisition_optimizer = optimizer,
    batch_size = 1
)

In [18]:
ed_loop.run_loop(user_function_time_loss, 250)

Optimization restart 1/5, f = -22.106309144390245
Optimization restart 2/5, f = 3.739707851632925
Optimization restart 3/5, f = 3.7397078516436757
Optimization restart 4/5, f = -19.395770869430272
Optimization restart 5/5, f = -22.106309144392547


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[ 4.         21.07399884 20.897432   57.87949848  1.          1.63553464]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -22.01546717120799
Optimization restart 2/5, f = 5.236329265753941
Optimization restart 3/5, f = 5.236329399312638
Optimization restart 4/5, f = 5.236329399313188
Optimization restart 5/5, f = -22.015467171232217
[[ 3.         13.69671901 11.01143721 68.41074992  3.          2.25529686]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -21.641311190043083
Optimization restart 2/5, f = -21.641311191301323
Optimization restart 3/5, f = -21.641311191376886
Optimization restart 4/5, f = 5.153813803075472
Optimization restart 5/5, f = 5.153813652915208
[[16.         23.65507373 10.99173907 31.34139184  2.          1.60375812]]

User function time loss called with 1 inputs to simulate

Evaluati

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[ 3.          8.83551429 20.09681223 37.2946094   2.          2.48730874]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -27.258413440841327
Optimization restart 2/5, f = 6.357247938092025
Optimization restart 3/5, f = -27.25841344079972
Optimization restart 4/5, f = 6.357240865755422
Optimization restart 5/5, f = 6.357246969411651
[[ 3.         21.10354188  5.03097812 37.55040538  2.          1.5580608 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -28.627695961480043
Optimization restart 2/5, f = -28.627695961452055
Optimization restart 3/5, f = -28.627695961504884
Optimization restart 4/5, f = -28.627695961506962
Optimization restart 5/5, f = 6.1819484036492796
[[18.         23.02431549 24.97317915 56.04432437  2.          3.88107179]]

User function time loss called with 1 inputs to simulate

Evalu

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[ 5.         22.18723215 26.04347934 66.00109779  1.          4.40817696]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -33.57297588995185
Optimization restart 2/5, f = -33.572975890034414
Optimization restart 3/5, f = 7.128383500718677
Optimization restart 4/5, f = 7.128383500718996
Optimization restart 5/5, f = 7.1283835007209895
[[ 5.         16.36189978 16.12283134 48.57185831  2.          4.21824211]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -34.721425965600005
Optimization restart 2/5, f = 7.425523213963874
Optimization restart 3/5, f = 7.425523213970653
Optimization restart 4/5, f = 7.42552321396386
Optimization restart 5/5, f = 7.425523213963867
[[20.          8.66508391 26.02387315 36.63613525  2.          2.75214909]]

User function time loss called with 1 inputs to simulate

Evaluating i

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[13.         14.15407249  5.82361336 40.89174666  3.          3.80822998]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -40.88477053237284
Optimization restart 2/5, f = -40.884770532377814
Optimization restart 3/5, f = 6.9160924603672385
Optimization restart 4/5, f = -40.88477053234554
Optimization restart 5/5, f = -40.884770532379335
[[ 6.         23.67430581 13.59763985 60.76184911  3.          4.51379367]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -41.48822998185887
Optimization restart 2/5, f = 7.109174914144884
Optimization restart 3/5, f = -41.48822998183898
Optimization restart 4/5, f = 7.109174914145285
Optimization restart 5/5, f = 7.109174914141629
[[19.         23.91099828 24.72920729 42.15929333  2.          3.38882625]]

User function time loss called with 1 inputs to simulate

Evaluati

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -53.82123410899723
Optimization restart 5/5, f = -53.82123410899546
[[15.         11.96494139 12.36795204 69.17683571  1.          4.65948145]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -55.693201015545895
Optimization restart 2/5, f = 8.471405084249078
Optimization restart 3/5, f = 8.471405084234206
Optimization restart 4/5, f = 8.471405084249099
Optimization restart 5/5, f = -55.693201015581906
[[ 3.         20.29406768 26.9060503  39.58346485  3.          4.6212094 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -57.19374331268773
Optimization restart 2/5, f = -57.19374331268934
Optimization restart 3/5, f = 9.279632367260621
Optimization restart 4/5, f = 9.279632518256403
Optimization restart 5/5, f = 9.279632488992252
[[17.         10.27994624 26.5589037  44.7575671

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -63.27497851503175
Optimization restart 4/5, f = 8.573106069907347
Optimization restart 5/5, f = -64.96140706624192
[[19.         24.99562404 18.75797844 57.64284821  2.          1.86339359]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -66.73780199662289
Optimization restart 2/5, f = 9.232758868005671
Optimization restart 3/5, f = 9.232758868005899
Optimization restart 4/5, f = -66.73780199663175
Optimization restart 5/5, f = 9.232758868005543
[[19.          8.53271745  5.25343962 30.19266537  2.          3.90172321]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -68.59956458408793
Optimization restart 2/5, f = -68.5995645584157
Optimization restart 3/5, f = -68.59956458408723


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -64.02096910194327
Optimization restart 5/5, f = 9.129936326893262
[[ 3.         24.95511649 24.70552219 55.65175896  1.          4.16465476]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -70.44303614208482
Optimization restart 2/5, f = -70.44303614206119
Optimization restart 3/5, f = 10.349092805807569


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = -70.44303614029093
Optimization restart 5/5, f = 10.349083425521634
[[20.         10.33853827  5.25238136 67.70649642  2.          1.66806096]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -72.25845288872272
Optimization restart 2/5, f = 10.073954364571613
Optimization restart 3/5, f = -72.25845288896042
Optimization restart 4/5, f = 10.073954364571538
Optimization restart 5/5, f = 10.073954364579418
[[20.          8.72277336  5.99758217 50.379003    1.          4.26995299]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -73.24716822539239
Optimization restart 2/5, f = 9.956167809981448
Optimization restart 3/5, f = 9.956165933251992
Optimization restart 4/5, f = -73.24716822557426
Optimization restart 5/5, f = 9.95616780998147
[[13.         22.71828085 26.36828312 69.9850758

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -76.75013195904785
[[20.          8.49909228 24.85631343 48.48494955  1.          1.99826662]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -78.80430765354696
Optimization restart 2/5, f = 11.616931251164978
Optimization restart 3/5, f = -78.80430765355473
Optimization restart 4/5, f = 11.616931358103006
Optimization restart 5/5, f = 11.616931357264136
[[ 3.         23.1129348  13.72827834 31.23047742  2.          4.94254567]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -79.66288020755252
Optimization restart 2/5, f = 12.259758501811831
Optimization restart 3/5, f = 12.259758501810268
Optimization restart 4/5, f = 12.259758501810786
Optimization restart 5/5, f = 12.259744553990672
[[ 5.         24.74998439  6.3017323  63.2311381   3.          3.76520089]]

User function ti

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -90.9271051624537
[[ 4.         14.3203057  15.0359931  45.51947125  3.          4.6715892 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -89.73875059956853
Optimization restart 2/5, f = 13.964521784180427
Optimization restart 3/5, f = 13.964521784045097
Optimization restart 4/5, f = 13.964519037246987
Optimization restart 5/5, f = -89.7387505995711
[[19.         19.23709593 11.07478376 38.92092662  1.          1.76140964]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -91.83195695523798
Optimization restart 2/5, f = -91.83195695540164
Optimization restart 3/5, f = 13.983525489180927
Optimization restart 4/5, f = 13.98352548126735
Optimization restart 5/5, f = 13.98352566652268
[[13.         24.79126686 12.58470176 54.15576468  3.          4.75853092]]

User function time l

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -113.91159131325914
Optimization restart 4/5, f = -113.91159131341789
Optimization restart 5/5, f = -113.91159131336919
[[ 3.         21.98141171  5.07285994 69.76452592  2.          1.50844383]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -115.98441070505737
Optimization restart 2/5, f = -115.98441045009676


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -115.98441070603448
Optimization restart 4/5, f = -115.98441070007334
Optimization restart 5/5, f = -115.98441070630544
[[20.         18.89541587 25.97652801 51.72666722  1.          4.55099789]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -118.15400177394184
Optimization restart 2/5, f = -118.154001775362
Optimization restart 3/5, f = 17.93096827443108
Optimization restart 4/5, f = -118.15400177407943
Optimization restart 5/5, f = -118.15400177528096
[[16.         23.06523465  5.05418163 57.78697589  3.          2.15244352]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -120.12406010286765
Optimization restart 2/5, f = -120.12406010350637
Optimization restart 3/5, f = -120.12406010333505
Optimization restart 4/5, f = -120.12406010199504
Optimization restart 5/5, f = -120.1

Optimization restart 3/5, f = -150.01377150705858
Optimization restart 4/5, f = -150.01377150724252
Optimization restart 5/5, f = -150.01377150730244
[[19.         14.28888994 26.89546908 36.5274274   3.          3.57554375]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -151.8631208950873
Optimization restart 2/5, f = -151.8631491774288
Optimization restart 3/5, f = -151.8631491804157
Optimization restart 4/5, f = -151.8631491802652
Optimization restart 5/5, f = -151.86314918043584
[[10.         10.207845    5.59391985 69.23391035  2.          4.37205736]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -153.44768683974905
Optimization restart 2/5, f = -153.44768683108333
Optimization restart 3/5, f = -153.44768683971705
Optimization restart 4/5, f = -153.44768683974183
Optimization restart 5/5, f = -100.9

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -173.6457890128938
Optimization restart 4/5, f = -173.6457890048664
Optimization restart 5/5, f = -173.64578898389146
[[20.         13.40178151 24.55669332 41.73475641  1.          4.53183058]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -175.98334170679848
Optimization restart 2/5, f = 25.689958228718304
Optimization restart 3/5, f = -175.98335975144613
Optimization restart 4/5, f = -175.98335975235008
Optimization restart 5/5, f = -175.98335975159188
[[ 6.          8.28177335  7.08111293 30.07935889  3.          4.68692064]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -177.93893279968316
Optimization restart 2/5, f = 25.87388734639812
Optimization restart 3/5, f = -177.9389327290192
Optimization restart 4/5, f = -177.93893279986682
Optimization restart 5/5, f = 25.87388

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -172.8914813903528
Optimization restart 3/5, f = -175.76188636244675
Optimization restart 4/5, f = 26.712138976701652
Optimization restart 5/5, f = -175.76188636181803
[[13.         21.14966649 26.32469436 44.36758705  3.          4.82628937]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -178.0145364067381
Optimization restart 2/5, f = -122.1460220459031


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -178.01453639669987
Optimization restart 4/5, f = -178.0145364071351
Optimization restart 5/5, f = -178.0145364063817
[[19.         23.7347014  26.89636235 57.4122574   2.          4.02602444]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -180.279581656463
Optimization restart 2/5, f = -180.27965502132508
Optimization restart 3/5, f = -180.27965502118582
Optimization restart 4/5, f = -180.27965501941424
Optimization restart 5/5, f = -180.27965502142658
[[ 4.          9.57858201 23.17310365 55.35188003  1.          4.95366834]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -182.41780814048624
Optimization restart 2/5, f = -182.41780813997994
Optimization restart 3/5, f = -182.4178081404562
Optimization restart 4/5, f = -182.4178081399674
Optimization restart 5/5, f = -182.417

Optimization restart 3/5, f = -210.40405216591543
Optimization restart 4/5, f = -210.4040521654744
Optimization restart 5/5, f = -210.40405216579796
[[ 3.         24.17874628  5.13312724 60.12815748  3.          3.19166727]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -212.41147139439212
Optimization restart 2/5, f = -212.4114714012756
Optimization restart 3/5, f = -212.41147140155957
Optimization restart 4/5, f = -212.41147139994018
Optimization restart 5/5, f = -212.41147139979174
[[18.         15.920758   11.19670823 57.88895219  3.          1.50385069]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -214.72151208830385
Optimization restart 2/5, f = -211.25878558831658


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -214.72151209001424
Optimization restart 4/5, f = 32.24656005887468
Optimization restart 5/5, f = -214.72151209021865
[[20.         12.16452721 26.82563931 34.94848964  1.          2.9419165 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -216.88373614711662
Optimization restart 2/5, f = -216.8837610533578
Optimization restart 3/5, f = -216.88376105154447
Optimization restart 4/5, f = -216.88376105332932
Optimization restart 5/5, f = -216.88376105334765
[[13.         24.94441971 15.79896517 69.55681051  1.          2.23887491]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -218.90756489565268
Optimization restart 2/5, f = -218.90756489565996
Optimization restart 3/5, f = -218.90756489350542
Optimization restart 4/5, f = -218.9075648957585
Optimization restart 5/5, f = -218.9

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -221.15999958400192
Optimization restart 5/5, f = -221.15999958330184
[[11.         24.76903141 19.90425123 40.32831429  1.          4.36999601]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -223.36060727801737
Optimization restart 2/5, f = -223.36060727822
Optimization restart 3/5, f = -223.36060727817477
Optimization restart 4/5, f = -223.36060727635146
Optimization restart 5/5, f = -223.36060727832415
[[20.          8.75567326 24.22461977 58.57267341  3.          1.72297906]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -225.65721654929663
Optimization restart 2/5, f = -225.6572231432444
Optimization restart 3/5, f = -225.65722329181264
Optimization restart 4/5, f = -225.65722329180983
Optimization restart 5/5, f = -225.65722329012402
[[16.          9.25712364  5.5399069

Optimization restart 5/5, f = 38.75285123364354
[[11.         17.38026775 26.85197083 58.17419916  1.          1.55616457]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -259.7383525014456
Optimization restart 2/5, f = -259.7386371783308
Optimization restart 3/5, f = -259.7386372183425
Optimization restart 4/5, f = -259.73863721760694
Optimization restart 5/5, f = -259.73863721858163
[[ 3.          8.74081293 15.79906203 51.05331349  3.          4.84528395]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -261.92633559772275
Optimization restart 2/5, f = -261.9263500441471
Optimization restart 3/5, f = -261.9263500447875
Optimization restart 4/5, f = -261.92635004478143
Optimization restart 5/5, f = -261.9263500431822
[[20.         18.07463167 14.07475805 61.48799634  3.          4.92576743]]

User function

[[17.          8.16458104  5.15230207 60.38526088  1.          2.65184577]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -292.9108527098798
Optimization restart 2/5, f = -292.9108808646439
Optimization restart 3/5, f = -292.9108808660077
Optimization restart 4/5, f = -292.9108808659988
Optimization restart 5/5, f = -292.91088086584
[[19.         17.20178528  5.14812295 62.73447155  3.          1.54364454]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -295.02975959250597
Optimization restart 2/5, f = -295.02976277640096
Optimization restart 3/5, f = 43.6533830360336
Optimization restart 4/5, f = 43.653383085913234
Optimization restart 5/5, f = -295.029762776255
[[20.         24.65249224 26.98711926 50.58501009  1.          4.04719624]]

User function time loss called with 1 inputs to simulate

Evaluating

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -299.50188943747463
Optimization restart 4/5, f = -299.5018894376577
Optimization restart 5/5, f = -299.50188943764874
[[ 8.         15.9259772   9.58696327 39.79748189  3.          4.80541354]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -300.6737215623242
Optimization restart 2/5, f = -300.67372156303236
Optimization restart 3/5, f = -300.67372156516626
Optimization restart 4/5, f = -300.6737215635611
Optimization restart 5/5, f = -300.6737215652155
[[20.         24.69699646 15.76667215 41.633713    3.          1.83713541]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -302.7857766609492
Optimization restart 2/5, f = -302.7857882718194
Optimization restart 3/5, f = -302.78578827347815
Optimization restart 4/5, f = -302.78578827346473
Optimization restart 5/5, f = -302.785

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -301.78723320375866
Optimization restart 4/5, f = -307.3351712329786
Optimization restart 5/5, f = -307.3351661811666
[[ 3.         19.45079658  8.91768384 60.97893853  1.          4.81625225]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -308.54042981999254
Optimization restart 2/5, f = -308.5404298184829
Optimization restart 3/5, f = -308.54042981971975
Optimization restart 4/5, f = -308.5404298186842
Optimization restart 5/5, f = 46.01080777504393
[[ 6.          8.27105519 25.19045753 48.03305219  1.          3.96811494]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -310.75467161226584
Optimization restart 2/5, f = -310.7546716121706
Optimization restart 3/5, f = -310.75467161226413
Optimization restart 4/5, f = 45.90822097745195
Optimization restart 5/5, f = -310.754671

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -334.08210790130005
Optimization restart 4/5, f = -334.0821079012725
Optimization restart 5/5, f = -334.0821079011447
[[11.          8.44420137 25.23923542 59.88745353  3.          1.52899711]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -336.5044636645853
Optimization restart 2/5, f = -336.504557692007
Optimization restart 3/5, f = -336.5045576368775
Optimization restart 4/5, f = -336.50455768356744
Optimization restart 5/5, f = -336.5045576955974
[[14.         13.57952353 14.74564876 41.92088903  1.          1.53389535]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -338.1914802241223
Optimization restart 2/5, f = -338.19148022390004
Optimization restart 3/5, f = -338.19148022408
Optimization restart 4/5, f = -338.19148021154524
Optimization restart 5/5, f = -338.19148022

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -335.62769621226744
Optimization restart 3/5, f = -341.6317585966856
Optimization restart 4/5, f = -341.6317586024953
Optimization restart 5/5, f = -341.63175860306353
[[ 5.         12.22718013 12.04826324 58.84921036  3.          1.53831087]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -342.68534017349157
Optimization restart 2/5, f = -342.68534017290995
Optimization restart 3/5, f = -342.68534017321883
Optimization restart 4/5, f = -342.6853401735056
Optimization restart 5/5, f = -342.68534017349316
[[ 3.         20.26414724 12.27187839 34.17191954  1.          4.5317266 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -344.3376023199527
Optimization restart 2/5, f = -344.3376023200848


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -343.6901865363072
Optimization restart 4/5, f = -344.337602320112
Optimization restart 5/5, f = -344.33760232003044
[[20.         12.6136702  12.78579933 61.46601427  3.          4.48863413]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -346.7258070153097
Optimization restart 2/5, f = -346.7258070087669
Optimization restart 3/5, f = -346.7258070662964
Optimization restart 4/5, f = 50.06283894165743
Optimization restart 5/5, f = -346.72580707273005
[[ 9.         14.83541255 26.82125988 69.75092523  2.          3.71919939]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -348.7199871723552
Optimization restart 2/5, f = -348.71998715646936
Optimization restart 3/5, f = -348.7199871726474
Optimization restart 4/5, f = -348.71998716012814
Optimization restart 5/5, f = -348.7199871

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -352.24430809102296
[[11.         24.39111255  9.81202174 61.54052072  3.          4.86883638]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -354.8756785623427
Optimization restart 2/5, f = -354.8756785627902
Optimization restart 3/5, f = -354.8756785403748
Optimization restart 4/5, f = -354.87567855679214
Optimization restart 5/5, f = 50.2323165490905
[[ 9.         15.1936506  25.54945064 47.49187273  3.          4.95949809]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -356.92789681993133
Optimization restart 2/5, f = -356.92789682312014
Optimization restart 3/5, f = 50.470997473324985
Optimization restart 4/5, f = -356.9278968219636
Optimization restart 5/5, f = -356.92789682926474
[[20.         18.91048704 26.86725197 58.75514183  3.          3.98527362]]

User function

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = -364.035534192261
Optimization restart 4/5, f = -366.39582332655607
Optimization restart 5/5, f = -366.395823400037
[[10.         22.50131628 26.87385513 53.54517524  1.          1.6576273 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -368.674716049539
Optimization restart 2/5, f = -368.6747160588434
Optimization restart 3/5, f = -368.6747160591154
Optimization restart 4/5, f = -368.6747160591337
Optimization restart 5/5, f = -368.6747160590581
[[ 7.          8.49994573  5.09188343 31.55711402  3.          4.44537322]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -370.9845985009521
Optimization restart 2/5, f = -370.98461128070016
Optimization restart 3/5, f = -370.9846112581997
Optimization restart 4/5, f = -370.98461112055185


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -367.9639919531903
[[ 3.         12.79436494  5.67107613 58.83730089  3.          1.52616202]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -372.996600193753
Optimization restart 2/5, f = -372.9966001928708
Optimization restart 3/5, f = -372.996600196054
Optimization restart 4/5, f = -372.99660019584417
Optimization restart 5/5, f = 52.439684424594745
[[10.         12.61839015  8.59304694 62.9318642   1.          4.95365259]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -375.1415818364538
Optimization restart 2/5, f = -375.1415818329929
Optimization restart 3/5, f = -375.14158183859456
Optimization restart 4/5, f = 52.36398658930784
Optimization restart 5/5, f = -375.1415818392443
[[ 3.         17.48797472 22.11329369 42.15298154  1.          4.86908471]]

User function tim

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -380.55146927373
[[18.         18.40120411 16.8305497  44.375548    1.          4.85678185]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -385.5674883241862
Optimization restart 2/5, f = -385.56751086735585
Optimization restart 3/5, f = -385.56751088743067
Optimization restart 4/5, f = -385.5675108818039
Optimization restart 5/5, f = -385.5675108873088
[[ 9.         19.6705727  12.23073535 30.99360402  3.          1.54071425]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -383.23545916800936
Optimization restart 2/5, f = -383.23545917285884
Optimization restart 3/5, f = -383.2354591729503
Optimization restart 4/5, f = -383.23545917279637
Optimization restart 5/5, f = 56.737540216420584
[[14.         22.35444214 18.68364747 50.93327655  3.          1.83791903]]

User function

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = -406.23765798509623
Optimization restart 3/5, f = -406.2376580020525
Optimization restart 4/5, f = -406.2376579883071
Optimization restart 5/5, f = -406.2376580013007
[[12.         18.90551154 12.56490668 47.02076233  3.          4.91713845]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -408.1442489559802
Optimization restart 2/5, f = -408.1442489530417
Optimization restart 3/5, f = -408.144248956075
Optimization restart 4/5, f = 61.20241605544601
Optimization restart 5/5, f = 61.20241011556823
[[20.         13.40657828 12.76050973 57.54070277  3.          2.05066208]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -409.8222121411893
Optimization restart 2/5, f = -409.8222121414308
Optimization restart 3/5, f = -409.8222121414925
Optimization restart 4/5, f = -409.82221208570

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -409.82221214126764
[[12.         18.96085779 22.07957725 64.32148952  1.          1.86237826]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -412.18205587284905
Optimization restart 2/5, f = -412.1820558728548
Optimization restart 3/5, f = -412.182055872866
Optimization restart 4/5, f = -412.18205587082815
Optimization restart 5/5, f = -412.1820558708227
[[13.         24.71397202  6.39159373 58.14063621  1.          3.47765312]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -414.5614949492944
Optimization restart 2/5, f = 61.76764116311708


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -414.5614949551715
Optimization restart 4/5, f = -414.5614949541721
Optimization restart 5/5, f = -414.5614949551865
[[ 6.         24.48777587 26.22626792 37.14510632  1.          1.86819689]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -416.77952940629
Optimization restart 2/5, f = -416.7795294041489
Optimization restart 3/5, f = -416.7795294070173
Optimization restart 4/5, f = -416.7795294070976
Optimization restart 5/5, f = 63.39936870306448
[[10.         24.81185837 17.78357878 34.95661473  1.          4.77079393]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -418.26340314278156


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -410.0680734709239
Optimization restart 3/5, f = -415.9411882437218
Optimization restart 4/5, f = -418.2634031127884


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -418.263403141235
[[14.         13.03211376  5.40543703 54.19737837  3.          2.0215778 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -420.59114097887255
Optimization restart 2/5, f = -420.59115064112257
Optimization restart 3/5, f = -420.59115064807673
Optimization restart 4/5, f = -420.5911506482731
Optimization restart 5/5, f = 64.02202541084549
[[14.         19.76725656 25.15532784 54.14423976  3.          1.54795653]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -422.57370209978575
Optimization restart 2/5, f = -422.57372218949484
Optimization restart 3/5, f = 64.72976216701564
Optimization restart 4/5, f = 64.72976215331965
Optimization restart 5/5, f = -422.5737221551041
[[19.          8.02464134 20.9804667  46.95949196  1.          1.65750577]]

User function t

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -420.6451097966411
Optimization restart 5/5, f = -431.1956052761299
[[12.         24.66083186  5.40809778 30.30062632  1.          1.89451762]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -433.5310517340698
Optimization restart 2/5, f = -433.53108089256
Optimization restart 3/5, f = -433.5310809029677
Optimization restart 4/5, f = -433.5310809027312
Optimization restart 5/5, f = -433.5310808917611
[[20.          9.59938204 26.59945212 54.19179287  3.          2.42472608]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -435.93853295018437
Optimization restart 2/5, f = 64.28304558608517
Optimization restart 3/5, f = -435.93859278858247
Optimization restart 4/5, f = -435.9385927913573


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -435.938592791812
[[ 4.          8.16872311  9.41042547 58.26242897  2.          1.60416647]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -437.32353333950147
Optimization restart 2/5, f = -437.32353333947106
Optimization restart 3/5, f = -437.3235333380818
Optimization restart 4/5, f = -437.3235333395365
Optimization restart 5/5, f = -437.32353331168525
[[20.         12.36900833 26.72808957 42.06150878  1.          1.91211845]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -439.7284954543816
Optimization restart 2/5, f = -439.7285056673113
Optimization restart 3/5, f = -439.72850569786766
Optimization restart 4/5, f = -439.7285056980203
Optimization restart 5/5, f = -439.7285056954928
[[14.         11.03531306 18.73988747 37.83424447  1.          4.79685058]]

User function

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = -448.1462566447401
Optimization restart 3/5, f = -450.72132389526155
Optimization restart 4/5, f = 65.36829775059178
Optimization restart 5/5, f = -450.7213238934057
[[ 3.         18.37751285 22.31087442 46.83623661  3.          1.61033774]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -452.57416905892273
Optimization restart 2/5, f = -452.5741690598395
Optimization restart 3/5, f = -452.57416905985167
Optimization restart 4/5, f = -452.5741690629795
Optimization restart 5/5, f = -452.57416906316695


### Random GP

Supervised learning

In [19]:
emulator_rnd = GPy.models.GPRegression(train_X, train_Y)
emukit_model_rnd = GPyModelWrapper(emulator_rnd, n_restarts=50)
emukit_model_rnd.optimize()
emulator_rnd

Optimization restart 1/50, f = -512.2030638998212
Optimization restart 2/50, f = -512.2030640286398
Optimization restart 3/50, f = -512.2030640290843
Optimization restart 4/50, f = -512.2030640201525
Optimization restart 5/50, f = -512.2030640289969
Optimization restart 6/50, f = -512.203063792999
Optimization restart 7/50, f = 55.18206825175798
Optimization restart 8/50, f = -512.203064028459
Optimization restart 9/50, f = -512.203063651166
Optimization restart 10/50, f = 55.18206854534654
Optimization restart 11/50, f = -512.2030623774881
Optimization restart 12/50, f = 55.182058291435965
Optimization restart 13/50, f = -512.2030640290802
Optimization restart 14/50, f = 55.182068514598114
Optimization restart 15/50, f = -512.2030640288672
Optimization restart 16/50, f = -512.203064029027
Optimization restart 17/50, f = -512.2030639699112
Optimization restart 18/50, f = -512.2030640268636
Optimization restart 19/50, f = 55.182068545346624


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 20/50, f = -512.2030640290823
Optimization restart 21/50, f = -512.203064007515
Optimization restart 22/50, f = -512.2030640290832
Optimization restart 23/50, f = -512.2030640263912
Optimization restart 24/50, f = -512.2030640289362
Optimization restart 25/50, f = -512.2030640279381
Optimization restart 26/50, f = -512.2030640220779
Optimization restart 27/50, f = -512.203064028738
Optimization restart 28/50, f = 55.18206854534375
Optimization restart 29/50, f = -512.2030640290834
Optimization restart 30/50, f = -512.2030640255547
Optimization restart 31/50, f = -512.2030640290831
Optimization restart 32/50, f = -512.2030640288842
Optimization restart 33/50, f = 55.18205657010873
Optimization restart 34/50, f = 55.182068545346596
Optimization restart 35/50, f = -512.203063925633
Optimization restart 36/50, f = -512.2030640202236
Optimization restart 37/50, f = -512.2030640290328
Optimization restart 38/50, f = -512.2030640290849
Optimization restart 39/50, f = -512

### Evaluate

Evaluate RMSE of each model on our test set of 50 randomly selected points.

In [20]:
pred_Y, pred_Y_variance = emukit_model_ed.predict(test_X)
mse_ed = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Model Variance RMSE: ', mse_ed)

Experimental Design w/ Model Variance RMSE:  0.031421356052996174


In [21]:
pred_Y, pred_Y_variance = emukit_model_ird.predict(test_X)
mse_ird = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Integrated Variance Reduction RMSE: ', mse_ird)

Experimental Design w/ Integrated Variance Reduction RMSE:  0.03031180445853298


In [22]:
pred_Y, pred_Y_variance = emukit_model_rnd.predict(test_X)
mse_rnd = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Random GP RMSE: ', mse_rnd)

Random GP RMSE:  0.03308872848686157


In [23]:
p = 1 - (mse_ed/mse_rnd)
f'Experimental Design w/ Model Variance is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Model Variance is 5.039% better than training on random points.'

In [24]:
p = 1 - (mse_ird/mse_rnd)
f'Experimental Design w/ Integrated Variance Reduction is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Integrated Variance Reduction is 8.392% better than training on random points.'

### Save Models

In [25]:
with open(f'experimental_design/models/model_variance_20_init_points_250_loops_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_ed, f)

with open(f'experimental_design/models/integrated_variance_reduction_20_init_points_250_loops_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_ird, f)
        
with open(f'experimental_design/models/270_random_points_supervised_GP_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_rnd, f)