In [1]:
%cd ../

/Users/harrysonghurst/Documents/Coursework/L48 Machine Learning and the Physical World/TrafficEmu


In [2]:
# If you get a SciPy error when installing Emukit, build it from source:

# git clone https://github.com/amzn/Emukit.git
# cd Emukit
# pip install -r requirements/requirements.txt
# python setup.py develop

In [3]:
import numpy as np
import pickle
import emukit as ek
import GPy

from emukit.model_wrappers import GPyModelWrapper
from emukit.experimental_design.experimental_design_loop import ExperimentalDesignLoop
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.core.initial_designs import RandomDesign, latin_design
from emukit.experimental_design.acquisitions import ModelVariance, IntegratedVarianceReduction
from emukit.core.loop import UserFunctionWrapper
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.bayesian_optimization.loops import BayesianOptimizationLoop
from emukit.core.optimization import GradientAcquisitionOptimizer

from sumo_grid_simulation.grid_simulation import Simulator
import experimental_design.config as config

### Pseudocode

Fitting a gaussian process to a simulator using Emukit takes the following form (taken from L48 lectures):

```
initialize GP with some randomly chosen points
while stopping condition is not met:
    compute candidate point(s) using GP and acquisition funciton (model_variance) -> new point
    evaluate this new point with our simulator/user function -> observation
    update model with new observation -> new GP
```

### Simulator

In [4]:
simulator = Simulator(end_time=300)

### User Function
 
This is the function we want to understand. Namedly, how are CO2 emissions and timeLoss (the time lost due to driving below the ideal speed) affected by the following parameters: 

```
gridSize: the size of the grid network where the simulation is carried out
edgeMaxSpeed: legal speed limit in m/s - this can be exceeded (11.11 == 40km/h)
maxSpeed: the absolute maximum velocity of any vehicle in m/s (55.55 == 200 km/h)
edgeLength: length of the roads between intersections in meters
numLanes: number of lanes per road
accel: The acceleration ability of vehicles in m/s^2.
```

*A complete list of parmeters analysed is discussed in our report.*

In [5]:
def user_function_time_loss(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function time loss called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, maxSpeed, edgeLength, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.005
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * edgeLength / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            maxSpeed      = maxSpeed,
            edgeLength    = edgeLength,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average time loss / average route duration
        result.append(s['timeLoss']/s['duration'])
        i += 1
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

### Model Inputs / parameter space

In [6]:
parameter_space = config.get_parameter_space()

### Get init, test, and train points

Train points are used to optimize a GP without experimental design - to verify experimental design works.

In [7]:
design = RandomDesign(parameter_space)
init_X = design.get_samples(20)
init_Y = user_function_time_loss(init_X)

design = RandomDesign(parameter_space)
test_X = design.get_samples(50)
test_Y = user_function_time_loss(test_X)

design = RandomDesign(parameter_space)
train_X = design.get_samples(200)
train_Y = user_function_time_loss(train_X)

[[12.         13.2472251  16.00309042 44.15647269  1.          4.84037006]
 [ 3.         13.85991128 21.52428571 63.58881136  3.          4.53875461]
 [20.         20.49378826 13.58839796 56.78815434  1.          4.49833466]
 [12.         21.1110553  13.08387654 53.73658844  1.          3.32115863]
 [18.         11.63207666 18.40559721 38.82298417  3.          1.92153349]
 [ 6.         10.5960296   5.14359864 36.50388433  1.          3.45380455]
 [13.         24.10880585 16.08695157 48.01906136  2.          3.78158195]
 [15.         14.9719694  15.21440119 37.37005081  1.          1.62425583]
 [15.          8.60571641 25.98958494 56.45145224  2.          1.52055699]
 [18.         19.42708537  8.41937406 62.14267917  2.          3.62195194]
 [11.          9.17628712 14.01462276 58.14471293  1.          3.38775973]
 [ 5.          8.48478217 23.48863628 47.67340324  3.          3.32045529]
 [10.         15.25176756 13.1581459  64.54878793  1.          3.63920978]
 [ 6.         21.83984647


Evaluating input: 36 of 50

 Retrying in 1 seconds

Evaluating input: 37 of 50

 Retrying in 1 seconds

Evaluating input: 38 of 50

 Retrying in 1 seconds

Evaluating input: 39 of 50

 Retrying in 1 seconds

Evaluating input: 40 of 50

 Retrying in 1 seconds

Evaluating input: 41 of 50

 Retrying in 1 seconds

Evaluating input: 42 of 50

 Retrying in 1 seconds

Evaluating input: 43 of 50

 Retrying in 1 seconds

Evaluating input: 44 of 50

 Retrying in 1 seconds

Evaluating input: 45 of 50

 Retrying in 1 seconds

Evaluating input: 46 of 50

 Retrying in 1 seconds

Evaluating input: 47 of 50

 Retrying in 1 seconds

Evaluating input: 48 of 50

 Retrying in 1 seconds

Evaluating input: 49 of 50

 Retrying in 1 seconds

Evaluating input: 50 of 50

 Retrying in 1 seconds
[[16.         20.72584304  5.69355467 65.12260492  1.          3.28939768]
 [18.         20.73277493  5.06573506 39.19151712  1.          3.74252115]
 [13.         13.82300535  5.29443477 64.64586959  2.          2.42841


Evaluating input: 131 of 200

 Retrying in 1 seconds

Evaluating input: 132 of 200

 Retrying in 1 seconds

Evaluating input: 133 of 200

 Retrying in 1 seconds

Evaluating input: 134 of 200

 Retrying in 1 seconds

Evaluating input: 135 of 200

 Retrying in 1 seconds

Evaluating input: 136 of 200

 Retrying in 1 seconds

Evaluating input: 137 of 200

 Retrying in 1 seconds

Evaluating input: 138 of 200

 Retrying in 1 seconds

Evaluating input: 139 of 200

 Retrying in 1 seconds

Evaluating input: 140 of 200

 Retrying in 1 seconds

Evaluating input: 141 of 200

 Retrying in 1 seconds

Evaluating input: 142 of 200

 Retrying in 1 seconds

Evaluating input: 143 of 200

 Retrying in 1 seconds

Evaluating input: 144 of 200

 Retrying in 1 seconds

Evaluating input: 145 of 200

 Retrying in 1 seconds

Evaluating input: 146 of 200

 Retrying in 1 seconds

Evaluating input: 147 of 200

 Retrying in 1 seconds

Evaluating input: 148 of 200

 Retrying in 1 seconds

Evaluating input: 149 of 20

### Experimental Design - Model Variance

#### Model / Emulator (GP)

Our surrogate model is our emulator. In this case, a gaussian process.

In [8]:
emulator_ed = GPy.models.GPRegression(init_X, init_Y, noise_var=1e-10)
emukit_model_ed = GPyModelWrapper(emulator_ed, n_restarts=5)
emukit_model_ed.optimize()
emulator_ed

Optimization restart 1/5, f = -18.904667569713787
Optimization restart 2/5, f = 3.656207533743695
Optimization restart 3/5, f = 3.656206260245183
Optimization restart 4/5, f = 3.6562078363206005
Optimization restart 5/5, f = -16.417645787637227


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


#### Acquisition Function

In [9]:
model_variance = ModelVariance(model=emukit_model_ed)

#### Optimizer

In [10]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [11]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ed,
    space = parameter_space,
    acquisition = model_variance,
    acquisition_optimizer = optimizer,
)

In [12]:
ed_loop.run_loop(user_function_time_loss, 200)

Optimization restart 1/5, f = -18.904667569713787
Optimization restart 2/5, f = 3.6562047897258445
Optimization restart 3/5, f = 3.656207836243727
Optimization restart 4/5, f = 3.656207836328477
Optimization restart 5/5, f = -20.62882771019055
[[20. 25.  5. 30.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -21.71593199379032
Optimization restart 2/5, f = 3.871997132964454
Optimization restart 3/5, f = 3.871997139736994
Optimization restart 4/5, f = -20.48694020038961
Optimization restart 5/5, f = 3.8719971397521906
[[ 3.  25.   5.  70.   3.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1



 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -22.855172845274165
Optimization restart 2/5, f = 3.5962316712748077
Optimization restart 3/5, f = 3.596231673084688
Optimization restart 4/5, f = 3.5962316730846826
Optimization restart 5/5, f = 3.5962316730813217
[[ 3.  8. 27. 30.  1.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -23.886091431685745
Optimization restart 2/5, f = 3.4944466810065684
Optimization restart 3/5, f = -23.886091431332527
Optimization restart 4/5, f = 3.4944466810072257
Optimization restart 5/5, f = 3.4944458300504078
[[20.  8.  5. 70.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -24.402992002574695
Optimization restart 2/5, f = 3.5440843044010304
Optimization restart 3/5, f = -24.402992003135772
Optimization restart 4/5, f = 3.544083794989982
Optimization res

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -25.467718180115313
Optimization restart 2/5, f = 3.236862840409433
Optimization restart 3/5, f = -25.46771818025805
Optimization restart 4/5, f = 3.236863160931364
Optimization restart 5/5, f = 3.236863161000663
[[20.  8.  5. 30.  1.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1



 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -26.521747355664573
Optimization restart 2/5, f = 3.280295009646533
Optimization restart 3/5, f = 3.280295904239498
Optimization restart 4/5, f = 3.280295341034339
Optimization restart 5/5, f = -26.52174735692113
[[ 3.  25.  27.  70.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -26.071916412230166
Optimization restart 2/5, f = 5.0925819947254904
Optimization restart 3/5, f = 5.092581183945221
Optimization restart 4/5, f = 5.092581994725471
Optimization restart 5/5, f = -26.071916414097426
[[ 3. 25. 27. 30.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -27.545468549218615
Optimization restart 2/5, f = 6.666775708505202
Optimization restart 3/5, f = -27.545468549234386
Optimization restart 4/5, f = 6.66676839705171
Optimization res

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -30.139621969129163
Optimization restart 2/5, f = 6.439975900065525
Optimization restart 3/5, f = -30.13962196913505
Optimization restart 4/5, f = 6.4399759064057545
Optimization restart 5/5, f = -30.139621969135227
[[ 3.         25.          5.         41.11453054  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1



 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -31.59257709866666
Optimization restart 2/5, f = 6.4623120873505755
Optimization restart 3/5, f = -31.592577098668976
Optimization restart 4/5, f = -31.592577098668617
Optimization restart 5/5, f = -31.59257709866578
[[20.  25.   5.  70.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -33.313658301639606
Optimization restart 2/5, f = -33.31365830169872
Optimization restart 3/5, f = 6.202633690747895
Optimization restart 4/5, f = 6.202633804290807
Optimization restart 5/5, f = 6.2026250259760705
[[20. 25. 27. 30.  1.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -35.11614412054189
Optimization restart 2/5, f = 7.584711951891844
Optimization restart 3/5, f = -35.11614412037575
Optimization restart 4/5, f = -35.116144119697424
Optimization

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -48.35789272109558
Optimization restart 2/5, f = -48.35789272112517
Optimization restart 3/5, f = -48.35789271971469
Optimization restart 4/5, f = -48.35789272007959
Optimization restart 5/5, f = 9.543797957191781
[[ 3.  25.   5.  30.   3.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -45.554892831569326
Optimization restart 2/5, f = -45.55489283160513
Optimization restart 3/5, f = 9.346435446093906
Optimization restart 4/5, f = -45.554892830899554
Optimization restart 5/5, f = 9.346435578901687
[[12.         15.10403543 27.         30.          3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -47.4659692435231
Optimization restart 2/5, f = 10.164763011628963
Optimization restart 3/5, f = 10.164763011629365
Optimization res

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -55.53902123997285
Optimization restart 2/5, f = -55.53902123928559
Optimization restart 3/5, f = -55.53902123796728
Optimization restart 4/5, f = -55.53902123995759
Optimization restart 5/5, f = 11.510533463625215
[[ 3.         25.         12.69795146 55.38540981  1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -57.63611907226445
Optimization restart 2/5, f = 11.74836824393034
Optimization restart 3/5, f = 11.748366727164672
Optimization restart 4/5, f = 11.74836969755654
Optimization restart 5/5, f = -57.636119072247084
[[ 3.  8.  5. 70.  1.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -58.83172932812026
Optimization restart 2/5, f = 11.797094883805258
Optimization restart 3/5, f = -58.83172932935446
Optimization restart 

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -62.48218161714436
[[20. 25.  5. 70.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -60.638024480096206
Optimization restart 2/5, f = 11.802354841195807
Optimization restart 3/5, f = 11.802354841195815
Optimization restart 4/5, f = 11.802354841195822
Optimization restart 5/5, f = 11.802354841197566
[[ 3.   8.   5.  30.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -62.44965005741005
Optimization restart 2/5, f = -62.449650057391565
Optimization restart 3/5, f = -62.44965005736708
Optimization restart 4/5, f = -62.44965005657832
Optimization restart 5/5, f = 11.586526653070933
[[ 3.          8.         14.08645591 53.75152363  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 secon

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


 Retrying in 1 seconds
Optimization restart 1/5, f = -75.59676202000387
Optimization restart 2/5, f = -75.5967620202038
Optimization restart 3/5, f = -75.5967620201524
Optimization restart 4/5, f = -75.59676201956944
Optimization restart 5/5, f = -75.59676201970554
[[20.  25.   5.  30.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -74.18121805995321
Optimization restart 2/5, f = 19.2417367026599
Optimization restart 3/5, f = -74.18121805994264
Optimization restart 4/5, f = 19.241736701946188
Optimization restart 5/5, f = -74.18121805983736
[[20.  8.  5. 70.  1.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -76.20337862369601
Optimization restart 2/5, f = 19.325163011644264
Optimization restart 3/5, f = 19.325173608874287
Optimization restart 4/5, f = -76.2033786237468
Optimization resta

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


 Retrying in 1 seconds
Optimization restart 1/5, f = -78.27852172021323
Optimization restart 2/5, f = -78.27852172020891
Optimization restart 3/5, f = -78.2785217202024
Optimization restart 4/5, f = 19.528511894801476
Optimization restart 5/5, f = -78.27852172025959
[[ 3.          8.         18.28465527 70.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -80.31534465343954
Optimization restart 2/5, f = 19.466862763120382
Optimization restart 3/5, f = 19.466862762787365
Optimization restart 4/5, f = -80.31534465586947
Optimization restart 5/5, f = -80.31534465596673
[[12.         25.          5.         58.04265114  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -82.35447291824056
Optimization restart 2/5, f = -82.35447291873676
Optimization restart 3

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


[[ 3.         17.82164732  5.         51.81832091  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -95.37606497376568
Optimization restart 2/5, f = -78.99214006199313
Optimization restart 3/5, f = -95.37606497387246
Optimization restart 4/5, f = -95.3760649738729
Optimization restart 5/5, f = -95.37606497378063
[[ 3.         14.61757311 27.         61.52144275  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -97.09313878048059
Optimization restart 2/5, f = -97.0931387804377
Optimization restart 3/5, f = -97.0931387805064
Optimization restart 4/5, f = -97.09313878050685
Optimization restart 5/5, f = -97.09313878040804
[[13.   8.   5.  70.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Opt

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = -76.44597194744938
Optimization restart 5/5, f = -99.00911991873994
[[20.          8.         12.74448784 30.          1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -99.79696984963479
Optimization restart 2/5, f = 22.52012277842907
Optimization restart 3/5, f = -99.7969698495393
Optimization restart 4/5, f = -99.79696984798643
Optimization restart 5/5, f = 22.520122778429474
[[ 3.         12.0256042  17.99835421 70.          3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -99.05550618450786
Optimization restart 2/5, f = 22.703779853153172
Optimization restart 3/5, f = -99.05550618447232
Optimization restart 4/5, f = 22.703779853153144
Optimization restart 5/5, f = -99.05550618451507
[[ 3. 25. 27. 70.  3.  5.]]

User function tim

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -124.32718818775867
Optimization restart 4/5, f = -124.32718818762393
Optimization restart 5/5, f = -124.32718818729788
[[ 3.         19.58160158  5.         30.          1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -125.52407782776491
Optimization restart 2/5, f = -125.52407782772713
Optimization restart 3/5, f = -125.52407782776643
Optimization restart 4/5, f = -125.5240778277637
Optimization restart 5/5, f = 26.658457447045713
[[20.         17.87257284 27.         43.37921244  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -127.59188158446194
Optimization restart 2/5, f = 27.15770913632037
Optimization restart 3/5, f = 27.157709136407277
Optimization restart 4/5, f = -127.59188159087307
Optimization restart 5/5, f = -127.59

 Retrying in 1 seconds
Optimization restart 1/5, f = -160.27251601979452
Optimization restart 2/5, f = 24.249998418175636
Optimization restart 3/5, f = 24.249997532251236
Optimization restart 4/5, f = -125.33304579825048


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -127.37144979518305
[[20.  8.  5. 30.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -162.40171400738
Optimization restart 2/5, f = -129.96590405207272
Optimization restart 3/5, f = -162.40171400748966
Optimization restart 4/5, f = -129.96590405216205
Optimization restart 5/5, f = -162.40171400739203
[[13.  8. 27. 30.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -163.66591858463542
Optimization restart 2/5, f = -131.26543531562874
Optimization restart 3/5, f = -131.2654322887961
Optimization restart 4/5, f = -131.26542965734734
Optimization restart 5/5, f = 24.631602955604386
[[ 3.          8.         10.97859996 30.          1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Optimization restart 3/5, f = -196.87452878793164
Optimization restart 4/5, f = -161.3687422207896
Optimization restart 5/5, f = -161.3687426695427
[[ 3.         25.          5.         35.73519685  1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -198.6445730611695
Optimization restart 2/5, f = -163.53156516893048
Optimization restart 3/5, f = -198.6445730609575
Optimization restart 4/5, f = -163.5315648848998
Optimization restart 5/5, f = -163.5315648905218
[[20.        14.0826167  5.        70.         1.         1.5      ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -200.82147689405076
Optimization restart 2/5, f = 29.402812720754298
Optimization restart 3/5, f = -200.82148721114567
Optimization restart 4/5, f = -164.94165597089875
Optimization restart 5/5, f = -164.9416559705

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -171.9125705985011
Optimization restart 4/5, f = -214.23435787711503
Optimization restart 5/5, f = -214.23435788067016
[[ 3.        20.1527669  5.        39.6889591  3.         5.       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -216.54527182917815
Optimization restart 2/5, f = 33.7917551422787
Optimization restart 3/5, f = -216.54528549842476
Optimization restart 4/5, f = -174.07802378062385
Optimization restart 5/5, f = -216.54528550036338
[[20.         17.2556888   5.         38.08275608  3.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -216.3970925456734
Optimization restart 2/5, f = 33.610206316904936
Optimization restart 3/5, f = -216.3970925443601
Optimization restart 4/5, f = -216.39709254537127
Optimization restart 5/5, f = -175.4310474423

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -159.2826235726975
[[15.   8.   5.  30.   1.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -224.0936571119557
Optimization restart 2/5, f = -178.0316841184461
Optimization restart 3/5, f = 35.65464214158078
Optimization restart 4/5, f = -178.0316841174781
Optimization restart 5/5, f = -178.03168377095977
[[20.          8.          5.         61.45730117  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -226.19820736544887
Optimization restart 2/5, f = -226.19820736551478
Optimization restart 3/5, f = -180.23703333444803
Optimization restart 4/5, f = -226.19820736541558
Optimization restart 5/5, f = -226.19820735717042
[[ 3.         15.49577197  8.28381751 70.          1.          1.5       ]]

User function time loss called with 1 inputs to simul

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = -239.1498236253689
Optimization restart 5/5, f = 38.493894744520304
[[ 9.          8.         15.28880498 70.          1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -241.4718202523697
Optimization restart 2/5, f = -193.1449105642247
Optimization restart 3/5, f = 38.328815119934674
Optimization restart 4/5, f = -241.47183329992396
Optimization restart 5/5, f = -241.4718332988799
[[20.          8.          5.         45.29974782  3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -243.73667353318922
Optimization restart 2/5, f = -243.73667352251772
Optimization restart 3/5, f = -243.7366735340795
Optimization restart 4/5, f = -243.73667353028952
Optimization restart 5/5, f = 38.41143703641504
[[ 3.          8.         17.01714522 46.

 Retrying in 1 seconds
Optimization restart 1/5, f = -269.56781024291735
Optimization restart 2/5, f = -222.02080303434388
Optimization restart 3/5, f = 42.24174702957998
Optimization restart 4/5, f = -269.5678059773969
Optimization restart 5/5, f = -269.5678102133104
[[ 3.         14.92752003  5.         58.61792706  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -271.7867167873659
Optimization restart 2/5, f = -271.78671678741944
Optimization restart 3/5, f = -223.90885507186783
Optimization restart 4/5, f = -271.7867167874493
Optimization restart 5/5, f = -271.7867167826543
[[ 3.         25.          9.97408402 44.8224463   3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -272.55638504199544
Optimization restart 2/5, f = -224.58646360925502
Optimization res

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = 43.191133324300694
[[ 3.          8.          5.         38.96261593  3.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -273.1907050893194
Optimization restart 2/5, f = -228.4279575386841
Optimization restart 3/5, f = -273.190710480237
Optimization restart 4/5, f = 43.28641939640514
Optimization restart 5/5, f = -273.1907104805407
[[ 3. 25. 27. 30.  3.  5.]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -275.46512573547744
Optimization restart 2/5, f = -236.37278592837183
Optimization restart 3/5, f = -236.37278531882475
Optimization restart 4/5, f = -275.46512572945664
Optimization restart 5/5, f = -275.4651257348445
[[12.  25.   5.  70.   3.   1.5]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 secon

 Retrying in 1 seconds
Optimization restart 1/5, f = -313.4807491729466
Optimization restart 2/5, f = -274.29741083006076
Optimization restart 3/5, f = -313.48074917160704
Optimization restart 4/5, f = -313.480749173088
Optimization restart 5/5, f = -274.297459204614
[[ 3.          8.          5.         54.00058821  1.          1.5       ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -315.8662175969346
Optimization restart 2/5, f = -276.82836404020145
Optimization restart 3/5, f = -276.82836403973886
Optimization restart 4/5, f = 30.677143809173288
Optimization restart 5/5, f = 30.677141378772518
[[11.          8.         27.         38.78460579  1.          5.        ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -318.1927768217626
Optimization restart 2/5, f = -279.0819076632956
Optimization restar

### Experimental Design - Integrated Variance Reduction

#### Model / Emulator (GP)

In [13]:
emulator_ird = GPy.models.GPRegression(init_X, init_Y, noise_var=1e-10)
emukit_model_ird = GPyModelWrapper(emulator_ird, n_restarts=5)
emukit_model_ird.optimize()

Optimization restart 1/5, f = -18.904667569713787
Optimization restart 2/5, f = -16.174154145089986
Optimization restart 3/5, f = -20.62882771018527
Optimization restart 4/5, f = 3.6562078363206503
Optimization restart 5/5, f = -15.276560778342347


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


#### Acquisition Function

In [14]:
integrated_variance_reduction = IntegratedVarianceReduction(model=emukit_model_ird, space=parameter_space)

#### Optimizer

In [15]:
optimizer = GradientAcquisitionOptimizer(parameter_space)

#### Experimental Design Loop

In [16]:
ed_loop = ExperimentalDesignLoop(
    model = emukit_model_ird,
    space = parameter_space,
    acquisition = integrated_variance_reduction,
    acquisition_optimizer = optimizer,
)

In [17]:
ed_loop.run_loop(user_function_time_loss, 200)

Optimization restart 1/5, f = -20.62882771018527
Optimization restart 2/5, f = 3.656207836320588
Optimization restart 3/5, f = 3.6562078363216095
Optimization restart 4/5, f = 3.6562078363205828
Optimization restart 5/5, f = -20.62882771019055
[[17.         23.32748358  8.42152435 33.41587479  2.          2.80209198]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -20.262776246018483
Optimization restart 2/5, f = 3.4885194618037225
Optimization restart 3/5, f = -20.262776238081415
Optimization restart 4/5, f = 3.4885194618067867
Optimization restart 5/5, f = -20.262776246021346
[[11.         13.84125762 24.98554391 30.70943842  2.          4.61993872]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -21.18661453426204
Optimization restart 2/5, f = 3.8797105247745254
Optimization restart 3/5, f = 3.8797105237

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[ 3.          8.54120708  5.61644471 64.63306064  2.          2.01050509]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -31.838593320727732
Optimization restart 2/5, f = -31.838593320840523
Optimization restart 3/5, f = 6.944193774624775
Optimization restart 4/5, f = 6.944193774626209
Optimization restart 5/5, f = -31.838593320831876
[[19.         13.02153747  8.31226682 55.77479018  3.          1.7189555 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -33.61730093405677
Optimization restart 2/5, f = 6.769352259385604
Optimization restart 3/5, f = 6.769352259385595
Optimization restart 4/5, f = 6.769352259385725
Optimization restart 5/5, f = -33.61730093399093
[[18.         10.48662274  9.3891217  32.61277922  3.          3.59998204]]

User function time loss called with 1 inputs to simulate

Evaluatin

 Retrying in 1 seconds
Optimization restart 1/5, f = -52.049969785594755
Optimization restart 2/5, f = 10.808414367992732
Optimization restart 3/5, f = 10.808409918725836
Optimization restart 4/5, f = -52.04996978563721
Optimization restart 5/5, f = 10.808414367154036
[[17.         24.53211668 22.14640013 65.17714762  1.          4.41324722]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -53.67351020735266
Optimization restart 2/5, f = 11.242330128762877
Optimization restart 3/5, f = -53.67351020751498
Optimization restart 4/5, f = 11.242328961174557
Optimization restart 5/5, f = -53.673510206180936
[[20.         17.049019    8.08565913 40.98840518  2.          3.19470958]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -53.35575491756653
Optimization restart 2/5, f = 11.102488269197895
Optimization restar

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


[[ 8.          8.01608542 13.50072056 32.95147298  1.          4.54780275]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -57.381218664223326
Optimization restart 2/5, f = 11.417915086606701
Optimization restart 3/5, f = 11.417915078757161
Optimization restart 4/5, f = -57.38121866414877
Optimization restart 5/5, f = 11.417915086607241
[[20.          8.1796292  18.82446909 48.9924589   3.          3.2481671 ]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -59.30997640380999
Optimization restart 2/5, f = 11.254113466292264
Optimization restart 3/5, f = -59.30997640384717
Optimization restart 4/5, f = 11.254113466292342
Optimization restart 5/5, f = -59.30997640347998
[[16.          9.84589837  5.1525276  66.21243309  1.          1.50202632]]

User function time loss called with 1 inputs to simulate

Evalua

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -77.96550809248853
[[20.         10.34837979  5.18880931 48.56063415  1.          3.86830023]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -79.76744833516062
Optimization restart 2/5, f = 14.571659235250443
Optimization restart 3/5, f = 14.571625916428594
Optimization restart 4/5, f = -79.76744833517671
Optimization restart 5/5, f = 14.57165919210069
[[13.         24.81871008 24.67492202 41.93115253  1.          4.98898671]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -81.85462736059023
Optimization restart 2/5, f = 15.537041017321144
Optimization restart 3/5, f = -81.85462736078658
Optimization restart 4/5, f = 15.537053558941587


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = -81.85462736077602
[[12.         17.18198952  5.26390177 37.59817987  2.          1.79181487]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -83.33650422639354
Optimization restart 2/5, f = 15.325595980888323
Optimization restart 3/5, f = -83.33650422546064
Optimization restart 4/5, f = 15.3256002363621
Optimization restart 5/5, f = -83.3365042264056
[[ 7.         12.71840029  5.21676436 57.59493581  2.          1.87724441]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -85.46781467011333
Optimization restart 2/5, f = 15.109143760115145
Optimization restart 3/5, f = 15.109143760105006
Optimization restart 4/5, f = 15.109143760115352
Optimization restart 5/5, f = 15.109143760115622
[[13.          8.45171989 22.81580846 30.70306781  3.          1.67896375]]

User function time 

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -102.67231457514112
[[ 3.         12.65533309  9.64165349 51.32371972  1.          4.84385588]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -104.78787864387382
Optimization restart 2/5, f = -104.78788269247264
Optimization restart 3/5, f = -104.78788269150401
Optimization restart 4/5, f = -104.78788266251495
Optimization restart 5/5, f = 17.051674575370704
[[ 3.         16.32366444 16.78686349 44.0432139   3.          1.63431524]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -106.87668363100481
Optimization restart 2/5, f = 17.841788154138854
Optimization restart 3/5, f = 17.841788154138833
Optimization restart 4/5, f = 17.84178815413896
Optimization restart 5/5, f = -106.87668363055519
[[12.         23.52858996 15.71028877 34.39322789  3.          4.83015455]]

User funct

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = -119.01733267907011
Optimization restart 4/5, f = -119.01733267910093
Optimization restart 5/5, f = 20.186694110152665
[[ 3.          8.20929269  8.09356448 36.22305852  3.          3.33615426]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -120.64077150506373
Optimization restart 2/5, f = -120.64077150476504
Optimization restart 3/5, f = 20.07414782574145
Optimization restart 4/5, f = -120.64077142142315
Optimization restart 5/5, f = -120.64077150361491
[[11.          9.36944511  6.11162216 49.56981907  3.          4.85436388]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -121.60186228140432
Optimization restart 2/5, f = 20.03343843958468
Optimization restart 3/5, f = 20.033433495143015
Optimization restart 4/5, f = -121.60186228127448


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = -105.93619449252247
[[12.         24.97302654 18.71559563 43.35461848  1.          1.50791223]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -123.72546609243291
Optimization restart 2/5, f = 20.93653820704673
Optimization restart 3/5, f = 20.93653820704901
Optimization restart 4/5, f = 20.93653820704668
Optimization restart 5/5, f = 20.936538206943865
[[ 3.         24.4985083  16.79100605 57.55734744  3.          4.56402474]]

User function time loss called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds
Optimization restart 1/5, f = -125.89818235886347
Optimization restart 2/5, f = 21.369859180134185
Optimization restart 3/5, f = 21.369857574547638
Optimization restart 4/5, f = 21.369859180134334
Optimization restart 5/5, f = 21.36985918013425
[[ 3.         24.52646004 14.76226604 30.64217829  3.          4.19728835]]

User function tim

KeyboardInterrupt: 

### Random GP

Supervised learning

In [18]:
emulator_rnd = GPy.models.GPRegression(train_X, train_Y, noise_var=1e-10)
emukit_model_rnd = GPyModelWrapper(emulator_rnd, n_restarts=200)
emukit_model_rnd.optimize()
emulator_rnd

Optimization restart 1/200, f = -290.5258497515851
Optimization restart 2/200, f = -359.6234114819579
Optimization restart 3/200, f = 41.695978301154696
Optimization restart 4/200, f = 41.695978302361524
Optimization restart 5/200, f = -359.6234116719032


 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 6/200, f = -359.6234116724068
Optimization restart 7/200, f = -359.6234116714769
Optimization restart 8/200, f = -359.62341167201066
Optimization restart 9/200, f = -359.6234116679577
Optimization restart 10/200, f = -359.6234114952532
Optimization restart 11/200, f = -359.62341167244233
Optimization restart 12/200, f = -359.6234116724407
Optimization restart 13/200, f = 41.69597830219246
Optimization restart 14/200, f = 41.69597802016362
Optimization restart 15/200, f = 41.69597830236043
Optimization restart 16/200, f = -359.62341167211093
Optimization restart 17/200, f = -359.62341165274967
Optimization restart 18/200, f = 41.69597785122272
Optimization restart 19/200, f = -359.62341165333225
Optimization restart 20/200, f = -359.6234116718774
Optimization restart 21/200, f = 41.695978301009774
Optimization restart 22/200, f = -359.6234116724237
Optimization restart 23/200, f = -359.623411670319
Optimization restart 24/200, f = 41.69597804718218
Optimization rest

 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/harrysonghurst/opt/anaconda3/envs/traffic/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 32/200, f = -359.6234116704768
Optimization restart 33/200, f = 41.69597825730676
Optimization restart 34/200, f = 41.69597830213169
Optimization restart 35/200, f = -359.62341167170985
Optimization restart 36/200, f = -359.62341167243994
Optimization restart 37/200, f = -359.62341166681324
Optimization restart 38/200, f = 41.69597830236086
Optimization restart 39/200, f = 41.69597830216529
Optimization restart 40/200, f = -359.62341167158854
Optimization restart 41/200, f = 41.69597830236074
Optimization restart 42/200, f = -359.6234116724147
Optimization restart 43/200, f = -359.62341167201714
Optimization restart 44/200, f = -359.62341166934175
Optimization restart 45/200, f = 41.69597830236084
Optimization restart 46/200, f = -359.623411672442
Optimization restart 47/200, f = 41.69597830236077
Optimization restart 48/200, f = 41.69595760462818
Optimization restart 49/200, f = -359.6234116710798
Optimization restart 50/200, f = -359.6234116595541
Optimization re

Optimization restart 190/200, f = -359.623411667635
Optimization restart 191/200, f = -359.6234116724388
Optimization restart 192/200, f = 41.69592581877748
Optimization restart 193/200, f = -359.62341167164846
Optimization restart 194/200, f = -359.6234116700416
Optimization restart 195/200, f = -359.6234116711003
Optimization restart 196/200, f = -359.6234116724385
Optimization restart 197/200, f = 41.69597830236083
Optimization restart 198/200, f = -359.62341167239174
Optimization restart 199/200, f = -359.6234116724402
Optimization restart 200/200, f = -359.62341167171553


### Evaluate

Evaluate RMSE of each model on our test set of 50 randomly selected points.

In [19]:
pred_Y, pred_Y_variance = emukit_model_ed.predict(test_X)
mse_ed = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Model Variance RMSE: ', mse_ed)

Experimental Design w/ Model Variance RMSE:  0.03637841353711442


In [20]:
pred_Y, pred_Y_variance = emukit_model_ird.predict(test_X)
mse_ird = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Experimental Design w/ Integrated Variance Reduction RMSE: ', mse_ird)

Experimental Design w/ Integrated Variance Reduction RMSE:  0.030578350016321143


In [21]:
pred_Y, pred_Y_variance = emukit_model_rnd.predict(test_X)
mse_rnd = np.sqrt(np.mean((pred_Y-test_Y)**2))
print('Random GP RMSE: ', mse_rnd)

Random GP RMSE:  0.027845878832201847


In [26]:
p = 1 - (mse_ed/mse_rnd)
f'Experimental Design w/ Model Variance is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Model Variance is -30.642% better than training on random points.'

In [27]:
p = 1 - (mse_ird/mse_rnd)
f'Experimental Design w/ Integrated Variance Reduction is {p*100:.3f}% better than training on random points.'

'Experimental Design w/ Integrated Variance Reduction is -9.813% better than training on random points.'

### Save Models

In [28]:
with open(f'experimental_design/models/experimental_design_20_init_points_250_loops_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_ed, f)
        
with open(f'experimental_design/models/270_random_points_supervised_GP_timeloss.pkl', "wb") as f:
     pickle.dump(emukit_model_rnd, f)