In [1]:
%cd ..

/Users/Matteo/PycharmProjects/TrafficEmu


# Bayesian optimization: finding the minimum emission

In this notebook we will performing bayesian optimization on the emulator trained on our sumo simulation. We are interested in identifying the parameters which enable us to obtain the minimum travel time. Our emulator is a gaussian process with an **rbf** kernel.


## Imports

In [2]:
import pickle
import numpy as np
import emukit as ek
import GPy

from emukit.model_wrappers import GPyModelWrapper
from emukit.core.initial_designs import RandomDesign
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.bayesian_optimization.loops import BayesianOptimizationLoop

from experimental_design import config
from sumo_grid_simulation.grid_simulation import Simulator

warning in stationary: failed to import cython module: falling back to numpy
warning in coregionalize: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy


## Simulator

We start by initialising our simulation.

In [3]:
simulator = Simulator(end_time=300)

We then define the two user functions in which we are interested:

In [4]:
def user_function_emissions(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function emissions called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.005
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * 50 / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )
        # average co2 / average route duration
        CO2 = s['CO2']/s['num_emissions_samples']
        # average emissions / average route length
        result.append(CO2/s['duration'])
        i += 1
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

We then load the parameters' space from our configuration file:

In [5]:
gridSize = DiscreteParameter('gridSize', domain=[3, 4, 5, 6, 7, 8, 9, 10])
edgeMaxSpeed = ContinuousParameter('edgeMaxSpeed', min_value=8, max_value=20)  # 28.8 km/h to 72 km/h
numberOfLanes = DiscreteParameter('numberOfLanes', domain=[1, 2, 3])
accel = ContinuousParameter('accel', 1., 3.)

parameter_space = ParameterSpace([gridSize, edgeMaxSpeed, numberOfLanes, accel])
#parameter_space = config.get_parameter_space()

## Emulator

### Rnadomly initialised emulator

The first emulator we are going to analyse is the one that is just initilised with random points

We first sample at random 200 datapoints from the parameter space:

In [6]:
#init_X, init_Y = pickle.load(open('bayesian_optimization/init_points/emissions_200_init_points.pkl', 'rb'))

design = RandomDesign(parameter_space) 
num_init_points = 250
init_X = design.get_samples(num_init_points)
init_Y = user_function_emissions(init_X)

[[10.         14.3941175   3.          2.40989451]
 [ 6.         16.50534565  2.          2.32691315]
 [ 3.          9.48907108  1.          1.31720028]
 [ 7.         18.89699467  2.          1.51799023]
 [ 3.         17.32917171  2.          2.2122406 ]
 [ 5.          9.46855122  1.          2.13461924]
 [ 7.          9.06985734  1.          2.15313339]
 [ 9.         15.68064139  3.          1.78260641]
 [ 3.         16.26846333  1.          1.27120255]
 [ 4.         16.74902719  1.          2.89326729]
 [ 9.         17.14986084  3.          2.45904413]
 [ 9.         12.70028713  3.          2.65184914]
 [ 7.         19.1526701   1.          1.73478691]
 [ 4.         18.58545858  1.          1.06861139]
 [ 4.         10.36490701  3.          1.32492648]
 [ 3.         13.40256781  1.          1.22098735]
 [ 4.         13.67923539  1.          1.58760885]
 [ 7.         12.58067027  1.          2.63925179]
 [ 7.         10.17494264  3.          1.90317068]
 [ 4.         12.47105278  1.  

 Retrying in 1 seconds

Evaluating input: 2 of 250

 Retrying in 1 seconds

Evaluating input: 3 of 250

 Retrying in 1 seconds

Evaluating input: 4 of 250

 Retrying in 1 seconds

Evaluating input: 5 of 250

 Retrying in 1 seconds

Evaluating input: 6 of 250

 Retrying in 1 seconds

Evaluating input: 7 of 250

 Retrying in 1 seconds

Evaluating input: 8 of 250

 Retrying in 1 seconds

Evaluating input: 9 of 250

 Retrying in 1 seconds

Evaluating input: 10 of 250

 Retrying in 1 seconds

Evaluating input: 11 of 250

 Retrying in 1 seconds

Evaluating input: 12 of 250

 Retrying in 1 seconds

Evaluating input: 13 of 250

 Retrying in 1 seconds

Evaluating input: 14 of 250

 Retrying in 1 seconds

Evaluating input: 15 of 250

 Retrying in 1 seconds

Evaluating input: 16 of 250

 Retrying in 1 seconds

Evaluating input: 17 of 250

 Retrying in 1 seconds

Evaluating input: 18 of 250

 Retrying in 1 seconds

Evaluating input: 19 of 250

 Retrying in 1 seconds

Evaluating input: 20 of 250

 

 Retrying in 1 seconds

Evaluating input: 156 of 250

 Retrying in 1 seconds

Evaluating input: 157 of 250

 Retrying in 1 seconds

Evaluating input: 158 of 250

 Retrying in 1 seconds

Evaluating input: 159 of 250

 Retrying in 1 seconds

Evaluating input: 160 of 250

 Retrying in 1 seconds

Evaluating input: 161 of 250

 Retrying in 1 seconds

Evaluating input: 162 of 250

 Retrying in 1 seconds

Evaluating input: 163 of 250

 Retrying in 1 seconds

Evaluating input: 164 of 250

 Retrying in 1 seconds

Evaluating input: 165 of 250

 Retrying in 1 seconds

Evaluating input: 166 of 250

 Retrying in 1 seconds

Evaluating input: 167 of 250

 Retrying in 1 seconds

Evaluating input: 168 of 250

 Retrying in 1 seconds

Evaluating input: 169 of 250

 Retrying in 1 seconds

Evaluating input: 170 of 250

 Retrying in 1 seconds

Evaluating input: 171 of 250

 Retrying in 1 seconds

Evaluating input: 172 of 250

 Retrying in 1 seconds

Evaluating input: 173 of 250

 Retrying in 1 seconds

Eval

To then fit a GP to these points

In [7]:
emulator = GPy.models.GPRegression(init_X, init_Y, noise_var=1e-10)
emukit_model_random_init = GPyModelWrapper(emulator, n_restarts=5)
emukit_model_random_init.optimize()

Optimization restart 1/5, f = 1119.4230495971256


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = 1042.0469196786814
Optimization restart 3/5, f = 1042.0469196080724
Optimization restart 4/5, f = 1042.0469196074794
Optimization restart 5/5, f = 1042.0469196074744


### Experimentally designed emulator

We also load the emulator obtained during experimental design:

In [8]:
emukit_model_exp_design = pickle.load(open('experimental_design/models/model_variance_20_init_points_250_loops_co2.pkl', 'rb'))

## Bayesian optimisation

We now run bayesian optimisation on the emulators

In [9]:
n_iter_bo = 40

### Acquisition functions

In [10]:
acquisition_random_init = ExpectedImprovement(emukit_model_random_init)

In [11]:
acquisition_exp_design = ExpectedImprovement(emukit_model_exp_design)

### Optimisation loop

In [ ]:
bo_random_init = BayesianOptimizationLoop(parameter_space, emukit_model_random_init, acquisition=acquisition_random_init)
bo_random_init.run_loop(user_function_emissions, n_iter_bo)

Optimization restart 1/5, f = 1042.0469196074744


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1042.0469196074987
Optimization restart 3/5, f = 1042.38086665382
Optimization restart 4/5, f = 1042.0469196942913
Optimization restart 5/5, f = 1042.0469196138695
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1046.0170961130543
Optimization restart 2/5, f = 1046.0110271343656
Optimization restart 3/5, f = 1046.011027139721
Optimization restart 4/5, f = 1046.0110271630924
Optimization restart 5/5, f = 1046.0110281846978
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1049.7047666850483
Optimization restart 2/5, f = 1049.704310499683
Optimization restart 3/5, f = 1049.704310632337
Optimization restart 4/5, f = 1049.7043104770073
Optimization restart 5/5, f = 1049.7043104783534
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1053.3106312257953
Optimization restart 2/5, f = 1053.3105207907136
Optimization restart 3/5, f = 1053.3105206535888
Optimization restart 4/5, f = 1053.3105206544485
Optimization restart 5/5, f = 1053.3105206541427
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1056.8724458885588
Optimization restart 2/5, f = 1056.8724020944462
Optimization restart 3/5, f = 1056.8724020848813
Optimization restart 4/5, f = 1056.872402083966
Optimization restart 5/5, f = 1056.872402084888
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1060.4068103653813
Optimization restart 2/5, f = 1060.4067874611792
Optimization restart 3/5, f = 1060.406787461106
Optimization restart 4/5, f = 1060.4067874610857
Optimization restart 5/5, f = 1060.4067874610841
[[10.  8.  3.  3.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1064.2169226885774
Optimization restart 2/5, f = 1064.216468978536


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = 1207.0847621612947
Optimization restart 4/5, f = 1064.2164690204288
Optimization restart 5/5, f = 1064.2164689415233
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1067.7304096210205
Optimization restart 2/5, f = 1067.7303948402096
Optimization restart 3/5, f = 1067.7303948403198
Optimization restart 4/5, f = 1067.7303948572358
Optimization restart 5/5, f = 1067.730394840578
[[10.  8.  3.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1071.364325490987
Optimization restart 2/5, f = 1071.364324334332
Optimization restart 3/5, f = 1071.3643243343613
Optimization restart 4/5, f = 1071.364326703809
Optimization restart 5/5, f = 1071.364324334304
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1074.860896611171
Optimization restart 2/5, f = 1074.8608878140926


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = 1074.860887813718
Optimization restart 4/5, f = 1074.8608878548002
Optimization restart 5/5, f = 1074.8608878137172
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1078.3463913366008
Optimization restart 2/5, f = 1078.3463846257978
Optimization restart 3/5, f = 1078.3463847281646
Optimization restart 4/5, f = 1076.3107787942802


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1078.663280741122
[[7. 8. 1. 1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1080.8629727571981
Optimization restart 2/5, f = 1082.0460136847216
Optimization restart 3/5, f = 1082.0460136839079
Optimization restart 4/5, f = 1082.0460136838697
Optimization restart 5/5, f = 1082.0460147228296
[[3. 8. 3. 1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1085.9102781952774
Optimization restart 2/5, f = 1085.9768766786356
Optimization restart 3/5, f = 1085.976876678444
Optimization restart 4/5, f = 1085.9768766812322
Optimization restart 5/5, f = 1085.9768766823272
[[10. 20.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1090.895391304995
Optimization restart 2/5, f = 1089.8567342551003
Optimization restart 3/5, f = 1089.8567342557458
Optimization restart 4/5, f = 1089.8567342638655
Optimization restart 5/5, f = 1089.8567342556626
[[10.  8.  1.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1093.3279311536749
Optimization restart 2/5, f = 1093.327927034105
Optimization restart 3/5, f = 1093.3279270308924
Optimization restart 4/5, f = 1093.4943617422994
Optimization restart 5/5, f = 1093.3279270320445
[[10.  8.  3.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1096.8868386097065
Optimization restart 2/5, f = 1096.8868393124167
Optimization restart 3/5, f = 1096.8868385032536


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1335.445915084038
Optimization restart 5/5, f = 1096.8868386008996
[[10.          8.04578304  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1100.3493727024472
Optimization restart 2/5, f = 1100.3493670025453
Optimization restart 3/5, f = 1100.3493670890562
Optimization restart 4/5, f = 1100.3493669914442
Optimization restart 5/5, f = 1100.3493669921013
[[10.          8.10915856  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1103.8103569192028
Optimization restart 2/5, f = 1103.8103493316253
Optimization restart 3/5, f = 1103.810349332122
Optimization restart 4/5, f = 1103.8103493322124
Optimization restart 5/5, f = 1103.8103493315207
[[10.          8.15950989  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1107.272029321061
Optimization restart 2/5, f = 1107.272020985902
Optimization restart 3/5, f = 1107.2720209863028
Optimization restart 4/5, f = 1107.2720209860581
Optimization restart 5/5, f = 1107.2720209857014
[[10.          8.19620415  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1110.7300702771
Optimization restart 2/5, f = 1110.7300629337715
Optimization restart 3/5, f = 1110.7300629105036
Optimization restart 4/5, f = 1110.730062885108
Optimization restart 5/5, f = 1110.7300628852654
[[10.          8.22100186  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1114.1832490270829
Optimization restart 2/5, f = 1114.1832425546054
Optimization restart 3/5, f = 1114.1832425549565
Optimization restart 4/5, f = 1114.1832425536695
Optimization restart 5/5, f = 1114.1832425536609
[[10.  8.  3.  3.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1117.793598270533
Optimization restart 2/5, f = 1117.793597934358
Optimization restart 3/5, f = 1117.7935979342506
Optimization restart 4/5, f = 1117.7935979566669
Optimization restart 5/5, f = 1117.7935979344622
[[10.          8.22949836  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1121.2398476552426
Optimization restart 2/5, f = 1121.2398419113692
Optimization restart 3/5, f = 1121.2398414102663
Optimization restart 4/5, f = 1121.2398414091099
Optimization restart 5/5, f = 1121.2398414078566
[[10.          8.24563535  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1124.6812089054222
Optimization restart 2/5, f = 1124.6812032722603
Optimization restart 3/5, f = 1124.6812032379744
Optimization restart 4/5, f = 1124.6812032377543
Optimization restart 5/5, f = 1124.6812032408557
[[10.          8.25788175  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1128.1176504838525
Optimization restart 2/5, f = 1128.1176453018122
Optimization restart 3/5, f = 1128.117645301794
Optimization restart 4/5, f = 1128.1176454418585
Optimization restart 5/5, f = 1128.117645301811
[[10.          8.26764549  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1131.5594750152716
Optimization restart 2/5, f = 1131.5594687851149
Optimization restart 3/5, f = 1131.5594688129604
Optimization restart 4/5, f = 1131.5594687866726
Optimization restart 5/5, f = 1131.5594687867722
[[10.          8.27296718  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1134.9958637569725
Optimization restart 2/5, f = 1135.2449879499318
Optimization restart 3/5, f = 1134.9958578994429
Optimization restart 4/5, f = 1134.995857983623
Optimization restart 5/5, f = 1134.995857913545
[[10.  8.  3.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1138.4971396689302
Optimization restart 2/5, f = 1138.4971398295252
Optimization restart 3/5, f = 1138.4971396136348
Optimization restart 4/5, f = 1138.49713961362
Optimization restart 5/5, f = 1138.4971397128256
[[10.          8.27771725  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1141.9237782367338
Optimization restart 2/5, f = 1141.9237731272262
Optimization restart 3/5, f = 1141.9237731272244
Optimization restart 4/5, f = 1141.9237731272865
Optimization restart 5/5, f = 1141.923773127402
[[10.  8.  3.  3.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1145.4555604997156
Optimization restart 2/5, f = 1145.4555590445414
Optimization restart 3/5, f = 1145.4555590040031
Optimization restart 4/5, f = 1145.455559004046
Optimization restart 5/5, f = 1145.4555590039445
[[10.          8.28943557  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1148.8814587535799
Optimization restart 2/5, f = 1148.88145313553
Optimization restart 3/5, f = 1148.8814531469418
Optimization restart 4/5, f = 1148.8814531355713
Optimization restart 5/5, f = 1148.8814531369462
[[10.          8.28981206  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1152.3026591409343
Optimization restart 2/5, f = 1152.3026536332354
Optimization restart 3/5, f = 1152.3026536335356
Optimization restart 4/5, f = 1152.3026536321881
Optimization restart 5/5, f = 1152.3026536538453
[[10.          8.29112603  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1155.7194395163606
Optimization restart 2/5, f = 1155.7194341273575
Optimization restart 3/5, f = 1155.7194341232412
Optimization restart 4/5, f = 1155.719434124482
Optimization restart 5/5, f = 1155.7194341230074
[[10.  8.  3.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1159.1880106042188
Optimization restart 2/5, f = 1159.1880107540394
Optimization restart 3/5, f = 1159.1880102503499
Optimization restart 4/5, f = 1159.188010278495
Optimization restart 5/5, f = 1159.1880102495516
[[10.          8.29577351  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1162.5953328364749
Optimization restart 2/5, f = 1162.5953280013928
Optimization restart 3/5, f = 1162.5953280020835
Optimization restart 4/5, f = 1162.5953280013873
Optimization restart 5/5, f = 1162.5953280033364
[[10.          8.29809177  1.          1.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1165.9988909600495
Optimization restart 2/5, f = 1165.9988861589777
Optimization restart 3/5, f = 1165.9988861576335
Optimization restart 4/5, f = 1165.9988867266168
Optimization restart 5/5, f = 1165.9988861715567
[[10.  8.  3.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1169.4471482019808
Optimization restart 2/5, f = 1169.4471474534537
Optimization restart 3/5, f = 1169.447147453525
Optimization restart 4/5, f = 1169.4471474534994
Optimization restart 5/5, f = 1169.4471474534776
[[10.  8.  3.  1.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1172.882864330274
Optimization restart 2/5, f = 1172.8828632264867
Optimization restart 3/5, f = 1172.8828632265713
Optimization restart 4/5, f = 1172.8828632264003


In [ ]:
bo_exp_design = BayesianOptimizationLoop(parameter_space, emukit_model_exp_design, acquisition=acquisition_exp_design)
bo_exp_design.run_loop(user_function_emissions, n_iter_bo)

## Results

### Results on the random initialised emulator

In [ ]:
results_random_init = bo_random_init.get_results()

In [ ]:
results_random_init.minimum_location

In [ ]:
results_random_init.minimum_value*100

### Results on the experimentally designed emulator

In [ ]:
results_exp_design = bo_exp_design.get_results()

In [ ]:
results_exp_design.minimum_location

In [ ]:
results_exp_design.minimum_value*100