In [1]:
%cd ..

/Users/Matteo/PycharmProjects/TrafficEmu


# Bayesian optimization: finding the minimum emission

In this notebook we will performing bayesian optimization on the emulator trained on our sumo simulation. We are interested in identifying the parameters which enable us to obtain the minimum travel time. Our emulator is a gaussian process with an **rbf** kernel.


## Imports

In [30]:
import pickle
import numpy as np
import emukit as ek
import GPy
import pandas as pd

from emukit.model_wrappers import GPyModelWrapper
from emukit.core.initial_designs import RandomDesign
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.bayesian_optimization.loops import BayesianOptimizationLoop

from experimental_design import config
from sumo_grid_simulation.grid_simulation import Simulator

## Simulator

We start by initialising our simulation.

In [3]:
simulator = Simulator(end_time=300)

We then define the two user functions in which we are interested:

In [4]:
def user_function_emissions(X):
    """  X = inputs - emukit doesnt pass named args, just an NxM ndarray, N is the number of points to evaluate, M is the number of parameters per each point """
    result = []
    i = 0
    
    print(X)
    print(f'\nUser function emissions called with {X.shape[0]} inputs to simulate')

    
    for gridSize, edgeMaxSpeed, maxSpeed, edgeLength, numLanes, accel in X:
        print(f'\nEvaluating input: {i+1} of {X.shape[0]}\n')
        
        alpha = 0.005
        max_number_of_vehicles = ((gridSize - 1) * gridSize * 2 + 4 * gridSize) * edgeLength / 5
        period = 300/(max_number_of_vehicles * alpha)
        
        s = simulator.simulate(
            gridSize      = int(gridSize),
            edgeMaxSpeed  = edgeMaxSpeed,
            maxSpeed      = maxSpeed,
            edgeLength    = edgeLength,
            numberOfLanes = int(numLanes),
            accel         = accel,
            trips_generator_period = period
        )

        CO2 = s['CO2']/s['num_emissions_samples']
        result.append(CO2/s['duration'])
        print(f'\nOutput {result[-1]}\n')
        i += 1
        
    # expand dims is essential or the acquition function breaks
    return np.expand_dims(np.array(result), 1)  

We then load the parameters' space from our configuration file:

In [5]:
parameter_space = config.get_parameter_space()

## Emulator

### Rnadomly initialised emulator

The first emulator we are going to analyse is the one that is just initilised with random points

We first sample at random 200 datapoints from the parameter space:

In [6]:
init_X, init_Y = pickle.load(open('bayesian_optimization/init_points/270_init_points_emissions.pkl', 'rb'))

'''
design = RandomDesign(parameter_space)
num_init_points = 270
init_X = design.get_samples(num_init_points)
init_Y = user_function_emissions(init_X)
init_points = init_X, init_Y
with open(f'bayesian_optimization/init_points/{num_init_points}_init_points_emissions.pkl', "wb") as f:
     pickle.dump(init_points, f)
'''

[[ 3.         13.45629089 12.62279017 31.88002303  3.          3.29806164]
 [11.         24.84758826 10.4733427  44.62352234  1.          4.43758246]
 [15.         14.38873192 16.87062442 46.33469437  1.          3.26889924]
 ...
 [10.         15.45422557 22.5955133  30.3372117   2.          4.18152089]
 [ 9.         18.66407347 22.65891601 41.91541962  3.          2.96242485]
 [15.         19.70927053 23.73218336 65.60162907  3.          3.01234321]]

User function emissions called with 270 inputs to simulate

Evaluating input: 1 of 270

 Retrying in 1 seconds

Output 320.8279111111111


Evaluating input: 2 of 270

 Retrying in 1 seconds

Output 51.16088719744498


Evaluating input: 3 of 270

 Retrying in 1 seconds

Output 62.926845939696406


Evaluating input: 4 of 270

 Retrying in 1 seconds

Output 81.64658838900145


Evaluating input: 5 of 270

 Retrying in 1 seconds

Output 39.136407752497654


Evaluating input: 6 of 270

 Retrying in 1 seconds

Output 67.52764370413911


Evaluat


Output 76.86669505821557


Evaluating input: 97 of 270

 Retrying in 1 seconds

Output 12.107707399503429


Evaluating input: 98 of 270

 Retrying in 1 seconds

Output 114.73066666666669


Evaluating input: 99 of 270

 Retrying in 1 seconds

Output 135.0811788021597


Evaluating input: 100 of 270

 Retrying in 1 seconds

Output 66.39930346527107


Evaluating input: 101 of 270

 Retrying in 1 seconds

Output 52.890672810146675


Evaluating input: 102 of 270

 Retrying in 1 seconds

Output 63.65292845338777


Evaluating input: 103 of 270

 Retrying in 1 seconds

Output 28.59618503546401


Evaluating input: 104 of 270

 Retrying in 1 seconds

Output 98.79417517006797


Evaluating input: 105 of 270

 Retrying in 1 seconds

Output 144.5017336498146


Evaluating input: 106 of 270

 Retrying in 1 seconds

Output 132.38868184134532


Evaluating input: 107 of 270

 Retrying in 1 seconds

Output 65.40056498428875


Evaluating input: 108 of 270

 Retrying in 1 seconds

Output 66.4098255669482





Output 15.773382453007859


Evaluating input: 198 of 270

 Retrying in 1 seconds

Output 28.127017978928194


Evaluating input: 199 of 270

 Retrying in 1 seconds

Output 40.504534293552815


Evaluating input: 200 of 270

 Retrying in 1 seconds

Output 78.34497676248316


Evaluating input: 201 of 270

 Retrying in 1 seconds

Output 142.066853111615


Evaluating input: 202 of 270

 Retrying in 1 seconds

Output 163.72343750000002


Evaluating input: 203 of 270

 Retrying in 1 seconds

Output 58.623671348035344


Evaluating input: 204 of 270

 Retrying in 1 seconds

Output 119.90218311427938


Evaluating input: 205 of 270

 Retrying in 1 seconds

Output 26.09636080147253


Evaluating input: 206 of 270

 Retrying in 1 seconds

Output 35.56760484301561


Evaluating input: 207 of 270

 Retrying in 1 seconds

Output 63.22352032136104


Evaluating input: 208 of 270

 Retrying in 1 seconds

Output 146.82328656929357


Evaluating input: 209 of 270

 Retrying in 1 seconds

Output 96.83490981555

To then fit a GP to these points

In [7]:
emulator = GPy.models.GPRegression(init_X, init_Y, noise_var=1e-10)
emukit_model_random_init = GPyModelWrapper(emulator, n_restarts=5)
emukit_model_random_init.optimize()

Optimization restart 1/5, f = 1297.6948600888115
Optimization restart 2/5, f = 1201.127032490439


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = 1202.2664897844352
Optimization restart 4/5, f = 1201.127032492374
Optimization restart 5/5, f = 1201.1270324898426


### Experimentally designed emulator with model variance

We also load the emulator obtained during experimental design:

In [8]:
emukit_model_variance = pickle.load(open('experimental_design/models/model_variance_20_init_points_250_loops_co2.pkl', 'rb'))

### Experimentally designed emulator with integrated variance reduction

We also load the emulator obtained during experimental design:

In [9]:
emukit_model_integrated_variance = pickle.load(open('experimental_design/models/integrated_variance_reduction_20_init_points_250_loops_co2.pkl', 'rb'))

## Bayesian optimisation

We now run bayesian optimisation on the emulators

In [10]:
n_iter_bo = 40

### Acquisition functions

In [11]:
acquisition_random_init = ExpectedImprovement(emukit_model_random_init)

In [12]:
acquisition_model_variance = ExpectedImprovement(emukit_model_variance)

In [13]:
acquisition_integrated_variance = ExpectedImprovement(emukit_model_integrated_variance)

### Optimisation loop

In [14]:
bo_random_init = BayesianOptimizationLoop(parameter_space, emukit_model_random_init, acquisition=acquisition_random_init)
bo_random_init.run_loop(user_function_emissions, n_iter_bo)

Optimization restart 1/5, f = 1201.1270324898426


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1201.1270324923057
Optimization restart 3/5, f = 1201.1270324894372
Optimization restart 4/5, f = 1201.1270324953118
Optimization restart 5/5, f = 1201.1270328608696
[[12. 25.  5. 70.  3.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.876725628276361

Optimization restart 1/5, f = 1206.0713284704955


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = 1444.982267500398
Optimization restart 3/5, f = 1206.0575002271908
Optimization restart 4/5, f = 1206.0575003027875
Optimization restart 5/5, f = 1206.0575002306584
[[12.         25.          5.         44.51789748  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 13.27183348369983

Optimization restart 1/5, f = 1211.4398420933435


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1211.3613414956467
Optimization restart 3/5, f = 1211.3613414936242


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1463.6592085353045


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = 1211.3613414932868
[[ 7.  25.   5.  70.   3.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 14.494902074248596

Optimization restart 1/5, f = 1215.8121302261306


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1215.8115750071809
Optimization restart 3/5, f = 1215.8115785246557
Optimization restart 4/5, f = 1609.2823466552518
Optimization restart 5/5, f = 1215.8115750178872
[[13.          8.         27.         54.79322106  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 19.59188283790451



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1222.6046506015846
Optimization restart 2/5, f = 1222.4562368144416
Optimization restart 3/5, f = 1222.456236816483
Optimization restart 4/5, f = 1222.4562372591977
Optimization restart 5/5, f = 1222.456236815869
[[11.          8.          5.         39.16935341  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 14.644159562536315

Optimization restart 1/5, f = 1227.0351192331486


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1227.026111157883
Optimization restart 3/5, f = 1227.0261112662802
Optimization restart 4/5, f = 1227.0261111425493


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1441.9278083831223
[[20.         25.          5.         59.28767525  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.44264449272756

Optimization restart 1/5, f = 1231.1891742957328


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1625.5013450683514
Optimization restart 3/5, f = 1231.1891682635162
Optimization restart 4/5, f = 1231.189168267695
Optimization restart 5/5, f = 1231.1891682632854
[[20.         14.31106179  5.         60.84915267  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.094976924222027

Optimization restart 1/5, f = 1235.1906326368733


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1235.1903888829393
Optimization restart 3/5, f = 1235.190388836226
Optimization restart 4/5, f = 1235.1903888356042
Optimization restart 5/5, f = 1235.1903888390661
[[11.         25.          5.         61.92517542  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.840621531348635

Optimization restart 1/5, f = 1239.209175055661


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1239.2088221177892
Optimization restart 3/5, f = 1239.2088220864227
Optimization restart 4/5, f = 1239.2088220852763
Optimization restart 5/5, f = 1239.2088220973674
[[18.        25.         5.        40.3953179  3.         5.       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 11.115161377366693

Optimization restart 1/5, f = 1243.256706316787


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1243.256228463747
Optimization restart 3/5, f = 1243.2562284634366
Optimization restart 4/5, f = 1243.2562284625817
Optimization restart 5/5, f = 1243.2562284621706
[[20.         16.55009605  5.         61.49898997  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.378279910544435

Optimization restart 1/5, f = 1247.1282516768176


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1647.0655947440312
Optimization restart 3/5, f = 1247.128183016989
Optimization restart 4/5, f = 1247.1281830193261
Optimization restart 5/5, f = 1247.1281830062317
[[14.         25.          5.         64.07392662  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.005009566585317

Optimization restart 1/5, f = 1250.9918216891087


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1250.9917599852615
Optimization restart 3/5, f = 1250.9917582535397
Optimization restart 4/5, f = 1250.9917584221341
Optimization restart 5/5, f = 1250.9917582589615
[[15.        17.5674747  5.        62.7905177  3.         5.       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.997992921861625

Optimization restart 1/5, f = 1254.8029998646873


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1254.802761872947
Optimization restart 3/5, f = 1254.8027612949863
Optimization restart 4/5, f = 1254.8027615945964


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1256.7862298068185
[[15.         18.53272921  5.         62.48416274  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.268756967581261

Optimization restart 1/5, f = 1258.5553061458654


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1258.5550802891296
Optimization restart 3/5, f = 1258.5550802871958
Optimization restart 4/5, f = 1258.5550802871012
Optimization restart 5/5, f = 1258.5550803719193
[[20.          8.          5.         62.99660123  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.201480140478191



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1262.4896298461222
Optimization restart 2/5, f = 1262.4896297039454
Optimization restart 3/5, f = 1262.4896297022883
Optimization restart 4/5, f = 1262.4896297018581
Optimization restart 5/5, f = 1262.4896297809032
[[11.          8.         27.         63.63771091  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 19.08554390796357



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1267.0750970195638
Optimization restart 2/5, f = 1267.0669274682673
Optimization restart 3/5, f = 1267.0669274858517
Optimization restart 4/5, f = 1267.0669275261632
Optimization restart 5/5, f = 1267.06692750029
[[14.         25.          5.         62.66313201  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.218262194106615

Optimization restart 1/5, f = 1270.8277984801532


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1270.8277305024542
Optimization restart 3/5, f = 1270.8295138001793
Optimization restart 4/5, f = 1679.3731334495917


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1479.0341417453237
[[20.         16.60343671  5.         56.34970293  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.9090926531826335

Optimization restart 1/5, f = 1274.590776697344


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1274.5904128711322
Optimization restart 3/5, f = 1274.5904126716212
Optimization restart 4/5, f = 1274.5904126700789
Optimization restart 5/5, f = 1274.5904126703317
[[10.  8.  5. 70.  3.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 11.0431590477371

Optimization restart 1/5, f = 1278.6956679741722


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1278.6956487681468
Optimization restart 3/5, f = 1278.6956487681196
Optimization restart 4/5, f = 1278.6956487709008
Optimization restart 5/5, f = 1278.6956487694151
[[12.         25.          5.         43.27814302  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 16.24360047168202



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1282.7683768208879
Optimization restart 2/5, f = 1282.75879487561
Optimization restart 3/5, f = 1282.7587948769062
Optimization restart 4/5, f = 1282.7587949077074
Optimization restart 5/5, f = 1282.758794890582
[[17.   8.  27.  30.   1.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 27.19553973200424

Optimization restart 1/5, f = 1287.4446360703496


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1287.4425481282412
Optimization restart 3/5, f = 1287.4425481761627
Optimization restart 4/5, f = 1287.4425481274359
Optimization restart 5/5, f = 1287.4425482018687
[[20.         17.18495692  5.         57.64809268  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.8943527500123905



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1291.1789364488607
Optimization restart 2/5, f = 1291.1789259026416
Optimization restart 3/5, f = 1291.178925905499
Optimization restart 4/5, f = 1291.1789259026316
Optimization restart 5/5, f = 1706.2962667308848
[[14.         16.64657803  5.         38.77240886  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 12.89454299217853

Optimization restart 1/5, f = 1295.0990041243376


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1295.0988828755549
Optimization restart 3/5, f = 1295.0988828738882
Optimization restart 4/5, f = 1295.0988829158784


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1494.6662968123944
[[20.         14.93580816  5.         59.79799481  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.591405544310674



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1298.7690165428835
Optimization restart 2/5, f = 1298.7689696307216
Optimization restart 3/5, f = 1298.7689695402112
Optimization restart 4/5, f = 1298.768969540217
Optimization restart 5/5, f = 1298.768969548055
[[15.         17.93311549  5.         61.82988254  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.466743818669427

Optimization restart 1/5, f = 1302.4238804022445


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1302.4238511910128
Optimization restart 3/5, f = 1302.4238488332735
Optimization restart 4/5, f = 1302.423848833544
Optimization restart 5/5, f = 1302.4238494256645
[[13.        25.         5.        63.0957128  3.         5.       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.286900893567584



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1306.1630042026818
Optimization restart 2/5, f = 1306.1628770003272
Optimization restart 3/5, f = 1306.1628769788058
Optimization restart 4/5, f = 1306.1628769792164
Optimization restart 5/5, f = 1306.1628769788106
[[10.         25.          5.         42.90575389  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 17.75940748475096



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1310.134736269659
Optimization restart 2/5, f = 1310.1316874707238
Optimization restart 3/5, f = 1310.1316874795484


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1493.6816097729643
Optimization restart 5/5, f = 1310.1316874706908
[[20.          8.          5.         61.66805086  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.381737021064493



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1313.8826522188788
Optimization restart 2/5, f = 1738.4967101445882
Optimization restart 3/5, f = 1313.8826354455664
Optimization restart 4/5, f = 1313.882648690389
Optimization restart 5/5, f = 1313.8826354643263
[[13.         16.29984986  5.         62.00694892  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.567686855839975



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1317.5656021110672
Optimization restart 2/5, f = 1317.565573232728
Optimization restart 3/5, f = 1317.5655732026116
Optimization restart 4/5, f = 1317.5655783988507
Optimization restart 5/5, f = 1317.5655732029218
[[17.         19.94091923  5.         59.58009451  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.625433710428547



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1321.1753218538358
Optimization restart 2/5, f = 1749.2099828264659
Optimization restart 3/5, f = 1321.175309075468
Optimization restart 4/5, f = 1321.175309414105
Optimization restart 5/5, f = 1321.1753090677767
[[20.         25.          5.         54.96423725  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.2358944559995



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1325.002035007471
Optimization restart 2/5, f = 1325.0020130868481
Optimization restart 3/5, f = 1325.002013098736
Optimization restart 4/5, f = 1325.0020130833855
Optimization restart 5/5, f = 1325.0020130831135
[[20.         16.98550565  5.         57.3782582   1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.9263317781538785



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1328.6273674518307
Optimization restart 2/5, f = 1328.627361463146
Optimization restart 3/5, f = 1328.6273614598153
Optimization restart 4/5, f = 1328.627361435695
Optimization restart 5/5, f = 1328.627361433076
[[12.         25.          5.         63.25888474  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 10.372693338403806



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1332.3188580307256
Optimization restart 2/5, f = 1332.3187736282207
Optimization restart 3/5, f = 1332.3187734947433
Optimization restart 4/5, f = 1332.318773497472
Optimization restart 5/5, f = 1332.3187734934818
[[11.        25.         5.        64.1825664  1.         1.5      ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.723518116304877



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1336.0433111169914
Optimization restart 2/5, f = 1336.0432960648618
Optimization restart 3/5, f = 1336.043296039424
Optimization restart 4/5, f = 1336.0432960394355
Optimization restart 5/5, f = 1336.0432960523476
[[20.  8.  5. 70.  1.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.54770372540081



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1340.0212375469541
Optimization restart 2/5, f = 1340.0212171970418
Optimization restart 3/5, f = 1340.021212493585


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = 1340.0212124270467
Optimization restart 5/5, f = 1340.0212124420214
[[16.  8.  5. 30.  1.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 16.38893232319484



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1344.157370059775
Optimization restart 2/5, f = 1344.1572450238145
Optimization restart 3/5, f = 1344.1572444350952
Optimization restart 4/5, f = 1344.1572444314666
Optimization restart 5/5, f = 1344.1572445216798
[[20.         20.67146785  5.         45.48716866  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.865207933424728

Optimization restart 1/5, f = 1347.9113908341162


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1347.9111032615667
Optimization restart 3/5, f = 1347.9111032464064
Optimization restart 4/5, f = 1347.911103796466
Optimization restart 5/5, f = 1347.9111061109265
[[20.          8.         10.46298121 70.          1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 12.26377149818613



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1351.7708355571672
Optimization restart 2/5, f = 1351.7707723570004
Optimization restart 3/5, f = 1351.7707723402705
Optimization restart 4/5, f = 1351.7707723350384
Optimization restart 5/5, f = 1351.943060228462
[[ 9.          8.          5.         40.01293234  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 16.421538581952657

Optimization restart 1/5, f = 1355.7502177250879


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1355.7489764101292


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = 1621.0380777339115
Optimization restart 4/5, f = 1355.7489772792687
Optimization restart 5/5, f = 1355.748976448252
[[15.         17.03589328  5.         61.26840156  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.559185045990194



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1359.3319011597266
Optimization restart 2/5, f = 1359.3318803524821
Optimization restart 3/5, f = 1359.3318803344052
Optimization restart 4/5, f = 1359.3318803286124
Optimization restart 5/5, f = 1359.3318803529019
[[20.   8.   5.  70.   3.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.952162774388234

Optimization restart 1/5, f = 1363.46097438045


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1363.460189392102
Optimization restart 3/5, f = 1363.4601785180737
Optimization restart 4/5, f = 1363.4601785220473
Optimization restart 5/5, f = 1363.4601785345094


In [15]:
bo_model_variance = BayesianOptimizationLoop(parameter_space, emukit_model_variance, acquisition=acquisition_model_variance)
bo_model_variance.run_loop(user_function_emissions, n_iter_bo)

Optimization restart 1/5, f = 1299.81783983801
Optimization restart 2/5, f = 1299.8178398382338
Optimization restart 3/5, f = 1342.8604332834736
Optimization restart 4/5, f = 1299.8178402451185
Optimization restart 5/5, f = 1299.817839934829
[[20.         14.40071822  5.         61.21447956  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.309442696463182



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1303.6917234756843
Optimization restart 2/5, f = 1631.0258018633267
Optimization restart 3/5, f = 1303.6916963765552
Optimization restart 4/5, f = 1303.6916963765477
Optimization restart 5/5, f = 1303.6916963815688
[[20.         25.          5.         64.32342619  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.954431324805468

Optimization restart 1/5, f = 1307.5551846858834


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1350.2615632163324
Optimization restart 3/5, f = 1307.5551485085673
Optimization restart 4/5, f = 1307.555152236819


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = 1307.5551485190801
[[20.         25.          5.         64.30764964  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.948127021449078

Optimization restart 1/5, f = 1311.3199402444295


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1311.3198920734596


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = 1311.3198920734214
Optimization restart 4/5, f = 1311.319892074506
Optimization restart 5/5, f = 1347.5671058271366
[[20.          8.          5.         56.16411779  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.026805427974513



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1315.1648521421366
Optimization restart 2/5, f = 1351.1153547418198
Optimization restart 3/5, f = 1351.1153538356575
Optimization restart 4/5, f = 1315.164834179326


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1572.187923024962
[[13.         25.          5.         66.60312209  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.02690783678036

Optimization restart 1/5, f = 1318.976052944919


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = 1318.9759940907481
Optimization restart 3/5, f = 1680.6615781218607
Optimization restart 4/5, f = 1354.5856356250385
Optimization restart 5/5, f = 1318.9759940727106
[[20.         15.85002576  5.         61.29847157  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.288956989850962

Optimization restart 1/5, f = 1322.7215901556501


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1322.7215686649297
Optimization restart 3/5, f = 1356.7324034425878
Optimization restart 4/5, f = 1322.7215769857967
Optimization restart 5/5, f = 1356.7324040092954
[[20.         15.49419318  5.         61.12674261  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.335967598087921

Optimization restart 1/5, f = 1326.419667542289


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1356.7055675805757
Optimization restart 3/5, f = 1356.705658615683
Optimization restart 4/5, f = 1356.7056584862696
Optimization restart 5/5, f = 1326.4196222765588
[[20.          8.          5.         53.88514498  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.330423855054621

Optimization restart 1/5, f = 1330.1631806050245


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1358.6185329092518
Optimization restart 3/5, f = 1358.6186213667042
Optimization restart 4/5, f = 1358.618620309477
Optimization restart 5/5, f = 1330.1631644589033
[[20.         16.62868048  5.         62.61586572  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.161136422719933

Optimization restart 1/5, f = 1333.8287681768247


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1359.1011765357637
Optimization restart 3/5, f = 1359.10122857123
Optimization restart 4/5, f = 1359.1012672643603


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1451.8515046190737
[[20.         21.90940338  5.         65.52219653  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.405830481931851



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1337.537846062092
Optimization restart 2/5, f = 1362.3250460678996
Optimization restart 3/5, f = 1337.537759768789
Optimization restart 4/5, f = 1362.3249541959879
Optimization restart 5/5, f = 1362.3248632313764
[[14.         22.47855442  5.         38.98371942  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 14.863956849000411



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1341.5163374914096
Optimization restart 2/5, f = 1365.8900866241518
Optimization restart 3/5, f = 1341.516337487213
Optimization restart 4/5, f = 1365.889904760145
Optimization restart 5/5, f = 1365.889913433246
[[12.       25.        5.       65.633152  1.        5.      ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.029359622331762



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1345.244798086293
Optimization restart 2/5, f = 1345.2447201725447
Optimization restart 3/5, f = 1345.2447201728467
Optimization restart 4/5, f = 1345.2447201840969
Optimization restart 5/5, f = 1367.6789252061867
[[20.         15.59245448  5.         57.30436458  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.823685404316464



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1348.9018907189336
Optimization restart 2/5, f = 1348.9018841454917
Optimization restart 3/5, f = 1369.6141821492945
Optimization restart 4/5, f = 1369.6140805296022
Optimization restart 5/5, f = 1348.9018841413983
[[20.   8.   5.  70.   3.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.952162774388234

Optimization restart 1/5, f = 1352.677116835882


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1352.6770833114101


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = 1352.677056588034
Optimization restart 4/5, f = 1352.6770565987267
Optimization restart 5/5, f = 1361.6692019988527
[[20.         12.56160952  5.         70.          3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.044647309364609

Optimization restart 1/5, f = 1356.3860687521747


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1363.8159247816025
Optimization restart 3/5, f = 1363.8160642685368
Optimization restart 4/5, f = 1363.8164241747272
Optimization restart 5/5, f = 1363.8164242480675
[[20.   8.   5.  70.   1.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.469575516984683

Optimization restart 1/5, f = 1360.1540490498735


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1366.9137341239232
Optimization restart 3/5, f = 1360.153962104225
Optimization restart 4/5, f = 1366.9134603037114
Optimization restart 5/5, f = 1366.9134705077122
[[11.         21.61106137  5.         55.09161644  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 10.365342535015708



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1363.919479578029
Optimization restart 2/5, f = 1363.9194763779499
Optimization restart 3/5, f = 1370.5055345414294
Optimization restart 4/5, f = 1370.5056254981973
Optimization restart 5/5, f = 1370.5054474761873
[[20.         12.50102478  5.         70.          3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.92480416043588



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1367.583165263811


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = 1367.5831406550833
Optimization restart 3/5, f = 1373.0548622144368
Optimization restart 4/5, f = 1373.0546802883962
Optimization restart 5/5, f = 1373.0548621778848
[[20.          8.          5.         52.02659492  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.610336314898712

Optimization restart 1/5, f = 1371.244680098627


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1371.2446533626298
Optimization restart 3/5, f = 1371.2446533626305
Optimization restart 4/5, f = 1371.244653561999
Optimization restart 5/5, f = 1373.8407679596187
[[14. 25.  5. 70.  1.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.059802299171902



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1374.9264987255578


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = 1608.700514766194
Optimization restart 3/5, f = 1376.453545051651
Optimization restart 4/5, f = 1687.8475746097374
Optimization restart 5/5, f = 1374.9264779535984
[[20.         12.32921344  5.         70.          3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.9179948735860295

Optimization restart 1/5, f = 1378.543164971973


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1374.8355563518905
Optimization restart 3/5, f = 1378.543131024635


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1692.7485257235026
Optimization restart 5/5, f = 1374.8354941885066
[[ 9.         24.62761359  5.         37.55395153  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 21.565733552681657



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1384.0255500547305
Optimization restart 2/5, f = 1383.8585607962605
Optimization restart 3/5, f = 1383.858378946909
Optimization restart 4/5, f = 1383.8584336406882
Optimization restart 5/5, f = 1382.3339362647107
[[20.         17.29982295  5.         62.07179371  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.218355865489435

Optimization restart 1/5, f = 1385.9150630040053


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1383.9731714186662
Optimization restart 3/5, f = 1385.9150237064819
Optimization restart 4/5, f = 1385.9150236915777
Optimization restart 5/5, f = 1385.9150236916544
[[18.         25.          5.         42.91849819  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.033007489699376

Optimization restart 1/5, f = 1388.3239910229188


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1388.3215890575782
Optimization restart 3/5, f = 1388.3212253323195


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = 1388.3213162430557
Optimization restart 5/5, f = 1388.3213299524125
[[15.         25.          5.         56.83253968  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.458802495493966



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1392.0347253959535
Optimization restart 2/5, f = 1392.0342967382512
Optimization restart 3/5, f = 1392.0343934853497
Optimization restart 4/5, f = 1393.5780296166904
Optimization restart 5/5, f = 1392.0343868557004
[[15.         12.99372773  5.         65.63719978  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.864016181912105



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1395.4032065960232
Optimization restart 2/5, f = 1395.4027862743633
Optimization restart 3/5, f = 1395.4026953514397


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1401.5492555485766
Optimization restart 5/5, f = 1397.2374393814437
[[11.         16.30155924  5.         30.          1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 17.488921705989526



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1399.4178063324962
Optimization restart 2/5, f = 1401.0862647930574
Optimization restart 3/5, f = 1399.4162756047335
Optimization restart 4/5, f = 1401.0862647897352
Optimization restart 5/5, f = 1399.416379207146
[[20.         25.          5.         50.39521032  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.892747039131971



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1403.2183889789103
Optimization restart 2/5, f = 1403.2180625429733
Optimization restart 3/5, f = 1403.2178517142756
Optimization restart 4/5, f = 1404.843239937982
Optimization restart 5/5, f = 1404.8432397818954
[[ 9.         12.84283716  5.         58.05517596  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 10.682522246423272



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1406.9477090047412
Optimization restart 2/5, f = 1406.947752895106
Optimization restart 3/5, f = 1406.947792781668
Optimization restart 4/5, f = 1406.9476901534035
Optimization restart 5/5, f = 1408.5194442676218
[[10.          8.         25.008789   50.53672731  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 34.26811183431953

Optimization restart 1/5, f = 1411.5836005808555


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1412.9955333631046
Optimization restart 3/5, f = 1411.5796893511729
Optimization restart 4/5, f = 1412.9955333631265


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1691.8301809385036
[[13.         19.32050709  5.         70.          1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.501729452868674



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1414.8105348178615
Optimization restart 2/5, f = 1414.810384573114
Optimization restart 3/5, f = 1416.6368487198579
Optimization restart 4/5, f = 1414.810269272492
Optimization restart 5/5, f = 1416.636899369994
[[20.          8.         24.8223036  55.10528511  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 14.695953073598586

Optimization restart 1/5, f = 1418.7045928780944


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1420.3399571370082
Optimization restart 3/5, f = 1420.3399571355594
Optimization restart 4/5, f = 1420.3399571539164
Optimization restart 5/5, f = 1420.339957135396
[[14.          8.          5.         60.65169638  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.53577413085444

Optimization restart 1/5, f = 1422.2111229945126


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1424.0442370467904
Optimization restart 3/5, f = 1424.0442370467597
Optimization restart 4/5, f = 1424.0442371306606
Optimization restart 5/5, f = 1422.2112003517211
[[15.         12.11830824  5.78816251 69.94394033  3.          1.50400563]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.30238214215197



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1425.2571543558206
Optimization restart 2/5, f = 1425.2573818960323
Optimization restart 3/5, f = 1425.2570357462075
Optimization restart 4/5, f = 1425.2572726822705
Optimization restart 5/5, f = 1425.257108760394
[[20.         13.70693112  5.         70.          1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.54770372540081



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1428.0004240845542
Optimization restart 2/5, f = 1431.2984113131456
Optimization restart 3/5, f = 1431.298411314572
Optimization restart 4/5, f = 1431.2984113198872
Optimization restart 5/5, f = 1431.298411317528
[[20.         8.         5.        62.4601678  1.         5.       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.282054444907506



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1430.9337299689041
Optimization restart 2/5, f = 1434.9655167036312


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 3/5, f = 1430.9339031124246


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 2625.9605934638103
Optimization restart 5/5, f = 1430.9338270492094
[[20.         21.49850243  5.         35.46171617  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 11.362267027207064



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1434.8588226117315
Optimization restart 2/5, f = 1438.6529988004936
Optimization restart 3/5, f = 1434.858573520051
Optimization restart 4/5, f = 1438.6529987583192
Optimization restart 5/5, f = 1434.8586643315418
[[14.          8.         14.35860666 70.          1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 14.552225309300598

Optimization restart 1/5, f = 1438.5025711203107


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1438.5021956770424
Optimization restart 3/5, f = 1438.5020419525008
Optimization restart 4/5, f = 1438.502013763216
Optimization restart 5/5, f = 1442.3460731870255
[[16.          8.         20.56095533 70.          3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 16.151996535065773



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1442.2996197272635
Optimization restart 2/5, f = 1446.0421751429335
Optimization restart 3/5, f = 1442.2996429136385
Optimization restart 4/5, f = 1442.2996430327307
Optimization restart 5/5, f = 1442.2996427177668
[[14.          8.          5.         64.94296831  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.532123387415917



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1445.6012416997537
Optimization restart 2/5, f = 1445.6011459246463
Optimization restart 3/5, f = 1445.6013287869628
Optimization restart 4/5, f = 1445.6012414515712
Optimization restart 5/5, f = 1449.712389537633


In [16]:
bo_integrated_variance = BayesianOptimizationLoop(parameter_space, emukit_model_integrated_variance, acquisition=acquisition_integrated_variance)
bo_integrated_variance.run_loop(user_function_emissions, n_iter_bo)

Optimization restart 1/5, f = 1281.5336113895025
Optimization restart 2/5, f = 1281.5336113959763
Optimization restart 3/5, f = 1281.5336113859976
Optimization restart 4/5, f = 1281.5336113860421
Optimization restart 5/5, f = 1281.5336113861576
[[11.         25.          5.         37.01832727  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 18.396061576246655



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1287.175666539175
Optimization restart 2/5, f = 1287.1625546165722
Optimization restart 3/5, f = 1287.1625544433264
Optimization restart 4/5, f = 1287.1625544475148
Optimization restart 5/5, f = 1287.1625546275231
[[20.          8.          5.         53.90881708  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.378808786874681



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1291.3311815346433


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = 1414.31968479859
Optimization restart 3/5, f = 1291.3311808057856
Optimization restart 4/5, f = 1291.3311808064077
Optimization restart 5/5, f = 1291.3311808056856
[[ 9.  25.   5.  70.   1.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.498267342104846

Optimization restart 1/5, f = 1295.6107197063523


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1295.6090077856645


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = 1300.917045640392
Optimization restart 4/5, f = 1295.6090076216153
Optimization restart 5/5, f = 1296.0469206498638
[[14.         23.90685092  5.         44.24567183  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 12.694911121072698

Optimization restart 1/5, f = 1299.9469407385075


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1299.9462505361823
Optimization restart 3/5, f = 1299.946250535989
Optimization restart 4/5, f = 1299.9462505361548
Optimization restart 5/5, f = 1299.9462505359945
[[20.         20.46370457  5.         44.18128765  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.913303677199714

Optimization restart 1/5, f = 1304.1091262508799


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1304.1087725778295
Optimization restart 3/5, f = 1304.1087725769985
Optimization restart 4/5, f = 1304.1087725770058
Optimization restart 5/5, f = 1304.1087725797495
[[20.         19.87790162  5.         48.40332507  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.171022017351687

Optimization restart 1/5, f = 1308.1216033745882


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1308.1215106529448
Optimization restart 3/5, f = 1308.1215096076046
Optimization restart 4/5, f = 1308.1215096077242
Optimization restart 5/5, f = 1308.1215096089425
[[ 7.          8.          5.         56.88777849  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 19.431486670245985

Optimization restart 1/5, f = 1312.5925335806355


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1312.5911126695682
Optimization restart 3/5, f = 1312.5911126490003
Optimization restart 4/5, f = 1312.5911126482172
Optimization restart 5/5, f = 1312.591112649397
[[20.         21.14826426  5.         44.06502132  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.922109955034973

Optimization restart 1/5, f = 1316.5813168869531


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1316.581242734567
Optimization restart 3/5, f = 1316.5812427350786
Optimization restart 4/5, f = 1316.5812427345209
Optimization restart 5/5, f = 1316.5812430012634
[[ 9.         25.          5.         43.42187442  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 18.110975501770966



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1321.0264061711498
Optimization restart 2/5, f = 1321.0249567508429
Optimization restart 3/5, f = 1321.0249567510655
Optimization restart 4/5, f = 1321.0249567782103
Optimization restart 5/5, f = 1321.0249567513324
[[13.          8.         27.         32.20304558  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 45.30290588219934



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1327.1971622025278
Optimization restart 2/5, f = 1327.1816066796387
Optimization restart 3/5, f = 1327.1816067554594
Optimization restart 4/5, f = 1327.1816066756128
Optimization restart 5/5, f = 1327.181606669843
[[20. 25.  5. 70.  3.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.0454656513684935

Optimization restart 1/5, f = 1331.4502938224382


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1331.4501975599965
Optimization restart 3/5, f = 1331.450197561403
Optimization restart 4/5, f = 1331.4501975624507
Optimization restart 5/5, f = 1688.1419557821384
[[20.         18.8539339   5.         63.75363382  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.647284149395864

Optimization restart 1/5, f = 1335.4698017371115


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1335.4696495574103


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = 1583.1539758369809
Optimization restart 4/5, f = 1335.4696495720661
Optimization restart 5/5, f = 1335.4696495775252
[[20.         21.58336479  5.         41.23955055  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.604891264828183

Optimization restart 1/5, f = 1339.4588995887286


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1339.4588830002956
Optimization restart 3/5, f = 1339.4588827924354
Optimization restart 4/5, f = 1339.458882691044
Optimization restart 5/5, f = 1339.458882696376
[[14.         22.56072031  5.         47.02835904  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 12.204603091549911

Optimization restart 1/5, f = 1343.4468139840997


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1343.446801178397
Optimization restart 3/5, f = 1343.446801178143
Optimization restart 4/5, f = 1343.4468011802398
Optimization restart 5/5, f = 1343.446801178509
[[20.  8.  5. 70.  1.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.54770372540081

Optimization restart 1/5, f = 1347.7088543915245


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1347.7086232232527
Optimization restart 3/5, f = 1347.7086232231684


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 4/5, f = 1347.7086232246147
Optimization restart 5/5, f = 1347.708623259845
[[11.          8.         27.         69.17415577  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 16.583121050167843



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1352.1194257555567
Optimization restart 2/5, f = 1352.1191550510164
Optimization restart 3/5, f = 1352.119155050208
Optimization restart 4/5, f = 1352.1191550551375
Optimization restart 5/5, f = 1352.1191550508597
[[ 9.  25.   5.  70.   1.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 9.498267342104846

Optimization restart 1/5, f = 1356.128341973286


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 2/5, f = 1356.1283058155022
Optimization restart 3/5, f = 1356.1283058075055


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1598.8059750254288
Optimization restart 5/5, f = 1356.128305798428
[[20.          8.          5.         65.59556758  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.419574996001713



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1360.0967010477937
Optimization restart 2/5, f = 1360.0966981435133
Optimization restart 3/5, f = 1360.0966981434908
Optimization restart 4/5, f = 1360.0966981436159
Optimization restart 5/5, f = 1360.096698659177
[[20.          8.          5.         65.02796449  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.895724137600902



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1364.009288238335
Optimization restart 2/5, f = 1364.009287072995


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 3/5, f = 1549.9473060976613
Optimization restart 4/5, f = 1364.0092871136653
Optimization restart 5/5, f = 1364.0092870723079
[[20.         21.27048245  5.         48.25724632  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.082702514856788



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1367.8953225632106
Optimization restart 2/5, f = 1367.8953146463814
Optimization restart 3/5, f = 1367.8953146662614
Optimization restart 4/5, f = 1367.895314643291
Optimization restart 5/5, f = 1367.8953146427943
[[20.  25.   5.  70.   3.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.965663954428923

Optimization restart 1/5, f = 1371.916042772752


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1371.916038440647
Optimization restart 3/5, f = 1371.9160384408044
Optimization restart 4/5, f = 1371.9160384446432
Optimization restart 5/5, f = 1371.9160384403503
[[11.  25.   5.  70.   3.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.999837508750645



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1375.8928791906712
Optimization restart 2/5, f = 1375.892878582413
Optimization restart 3/5, f = 1375.8928785823387
Optimization restart 4/5, f = 1375.8928785821497
Optimization restart 5/5, f = 1375.8928785821502
[[20.         21.77346177  5.         65.57884466  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.84507455309405



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1379.8524243558727
Optimization restart 2/5, f = 1379.8524090422793
Optimization restart 3/5, f = 1379.8524090415049
Optimization restart 4/5, f = 1379.8524090471367
Optimization restart 5/5, f = 1379.8524090459523
[[20. 25.  5. 70.  3.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.0454656513684935



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1383.8006250203655
Optimization restart 2/5, f = 1383.800623877694
Optimization restart 3/5, f = 1383.8006238676614
Optimization restart 4/5, f = 1383.8006238703902
Optimization restart 5/5, f = 1383.8006239808258
[[11.  25.   5.  70.   3.   1.5]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.999837508750645



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1387.6912689216847
Optimization restart 2/5, f = 1387.6912687457802
Optimization restart 3/5, f = 1387.691268745813
Optimization restart 4/5, f = 1387.6912687458962
Optimization restart 5/5, f = 1387.691268776561
[[20.         17.31974913  5.         59.60578747  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.562967237644311



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1391.6066355046066


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = 1659.8323187097355
Optimization restart 3/5, f = 1391.6065584044104
Optimization restart 4/5, f = 1391.6065584318953
Optimization restart 5/5, f = 1391.606561858945
[[20.         21.4383799   5.         63.98315402  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.588436514560783



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1395.4716154256407
Optimization restart 2/5, f = 1395.4715769742359
Optimization restart 3/5, f = 1395.4715769817767
Optimization restart 4/5, f = 1395.4715769736224
Optimization restart 5/5, f = 1395.47157697661
[[20.         20.98256926  5.         65.31445953  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.472345519361184

Optimization restart 1/5, f = 1399.2969176623906


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = 1399.3196570722025
Optimization restart 3/5, f = 1399.2969134654584
Optimization restart 4/5, f = 1399.2969141592241
Optimization restart 5/5, f = 1399.296913466156
[[20.         18.69673551  5.         49.90895518  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 7.9064784554612855



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1403.159658359604
Optimization restart 2/5, f = 1403.1596214033684
Optimization restart 3/5, f = 1403.1596214269584
Optimization restart 4/5, f = 1403.1596214375077
Optimization restart 5/5, f = 1403.1596214207239
[[20.         20.66017046  5.         70.          3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.061683085647992

Optimization restart 1/5, f = 1407.0213167699935


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1407.0213110184236
Optimization restart 3/5, f = 1407.0213149091362
Optimization restart 4/5, f = 1407.021311011045
Optimization restart 5/5, f = 1407.0213110112566
[[20.         19.31890814  5.         47.72097853  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 8.04835346595111



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1410.8444164777236
Optimization restart 2/5, f = 1410.844411326582
Optimization restart 3/5, f = 1410.8444113280561
Optimization restart 4/5, f = 1410.844411349147
Optimization restart 5/5, f = 1410.8444113260866
[[20.          8.          5.         64.19820072  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.949387486749738



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1414.7444213513031
Optimization restart 2/5, f = 1414.7444254076677
Optimization restart 3/5, f = 1414.7444211816944
Optimization restart 4/5, f = 1414.7444211805232
Optimization restart 5/5, f = 1414.7444211806198
[[20.         18.5148985   5.         63.75326864  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.554373025032187



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1418.5835603998235
Optimization restart 2/5, f = 1418.5835469917936
Optimization restart 3/5, f = 1418.5835469918543


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 4/5, f = 1572.2419620935252
Optimization restart 5/5, f = 1418.583549687381
[[20.  8.  5. 70.  1.  5.]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 5.54770372540081



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1422.4987532471307
Optimization restart 2/5, f = 1422.498752626461
Optimization restart 3/5, f = 1422.49875261204
Optimization restart 4/5, f = 1422.4987523611821


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square


Optimization restart 5/5, f = 1422.498752360763
[[12.         22.12641583  5.         46.7096287   3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 15.13096414314337

Optimization restart 1/5, f = 1426.479465344331


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 2/5, f = 1426.479451924804
Optimization restart 3/5, f = 1465.6530018395479
Optimization restart 4/5, f = 1426.4794519238505


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 5/5, f = 1691.7868409224584
[[20.         16.40120451  5.         63.11348022  1.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.049309572336506



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1430.2905815485865
Optimization restart 2/5, f = 1430.2905777970932
Optimization restart 3/5, f = 1430.2905778008671
Optimization restart 4/5, f = 1430.290577775644
Optimization restart 5/5, f = 1430.2905778526033
[[ 8.          8.          5.         61.68697709  1.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 15.58546625885294



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1434.3520090314953
Optimization restart 2/5, f = 1434.351924289962
Optimization restart 3/5, f = 1434.3519243043809
Optimization restart 4/5, f = 1434.3519242912816
Optimization restart 5/5, f = 1434.3519242899954
[[20.          8.          5.         63.47758547  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.581907148745653



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1438.2193988703143


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


Optimization restart 2/5, f = 1673.1323028343554
Optimization restart 3/5, f = 1438.219398824935
Optimization restart 4/5, f = 1438.2193988244574
Optimization restart 5/5, f = 1438.2193991414574
[[20.         25.          5.         66.04380617  3.          5.        ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.393258244766027



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1442.0535910945086
Optimization restart 2/5, f = 1442.0535746304545
Optimization restart 3/5, f = 1442.0535744385688
Optimization restart 4/5, f = 1442.0535744384806
Optimization restart 5/5, f = 1442.0535744387325
[[20.         17.94714644  5.         63.42762328  3.          1.5       ]]

User function emissions called with 1 inputs to simulate

Evaluating input: 1 of 1

 Retrying in 1 seconds

Output 6.657298918849945



 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/paramz/transformations.py:111: RuntimeWarning:overflow encountered in expm1


Optimization restart 1/5, f = 1445.8398842901497
Optimization restart 2/5, f = 1445.8398834357058
Optimization restart 3/5, f = 1445.8398834192333
Optimization restart 4/5, f = 1481.0911863997148
Optimization restart 5/5, f = 1445.8687045246434


 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/stationary.py:168: RuntimeWarning:overflow encountered in true_divide
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:52: RuntimeWarning:overflow encountered in square
 /Users/Matteo/opt/anaconda3/envs/ml_and_physical/lib/python3.8/site-packages/GPy/kern/src/rbf.py:76: RuntimeWarning:invalid value encountered in multiply


## Results

In [27]:
parameters_name = ['Size of the grid', 'Speed limit in the net (m/s)', 'Max vehicles speed (m/s)', 'Length of the roads (m)', 'Number of lanes', 'Accelleration (m/s^2)']

### Results on the random initialised emulator

In [40]:
results_random_init = bo_random_init.get_results()

In [41]:
results_random_init_df = pd.DataFrame(results_random_init.minimum_location.reshape(1,-1))
results_random_init_df.columns = parameters_name
results_random_init_df

Size of the grid  Speed limit in the net (m/s)  Max vehicles speed (m/s)  \
0              20.0                           8.0                       5.0   

   Length of the roads (m)  Number of lanes  Accelleration (m/s^2)  
0                     70.0              1.0                    5.0

In [42]:
results_random_init.minimum_value

5.54770372540081

### Results on the experimentally designed emulator with model variance

In [43]:
results_model_variance = bo_model_variance.get_results()

In [44]:
results_random_init_df = pd.DataFrame(results_model_variance.minimum_location.reshape(1,-1))
results_random_init_df.columns = parameters_name
results_random_init_df

Size of the grid  Speed limit in the net (m/s)  Max vehicles speed (m/s)  \
0              20.0                          25.0                       5.0   

   Length of the roads (m)  Number of lanes  Accelleration (m/s^2)  
0                     70.0              1.0                    1.5

In [45]:
results_model_variance.minimum_value

5.469575516984683

### Results on the experimentally designed emulator with integrated variance reduction

In [46]:
results_integrated_variance = bo_integrated_variance.get_results()

In [47]:
results_random_init_df = pd.DataFrame(results_integrated_variance.minimum_location.reshape(1,-1))
results_random_init_df.columns = parameters_name
results_random_init_df

Size of the grid  Speed limit in the net (m/s)  Max vehicles speed (m/s)  \
0              20.0                          25.0                       5.0   

   Length of the roads (m)  Number of lanes  Accelleration (m/s^2)  
0                     70.0              1.0                    1.5

In [48]:
results_integrated_variance.minimum_value

5.469575516984683

## Save stuff

In [26]:
with open(f'bayesian_optimization/bayesian_opt_results/results_random_init_emissions.pkl', "wb") as f:
     pickle.dump(results_random_init, f)

with open(f'bayesian_optimization/bayesian_opt_results/results_model_variance_emissions.pkl', "wb") as f:
     pickle.dump(results_model_variance, f)
        
with open(f'bayesian_optimization/bayesian_opt_results/results_integrated_variance_emissions.pkl', "wb") as f:
     pickle.dump(results_integrated_variance, f)